### ISSUE TITLE
Stand Alone and VST Loading Fails

### ISSUE THREAD

**Issue by jwchamb** [zynaddsubfx/zyn-fusion-issues#1]
Reaper DAW does not display the GUI
FLStudio DAW does not recognize the VST
The stand alone stalls during loading

Windows 7 Ultimate SP1 x64
No external audio or MIDI devices

This is the output from the stand alone.  It stalls at parsing json file:

ZynAddSubFX - Copyright (c) 2002-2013 Nasca Octavian Paul and others
                Copyright (c) 2009-2016 Mark McCurry [active maintainer]
Compiled: Oct  4 2016 18:35:08
This program is free software (GNU GPL v2 or later) and
it comes with ABSOLUTELY NO WARRANTY.

Try 'zynaddsubfx --help' for command-line options.

Sample Rate =           44100
Sound Buffer Size =     256 samples
Internal latency =      5.8 ms
ADsynth Oscil.Size =    1024 samples
lo server running on 12128
[INFO] Nio::start()
Starting Audio: PA
Audio Started
Starting MIDI: NULL
MIDI Started
[INFO] exec-after-init
[INFO] No Windows MIDI Device At id 0
[INFO] No Windows MIDI Device At id 1
[INFO] No Windows MIDI Device At id 2
[INFO] No Windows MIDI Device At id 3
[INFO] No Windows MIDI Device At id 4
[INFO] No Windows MIDI Device At id 5
[INFO] No Windows MIDI Device At id 6
[INFO] No Windows MIDI Device At id 7
[INFO] No Windows MIDI Device At id 8
[INFO] No Windows MIDI Device At id 9
[INFO] startup OSC
[INFO] UI calbacks
[INFO] OSC replay
[INFO] auto_save setup
[INFO] NSM Stuff
[INFO] LASH Stuff
[INFO] Launching Zyn-Fusion...
[INFO] starting subprocess via <zyn-fusion.exe osc.udp://127.0.0.1:12128/>
[INFO] Main Loop...
[INFO:Zyn] setup_pugl()
[INFO:Zyn] zest_tick()
[INFO:Zyn] zest_open()
[INFO:Zyn] Found Assets at C:\Users*\Downloads\zynaddsubfx_3.0_Demo_w64-pac
kage\
[INFO:Zyn] Creating MRuby Interpreter...
[debug] parsing json file

**Comment by fundamental** [comment]
Interesting. I've waited to hear back on what other users have been trying zyn out in and I've seen some people using the UI on windows 7 x64 without issues. I've even seen some users making use of it in reaper on windows 7 x64.

I would recommend redownloading it to see if it somehow got corrupted given that users with relatively similar configurations seem to have it working.

If the error persists, could you elaborate how the standalone stalls?
Mainly I'd want to know if an empty 1181x659 window appears or not.
If that window does appear (empty or not) what is in it?

There's also a chance that this is related to the opengl version on your system.
Could you let me know what that version is? (after searching around it seems like tools like http://www.realtech-vr.com/glview/ are the standard way of finding this out on windows)

**Comment by jwchamb** [comment]
No luck yet getting this to work on this particular laptop.  Might as well close this out.  I might reformat/reinstall or just wait for the OSX version.

**Comment by fundamental** [comment]
Thanks. I'll reopen if there's any newer information available.
