### ISSUE TITLE
When navigating presets, keyboard is focused on "Comments" pane

### ISSUE THREAD

**Issue by badosu** [zynaddsubfx/zyn-fusion-issues#101]
It makes more sense to focus on the virtual keyboard when you select a new preset, otherwise you have to unselect the comments section for each preset you're checking.

**Comment by fundamental** [comment]
Notes for future fix:

At a high level I would say that users would expect different levels of priority for different levels of focus for various widgets. In the case of the bank view and 'qwerty-type' keyboards there would be:
1. The virtual piano keyboard
2. The search field
3. The tags/bank/etc columns
4. The comments field
5. The part name field
6. etc

When changing to this view the user would likely assume that only the high priority widget (1) will receive events and when desired other lower priority fields could be selected. For this view I would say that there would be high priority (1), medium priority (2,3), and low priority (4,5,6) subtypes which may have slightly different focus behavior.

## Obtaining focus

- High priority widgets should receive focus when changing views.
- Medium priority widgets should receive focus on single click and perhaps hover
- Low priority widgets should receive focus on double click

## Losing focus

Mouse hover location may play into this at some stage

- High/Medium priority widgets should retain focus unless another widget takes it
- Low priority widgets should lose focus after a suitable timeout (5s?) or if another takes it

## Event dispatch

- If a high priority widget is active the event is delivered to it first and if unhandled it goes to other high priority, then low priority widgets in order of priority
- If a medium priority widget is active the event is delivered to it first and if unhandled it does to other medium priority widgets in order of priority
- If a low priority widget is active the event is only delivered to that widget

## Other considerations

When changing views there may be a few cases where medium priority widgets appear in visually identical situations and thus the user would expect focus to be retained. There may need to be some workaround to lock the focus on a given xywh box, though it may be simpler to say "when clicking X to transition to Y, the focus switches to X temporarily"

**Comment by fundamental** [comment]
This should be fixed for now, but it will be likely revisited at a later point.
