### ISSUE TITLE
Paid for the plugin, but all "Paid" copies still run in demo mode

### ISSUE THREAD

**Issue by RealmportalMC** [zynaddsubfx/zyn-fusion-issues#107]
Self explanatory. I downloaded from the email link, but zyn still only runs in demo mode

**Comment by fundamental** [comment]
This should only affect the most recent -rc4 version for windows. The mistake has been corrected within the build scripts, so future builds should not be affected. If you are experiencing this issue with another build version, please update this issue.

The next release should be out relatively soon which will not be affected.

**Comment by fundamental** [comment]
Thanks for bearing with the delay. -patch5 is up on gumroad and I've finished off the first few steps for the 3.0.3 packaging process. If there's a problem with 3.0.2-patch5 please reopen this issue.
