### ISSUE TITLE
Log scale for Filter Cuttof in Macro Control

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#113]
I've started experimenting with ZynFusion for live performance and the Macro Control feature is already putting an infinite smile on my face.

One thing I have problem with is when mapping a CC control to a Filter Cuttof - I get a linear frequency scale which is very imprecise in the low end, and provides unneeded resolution in the high end.

I guess it should always work as a Log scale, so probably adding a switch for that in the Macro Control panel is  not a good idea.

PS: I've just noticed that the same problem applies to Filter Q.

**Comment by fundamental** [comment]
On Thu, Oct 19, 2017 at 2:13 PM, unfa <notifications@github.com> wrote:
>
> I've started experimenting with ZynFusion for live performance and the Macro Control feature is already putting an infinite smile on my face.

Excellent


> I guess it should always work as a Log scale, so probably adding a switch for that in the Macro Control panel is not a good idea.

Correct. This should be an automatic part of the automation process.
Currently the OSC API includes metadata which defines if a parameter
should be treated as having linearly spaced values or log space
values, but currently the consumer of the data
rtosc/src/cpp/automations.cpp does not utilize this information.

**Comment by unfa** [comment]
Knock, knock? ;)

**Comment by fundamental** [comment]
I love easy to use metadata. https://github.com/fundamental/rtosc/commit/60399ae0d95c53d2e03931afc10cfd6949e403ba should resolve this request. When you have a chance to test and verify that nothing else in zyn was broken by this quick change I'll close this issue.

**Comment by pdesaulniers** [comment]
Seems resolved for me.

**Comment by fundamental** [comment]
Closing as fixed
