### ISSUE TITLE
Controls that can't be assigned to a macro

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#115]
I've noticed that some controls cannot be assigned to a macro.

- [x] Distortion: Pre-Gain
- [x] Reverb: Decay Time (Dry/Wet works)
- [x] Delay / Echo: Time
- [x] Phaser: Depth

**Comment by fundamental** [comment]
I'm guessing that most effect parameters cannot be assigned at the moment as they appear to be missing min/max limits in the OSC metadata

**Comment by unfa** [comment]
Being able to control the modulation-based effects with Macros would open up amazing possibilities. Right now I use Calf filters afterwards and automate that separately (since they added an option I requested to pause the built-in LFOs and being able to drive them fully manually (with automation).

If I could do this withing ZynAddSubFX - it'd mean I can get much more done live onstage, with Macro Control, without writing complex scripts in Moony to be able to sync CC contorl of multiple plugins together :) Also that makes sounds much more portable and easier to move between Ardour and Carla (essiantially between studio / live environment).

**Comment by JohannesLorenz** [comment]
The missing metadata has been added via 9fcef1cf03878d7da1af35ef2595ebb2de9fafbf .
