### ISSUE TITLE
Macro Control: Gain / Offset not recalled properly in Ardour sessions

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#124]
![image](https://user-images.githubusercontent.com/491704/32700538-e1cf3628-c7c6-11e7-99a8-df998dd920af.png)

I've decided to finally switch to Zyn-Fusion for all my production as much as possible - so expect a lot more bug reports from me :)

Anyway - I've been working on a track and I've noticed after I reloaded Ardour session, my bas sound was different than I had it before saving.

When I looked at the control feedback I've noticed that two distortion effects that should have inverse polarity (macro is crossfading between them) are working in the same polarity - so my Macro Control Gain settings were nor recalled properly (they were drawn in the Macro Control GUI fine, but the sound and the actual knobs in the Effects Rack didn't reflect that - once I touched these, the sound "jumped" to a thing much closer to what I initially made.

I guess the GUI recalls these values fine, but they are not propagated to the synth engine at loading time.

Here's my Ardour session if it'll help.
[Flatout_2017-11-12_163617.zip](https://github.com/zynaddsubfx/zyn-fusion-issues/files/1464813/Flatout_2017-11-12_163617.zip)

The track should sound something like this:
https://youtu.be/JZaT70eNeaY

**Comment by unfa** [comment]
The bug is still kickin' :)

**Comment by fundamental** [comment]
https://github.com/zynaddsubfx/zynaddsubfx/commit/730c93452eca7a78569d1909156b0fc592b1584e should fix this bug

**Comment by unfa** [comment]
Thanks! I guess I should build from source to test it?

**Comment by fundamental** [comment]
That would be ideal. If you haven't used the new fusion build scripts, https://github.com/zynaddsubfx/zyn-fusion-build/wiki/Building-on-Linux provides a nice walkthrough.

**Comment by pdesaulniers** [comment]
Seems fixed for me in Renoise.

**Comment by fundamental** [comment]
Closing as fixed
