### ISSUE TITLE
ADDsynth: Global velocity sensing knob missing?

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#133]
I've noticed this while recording a new video - is there a control present for ADDsynth global velocity sensing in Zyn-Fusion?

**Comment by fundamental** [comment]
Looking at the source it should be the knob labeled "scale" in Add->global->amp->general. This in itself is a bit odd as all other uses seem to use the shortened label "sense".

**Comment by unfa** [comment]
I wouldn't have guessed that "Scale" is the velocity sensing function :)

**Comment by fundamental** [comment]
Updated metadata via https://github.com/zynaddsubfx/zynaddsubfx/commit/6e80dc74dd4ca4a8e20d09ed6150d3b3f2ecd4fc . Next time the osc schema is synced up the short label will be corrected.
