### ISSUE TITLE
Add a modulation volume floating point feedback port

### ISSUE THREAD

**Issue by fundamental** [zynaddsubfx/zyn-fusion-issues#137]
This is the first step in upgrading the parameter resolution of the add synth modulation amount.

First comes the setup.

- Get ZynAddSubFX built (UI doesn't matter yet) on your system using the https://github.com/zynaddsubfx/zynaddsubfx repository
- Get oscprompt built  using the https://github.com/fundamental/oscprompt repository

Now to explore the before change behavior:

- In one terminal start the built zynaddsubfx via "zynaddsubfx -U -P 1337"
- In a second terminal start oscprompt
- In oscprompt connect to zynaddsubfx via "connect 1337"
- The right pane should show a list of zynaddsubfx OSC ports
- Go to the old volume port via "/part0/kit0/adpars/VoicePar0/PFMVolume"
- Hit enter and you should see a value appear in the left pane
- You can update the value as well e.g. "/part0/kit0/adpars/VoicePar0/PFMVolume 12"
- oscprompt can also display metadata associated with a given port, try typing in "/Pvolume"

Now to add onto the existing tools:

- Go to https://github.com/zynaddsubfx/zynaddsubfx/blob/master/src/Params/ADnoteParameters.cpp#L273
- You'll see the definition of a lot of rtosc::Port objects which are defined by {OSC path pattern, port metadata, subports (NULL here), and port callback}.
- Add a new port with the path "FMvolume:" (the single ":" means it accepts OSC messages with only zero arguments)
- Try adding some metadata similar to the long form port definitions nearby
- Make the callback reply with something (e.g. d.reply(d.loc, "f", 0.1234); or d.reply("/some/other/path", "s", "hello world");)
- Recompile and navigate to the new OSC port you created "/part0/kit0/adpars/VoicePar0/FMvolume" in oscpromt and hit enter. You should see the new response that you added

Now for the original task:

- Identify the metadata&data to make the OSC port return 0 to 100 percent with respect to the PFMVolume parmaeter

**Comment by unfa** [comment]
Bump!

**Comment by fundamental** [comment]
Done via https://github.com/zynaddsubfx/zynaddsubfx/commit/463599325216cd6b110914d16163d9304babb337

and 

https://github.com/zynaddsubfx/zynaddsubfx/commit/35574439dc1dacf3a6eb0b513acd640a7dc24fb5
