### ISSUE TITLE
Double click to reset parameters [feature request]

### ISSUE THREAD

**Issue by suhr** [zynaddsubfx/zyn-fusion-issues#14]

**Comment by fundamental** [comment]
This is going to be deferred until the OSC metadata that the zyn backend includes default values. At the moment there's middle click on harmonics, but beyond that I don't think the new UI has reset values encoded yet.

**Comment by fundamental** [comment]
@JohannesLorenz has been working on integrating the metadata. Once that's in place for a reasonable number of parameters the UI should start supporting resetting.

**Comment by fundamental** [comment]
As of https://github.com/mruby-zest/osc-bridge/commit/c4a301b7bc61ecfed654f6b8a60399d416f7a1b1 support for default values have been added to the remote OSC bridge. This doesn't fully describe some of the more complex defaults (e.g. parameter A depends upon parameter B or parameter array A has different values based upon the position within the param array), but it covers quite a few parameters none the less. Next up is adding the double click handler to call br_default()

**Comment by fundamental** [comment]
Double clicking now resets parameters to the default value.
