### ISSUE TITLE
Rename "Morph" modulation to "Mix" modulation?

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#144]
I think that maybe the "Morph" modulation type in ADDsynth could be better described by a name of "Mix" modulation. It's basically mixing between the carrier and the modulator, right?
Or am I missing something?

In the beginning of my ZynAddSubFX usage I thought it's doing something fancy, but it seems to be a simple weighted addition. It can be used to do some cool stuff, but maybe a different name would make it easier for users to grasp?

**Comment by fundamental** [comment]
Unless I'm mistaken it's just a weighted sum (depending upon the volume) between the modulating oscillator and the base oscillator. I'm fine with the renaming.

**Comment by unfa** [comment]
Thanks. Let's do this :)

**Comment by dsheeler** [comment]
Done in: https://github.com/zynaddsubfx/zynaddsubfx/commit/ce6a9ab0ad01352a63cf340676d82e1d8c6500e5

**Comment by unfa** [comment]
Thank you, @dsheeler !

**Comment by dsheeler** [comment]
@unfa: you just reminded me to mention this commit is also necessary to see the "MORPH" -> "MIX" change in the gui: https://github.com/mruby-zest/osc-bridge/commit/e89dd02f0447de3b7aa52ea8739503a53027ce83.  Let me know if you have any problems.
