### ISSUE TITLE
Double-click on any slider in Zyn-Fusion will reset to default - but not for the partials table

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#145]
I think it's a general convention that middle mouse click and double-click reset sliders and knobs to default position. However only the middle click seems to work for these:

![image](https://user-images.githubusercontent.com/491704/38044779-0f537a28-32bb-11e8-998f-2542e86aa744.png)

Is this intentional?

**Comment by fundamental** [comment]
See HarmonicEdit.qml and Valuator.qml

**Comment by dsheeler** [comment]
Fixed via https://github.com/mruby-zest/mruby-zest/commit/7fb54839870e695f0065ab610951723ed7c12221
