### ISSUE TITLE
Display note name and octave when hovering over the virtual keyboard

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#149]
I think it could be useful to have text like C-4, D#-3 etc displayed in the  help area in the top panel, when hovering the mouse over the virtual keyboard keys:

![image](https://user-images.githubusercontent.com/491704/38749651-ad457468-3f52-11e8-9419-573c9e850afd.png)

![image](https://user-images.githubusercontent.com/491704/38749701-d73e3f3e-3f52-11e8-83a5-8be4bb98f15f.png)

**Comment by 18musicians** [comment]
Even more useful if this information contains the midi note number.  I've seen inconsistencies in how octaves are numbered in different DAWs, but midi number is unambiguous. C60, A69, etc.

**Comment by dsheeler** [comment]
Done via https://github.com/mruby-zest/mruby-zest/commit/7fb54839870e695f0065ab610951723ed7c12221
