### ISSUE TITLE
Issue with NSM Session

### ISSUE THREAD

**Issue by sub26nico** [zynaddsubfx/zyn-fusion-issues#150]
#Using ZynAddSubFx (3.0.3) with Non Session Manager or Ray Session, 
ZynFusion's window stay open when I close the session. ZynAdd is closed as expected, 
but ZynFusion won't quit. I have to do it manually. 
If I launch and close NSM in a terminal , ZynFusion is closed with the session.

**Comment by fundamental** [comment]
Anyone who wants to work on a patch for this, the fix should be just killing the subprocess around https://github.com/zynaddsubfx/zynaddsubfx/blob/master/src/main.cpp#L738 . It will likely be a while before I have a chance to work on fixing it myself.

**Comment by dsheeler** [comment]
Done with https://github.com/zynaddsubfx/zynaddsubfx/commit/893a08d546b95679d796625ab3df1fa40843d589

**Comment by sub26nico** [comment]
Sorry for this late answer, I was waiting to can test it. 
It is now done and I can confirm it's working. Thanks @dsheeler .
