### ISSUE TITLE
No text at all in GUI

### ISSUE THREAD

**Issue by ghost** [zynaddsubfx/zyn-fusion-issues#151]
I just build Zyn-Fusion on a fresh Xubuntu 18.04 LTS 64 bit install, following exactly the steps on https://github.com/zynaddsubfx/zyn-fusion-build/wiki/Building-on-Linux. It worked without errors.
The GUI however is missing some essential elements, see the screenshot. I aqlso had the same issue on 16.04 LTS 32 bit.
The console output shows some errors, the last of which repeats when I click someplace.

```
Sample Rate = 		44100
Sound Buffer Size = 	256 samples
Internal latency = 	5.8 ms
ADsynth Oscil.Size = 	1024 samples
lo server running on 15348
[INFO] Nio::start()
Starting Audio: JACK
Jack buffer resized
Audio Started
Starting MIDI: ALSA
MIDI Started
[INFO] exec-after-init
[INFO] startup OSC
[INFO] UI calbacks
[INFO] OSC replay
[INFO] auto_save setup
[INFO] NSM Stuff
[INFO] LASH Stuff
[INFO] Launching Zyn-Fusion...
[INFO] Main Loop...
[INFO:Zyn] setup_pugl()
Info, alsa midi port connected
[INFO:Zyn] zest_tick()
[INFO:Zyn] zest_open()
[INFO:Zyn] Found Assets at /opt/zyn-fusion/
[INFO:Zyn] Starting Zyn-Fusion
[INFO:Zyn] Thanks for supporting the developement of this project
[INFO:Zyn] Creating MRuby Interpreter...
[debug] parsing json file
[debug] json parsed succesfully
Error 00000501 after create tex
Time for a fast load is 10.425ms load(0.028) class(0.004) spawn(10.393)...
making reverse graph[1091]<5.969 ms>
[INFO:Zyn] zest_setup()
[DEBUG:Zyn] setting up animation fps
Error 00000502 after convex fill
Error 00000502 after convex fill
Error 00000502 after convex fill
```

![screenshot_2018-04-30_21-13-08](https://user-images.githubusercontent.com/16050452/39445487-74787e84-4cbb-11e8-81da-148a9df03cbb.png)

**Comment by fundamental** [comment]
Thanks for reporting this issue. The errors that you mention come from within the nanovg library which the zyn-fusion GUI uses. If possible can you see if the issue exists within the demos available via https://github.com/memononen/nanovg ?

**Comment by ghost** [comment]
I am happy to try, but would need some basic instructions. I downloaded the nanovg repository, and I see there is a demo in the examples folder, but how to compile? I suspect `premake4.lua` has to be used, but executing this with lua gave an error `lua: premake4.lua:4: attempt to call global 'solution' (a nil value)`. I have not used lua before.

**Comment by fundamental** [comment]
You need to use premake. More or less what https://github.com/memononen/nanovg/pull/232/commits/d450880eb40ab54507e84e0a6a86a23ceaf0aaac says

**Comment by ghost** [comment]
Thanks (the more recent `README.md` [here](https://github.com/memononen/nanovg) does not show the build instructions).

The outcome is that `example_fbo`,` example_gl3`,` example_gl3_msaa`, and` example_gles3` are not working. The throw an error `GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig` in the console. `example_gl2`, `example_gl2_msaa`, and `example_gles2` work, although they all show a continuously and fast decreasing frame rate.

**Comment by fundamental** [comment]
That sounds like your system may have an old OpenGL implementation. You can confirm this by checking 'glxinfo | grep -i version' and 'glxinfo | grep -i ext_framebuffer'. The Zyn-Fusion interface requires something which is more or less midway between nanovg's example_gl2 and example_fbo. which amounts to an opengl version 2.1+ and the existence of the GL_EXT_framebuffer.

**Comment by ghost** [comment]
I have the brand new Ubuntu 18.04 LTS, but with an older graphics card (GeForce 7200 GS / 7300 SE) using the nouveau driver (nVidia driver seems to be no more available). Is that really not sufficient? The output below seems to indicate that both conditions are fullfilled.
```
$ glxinfo | grep -i version
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Version: 18.0.0
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL version string: 2.1 Mesa 18.0.0-rc5
OpenGL shading language version string: 1.20
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 18.0.0-rc5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```
```
$ glxinfo | grep -i ext_framebuffer
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GL_EXT_framebuffer_blit, GL_EXT_framebuffer_object, 
$ glxinfo | grep -i ext_framebuffer
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GL_EXT_framebuffer_blit, GL_EXT_framebuffer_object, 
```

**Comment by ghost** [comment]
..closed by accident.

**Comment by fundamental** [comment]
Well, that's odd. That GL version info should be absolutely plenty. I do wish that I was better at OpenGL that I could point you to something concrete. 

If you're interested in finding the root cause yourself https://apitrace.github.io/ is the tool I use for OpenGL debugging. To me it sounds like there's a problem in the creation of the font atlas within nanovg's font rendering sub-library. I don't have any idea as to why that's occurring however. The notable difference from the example_gl2 in nanovg is zyn-fusion's use of a few framebuffers. The framebuffers do work though with non-font based draws. Hence my guess as to there being a strange interaction with the font atlas and the frame buffers.

Another thing which might be worth trying is updating the nanovg submodule when you build the zyn-fusion GUI. As you can see from https://github.com/mruby-zest/mruby-zest-build/tree/master/deps the mruby-zest framework that power's zyn-fusion uses a commit from nanovg mid-2016. I've tried to watch the nanovg development for critical fixes, but I may have missed something.

**Comment by ghost** [comment]
I updated now the nanovg sub-module before building Zyn-Fusion to the latest files available on GitHub, but no change in the outcome, still no text.

**Comment by ghost** [comment]
I have now a similar issue of no text in the GUI with [Dragonfly Reverb](https://github.com/michaelwillis/dragonfly-reverb), and in this case the GL version requested is at least 3.0 - maybe that is also the requirement for Zyn-Fusion? My graphics card indeed supports only GL 2.1.

**Comment by ghost** [comment]
@fundamental Given the discovery above, I can now get text into the GUI by requiring software rendering (and accepting the graphics performance reduction)

`LIBGL_ALWAYS_SOFTWARE=1; ./zyn-fusion`

The 'solution' to this bug report thus possibly is that the minimum GL version required from zyn-fusion is somewhat higher than 2.1.
