### ISSUE TITLE
Selection and cursor in text fields

### ISSUE THREAD

**Issue by suhr** [zynaddsubfx/zyn-fusion-issues#16]
For now, there's none.

**Comment by fundamental** [comment]
Agreed, some very basic editing functionality should be added

**Comment by unfa** [comment]
Yup. It's a bit difficult to know what's happening when saving files.

**Comment by fundamental** [comment]
Selection/highlighting/copy/paste/moving-the-cursor is still to-be-done, but the next -rc (3.0.2rc2) includes a cursor to indicate when a text area is active.

**Comment by fundamental** [comment]
Cursor movement and basic editing is now implemented (see https://youtu.be/ioCc0Dik4Wc for an example). I'm going to close this issue for the time being as implementing any copy/paste (for text fields) will likely involve the system clipboard which is a whole new can of worms to deal with.
