### ISSUE TITLE
Macro Control: slot names are lost after reload

### ISSUE THREAD

**Issue by pdesaulniers** [zynaddsubfx/zyn-fusion-issues#173]
I've been able to reproduce this issue in Renoise (VST) and Carla (LV2), using latest zyn built with `build-linux.rb`.

Here's how to reproduce the issue:
- Give slot 0 a name
![2018-07-13-14 14 08](https://user-images.githubusercontent.com/23723605/42707277-ae47a420-86a7-11e8-9e91-b147907fd846.png)
- Save Renoise / Carla project
- Reload project
- The slot name is back to Slot 0
![2018-07-13-14 14 20](https://user-images.githubusercontent.com/23723605/42707468-4e913f0e-86a8-11e8-948f-630cfb92c853.png)

The other parameters (gain, off, midi cc) seem to be recalled correctly. Perhaps I'm misunderstanding this feature? :p

**Comment by fundamental** [comment]
No misunderstanding, the textbox appears to be mapped just fine, but the XML save/load code is missing in zynaddsubfx/src/Misc/Master.cpp . This would be a good first issue for someone looking to get into zyn since it's pretty self contained.

**Comment by pdesaulniers** [comment]
OK, I'll take a look at that.
