### ISSUE TITLE
zynaddsubfx Linux 64 executable quits with error

### ISSUE THREAD

**Issue by romainbar** [zynaddsubfx/zyn-fusion-issues#18]
Launching the zynaddsubfx binary from the zyn-fusion-3.0.0pre.tar.bz2 pacakge yields:

Try 'zynaddsubfx --help' for command-line options.
Cannot lock down 82274202 byte memory area (Cannot allocate memory)

Sample Rate =       48000
Sound Buffer Size =     256 samples
Internal latency =  5.3 ms
ADsynth Oscil.Size =    1024 samples
lo server running on 12940
[INFO] Nio::start()
Starting Audio: JACK
Cannot lock down 82274202 byte memory area (Cannot allocate memory)
Jack buffer resized
Jack reports error: Cannot use real-time scheduling (RR/5)(1: Operation not permitted)
Jack reports error: JackClient::AcquireSelfRealTime error
./zynaddsubfx: symbol lookup error: ./zynaddsubfx: undefined symbol: jack_port_uui

As a wrokaround, starting the installed zynaddsubfx as 'zynaddsubfx -P 1337 -U -I alsa -O jack -a' then zyn-fusion works.

**Comment by romainbar** [comment]
OK, built zynaddsubfx from the latest sources and got a similar error:

Cannot lock down 82274202 byte memory area (Cannot allocate memory)

Sample Rate =       44100
Sound Buffer Size =     256 samples
Internal latency =  5.8 ms
ADsynth Oscil.Size =    1024 samples
lo server running on 12649
[INFO] Nio::start()
Starting Audio: JACK
Cannot lock down 82274202 byte memory area (Cannot allocate memory)
Jack buffer resized
Jack reports error: Cannot use real-time scheduling (RR/5)(1: Operation not permitted)
Jack reports error: JackClient::AcquireSelfRealTime error
Audio Started
Starting MIDI: ALSA
MIDI Started
[INFO] exec-after-init
[INFO] startup OSC
[INFO] UI calbacks
[INFO] OSC replay
[INFO] auto_save setup
[INFO] NSM Stuff
[INFO] LASH Stuff
[INFO] Main Loop...
^CDeactivating and closing JACK client

**Comment by fundamental** [comment]
Those are related to jack's system permissions. Usually that relates to PAM on linux, but that's distro dependent. 
Anyhow, none of those are fatal errors like the one shown in the original post. If you want your compiled zyn to run the zest UI, then in the build directory run "ccmake ." go to GuiModule and change it to "zest".

**Comment by fundamental** [comment]
The new build is now uploaded, check the http://zynaddsubfx.sf.net/demo.html for the updated link
