### ISSUE TITLE
Graph not always updated when tweaking parameters

### ISSUE THREAD

**Issue by pdesaulniers** [zynaddsubfx/zyn-fusion-issues#180]
How to reproduce:

- Go in Subsynth
- Lower the first harmonic slider

You might get this:
![2018-07-17-14 20 22](https://user-images.githubusercontent.com/23723605/42837614-918fd08c-89cc-11e8-911e-e6e19163c18a.png)

If I turn one of the overtone knobs:
![2018-07-17-14 20 49](https://user-images.githubusercontent.com/23723605/42837631-a0568386-89cc-11e8-844f-6f7d820e42ba.png)

This can also be reproduced in the filter tab by turning the cutoff knob pretty fast:
![2018-07-17-14 25 59](https://user-images.githubusercontent.com/23723605/42837900-61570574-89cd-11e8-9452-73a39f8e16d8.png)

Turning Frequency Tracking knob updates the graph:
![2018-07-17-14 26 06](https://user-images.githubusercontent.com/23723605/42837933-7c7120f6-89cd-11e8-840e-ef78b0372188.png)

**Comment by fundamental** [comment]
This issue should now be fixed for the filter visualization and the
subsynth harmonic visualization.

Other locations can be fixed by changing refresh to force_refresh within
the code which fetches the data to be visualized.
Note that force_refresh should *not* be used on normal parameters.

**Comment by fundamental** [comment]
Feel free to reopen if there are further visualizations which need updating.
