### ISSUE TITLE
Possible input values for Windows version?

### ISSUE THREAD

**Issue by Vthyarilops** [zynaddsubfx/zyn-fusion-issues#183]
Hi I have Zynfusion running great under Linux, but under Windows it will not connect to my Input device (Roland USB Midi keyboard) it outputs audio completley fine but the keyboard just won't work. I would use JACK as the input driver but it seems to not want to give me the option of using it as a midi driver. Anyways just wondering the available values for the -I switch, tyvm

**Comment by fundamental** [comment]
The -I flag under windows doesn't actually end up doing anything.
Right now zynaddsubfx tries it's best to find all physical MIDI devices
provided by the windows interface (at startup) and then it tries to
listen for events from all devices.

If you're interested I can point out where the current code exists.

**Comment by Vthyarilops** [comment]
Thank you for the reply and that is good to know so I don't waste my time with that switch, I would be interested to know where that code exists but I'm no programmer and would most likely not be able to do much with it. I still don't understand why Zyn doesn't see my keyboard at all (I actually tried 2 different keyboards with 2 different Windows 7 PC's) since it works fine with ALSA/JACK midi in Linux, I think I might end up using LMMS with the Zynaddsubfx plugin, thank you again.

**Comment by fundamental** [comment]
https://github.com/zynaddsubfx/zynaddsubfx/blob/master/src/main.cpp#L140-L219
is the code in question.

Windows has multiple MIDI APIs with seemingly no rational between which
one should be used and where differences should be expected.
That information might be documented somewhere, but it did not appear to
be documented in the official MS API specifications.

Ideally this code will be modernized at some point with whatever
combination of windows APIs are needed and translated into a
proper input engine which can be selected with -I, but for the time
being the linked code is what's available on windows and it works for
all MIDI devices that I've tested (which doesn't mean that it works for
all devices, but it means I don't have a way of replicating the
problem).

**Comment by Vthyarilops** [comment]
Ok thanks you very much, that is a lot less code than I expected (which is good for me, at least I can attempt to understand it). It's strange that it is not documented better on the MS website, I've tried a Roland USB Midi controller and a keyboard into a generic Chinese MIDI to USB adapter, both just don't function at all in Zynfusion I'm using Windows 7 build 2600 (ya ik it's old and outdated like 0 patches, but it's for offline only use). I'm gonna try out the Zynaddsubfx 2.2.0 build and see if I can get an input, anyways thanks again.

**Comment by Vthyarilops** [comment]
So I tried out LMMS with the Zynaddsubfx plugin and Zynaddsubfx 2.2.0, they both work perfectly fine, I believe the issue is that you can't select the default MIDI device in Zynfusion. In Zynaddsubfx 2.2.0 it defaulted to my Line 6 toneport as Midi 0 (which isn't even a Midi device) so in the setting I selected dev USB 1 and it works fine, is there a way to select the 2nd midi device in Zynfusion? Anyways thanks again for your awesome synth.

**Comment by fundamental** [comment]
As described with previous responses, there is not a mechanism for selecting MIDI devices beyond the default detection on windows. Patches are welcome to improve support there.
