### ISSUE TITLE
Load instrument

### ISSUE THREAD

**Issue by regfaker** [zynaddsubfx/zyn-fusion-issues#186]
When I open Load instrument dialog it shows only empty list with some graphics quirks. See video below https://youtu.be/-fUy5ZM0Zjg
I wanted to buy zyn-fusion but this surprised me.
Thanks

**Comment by fundamental** [comment]
Thanks for the video, as it makes it pretty clear what's going on.
Try starting 'zynaddsubfx' which will launch the zyn-fusion subprocess.

The video that you showed indicates that the zyn-fusion UI is open, but
it does not have a synthesizer core (i.e. the zynaddsubfx) process to
communicate to (which results in all fields being empty or at some other
default state).

**Comment by regfaker** [comment]
Works good. Thanks. zynaddsubfx showed me error where it is clear that I was missing libmxml lib and after that everything works. Ok, I'll be trying this demo and buy after if nothing wrong will appear.
