### ISSUE TITLE
Heavy CPU load

### ISSUE THREAD

**Issue by ctsexton** [zynaddsubfx/zyn-fusion-issues#187]
I'm getting 25-30% CPU load for ZynAddSubFX with the Fusion UI, compared to ~1-3% with the old UI. Note that when I check processes with "top", both zynaddsubfx and zyn-fusion are listed as separate processes - but it is zynaddsubfx showing the heavy load, not zyn-fusion. Is this expected? Running on Arch Linux with Jack2.

**Comment by fundamental** [comment]
That CPU load would be expected if a large number of effects are running
or if a few very heavy notes are being actively played.

With similar IO parameters there should only be a slight difference in
the CPU load of 'zynaddsubfx' between versions.
In this case 'zynaddsubfx' handles the audio synthesis and 'zyn-fusion'
is exclusively the user interface.

If you are concerned about the fusion UI causing overhead, then you
can run the synth headless via 'zynaddsubfx -U' and you should be able
to observe any differences in the CPU load of the audio synthesis
process.

**Comment by ctsexton** [comment]
This was on a very simple patch - and I tried the same patch with both UI versions. Is it possible to install the older interface alongside zyn-fusion and switch between them so I can compare? I had trouble uninstalling zyn-fusion (had to manually remove a few directories) so would prefer to compile and run from a single directory if possible.

**Comment by fundamental** [comment]
On 11-02, Cam Sexton wrote:
> This was on a very simple patch - and I tried the same patch with both UI versions.
> Is it possible to install the older interface alongside zyn-fusion and switch between them so I can compare?

Yes it is.
In one directory clone http://github.com/zynaddsubfx/zynaddsubfx
In another clone http://github.com/mruby-zest/mruby-zest-build

Using cmake configure the first one to generate the fltk UI

Build both dirs.

From here you can run zynaddsubfx -U -P 1234 from the zynaddsubfx repo.
Then you can run from the zynaddsubfx repo
zynaddsubfx-ext-gui osc://localhost:1234 for the fltk UI.
From the mruby-zest-build repo you can run zest osc://localhost:1234 for
the fusion GUI.
The underlying zynaddsubfx binary is virtually identical in both cases.

**Comment by ctsexton** [comment]
Ok great, thankyou. I will run some tests including headless and report here what I find. Interesting that both synth binaries are virtually identical, makes sense obviously.

**Comment by ctsexton** [comment]
OK so I have done some quick tests and have found that it is not the Fusion UI causing the issue. What I did find is that zynaddsubfx cloned from github - regardless running with GUI or headless - is showing a very high CPU usage in 'top' (16-20% when idle, no notes played and initial sine wave patch). 

However, when I install the binary via pacman from here: https://www.archlinux.org/packages/community/x86_64/zynaddsubfx/
CPU usage is <1% when idle. The build date of that package is 2018-06-14 21:24 UTC.

I also tried installing from here: https://aur.archlinux.org/packages/zynaddsubfx-git/
Which, as expected, produced identical results (high CPU usage) to compiling zyn as per fundamental's instructions above.

I don't really know enough to make an educated guess as to what is causing this difference. Maybe some cmake config/compilation options? I didn't change anything in cmake config when I compiled it.

I have "SOLVED" the problem by doing the following:
1. Install "official" Arch zynaddsubfx package from here: https://www.archlinux.org/packages/community/x86_64/zynaddsubfx/
2. Clone mruby-zest-build repo & compile 
3. Run 'zynaddsubfx -U -P 1234'
4. In mruby-zest-build directory, run './zest osc.udp://localhost:1234'
--> That gives both LOW cpu usage for zynaddsubfx & working new Fusion UI.

**Comment by fundamental** [comment]
That sounds like a regression in idle performance between the 3.0.3
release and the current git version.
Could you compile the 3.0.3 version of zynaddsubfx and verify that it
has the same <1% idle CPU present in the arch package?

Based upon the arch package build file they don't use any flags which
should alter the performance characteristics, but having you perform the
compilation of 3.0.3 and test should eliminate any other possible
variables.

If the test verifies there is a regression I should be able to identify
it using git bisect fairly quickly.

Thanks for the investigation.

**Comment by ctsexton** [comment]
I think I have narrowed it down to an issue on my end. I tried compiling the 3.0.3 release from github & also from this sourceforge link: 
https://sourceforge.net/projects/zynaddsubfx/files/

So every time zynaddsubfx is compiled on my machine (whether manually or via AUR), I get the same high CPU problem. So maybe I'm just building it wrong? These are the commands I used to build the 3.0.3 release from github:

1. git clone https://github.com/zynaddsubfx/zynaddsubfx.git
2. cd zynaddsubfx
3. git checkout 797c9a9069c30e682128033c923bac3739e67df1
4. git submodule update --init --recursive
5. mkdir build
6. cd build
7. cmake ..
8. make

Then to run:
1. cd src
2. ./zynaddsubfx

Thanks for your patience! I will be happy to help add to documentation on building zynaddsubfx once I work out what is going on here!

**Comment by fundamental** [comment]
Interesting. I'm not seeing anything particularly notworthy while trying to replicate odd behavior locally. From https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/zynaddsubfx I can see that the GuiModule is set to ntk, which changes the amount of time the main thread spends sleeping slightly, but otherwise things seem plenty stock.

Do you have any odd local CFLAGS/CXXFLAGS or an unusual compiler installed?

Since this relates to building yourself vs the arch package, @dvzrv , do you have any ideas on something which should be double checked?

**Comment by ctsexton** [comment]
I have found the culprit. I noticed in that PKGBUILD file, the 'DDefaultInput' flag is set to jack. My cmake config looked like this:
DefaultInput=alsa
DefaultOutput=jack

Once I changed the input to jack and compiled - no problems!

I compiled with and without changing the flag - massive difference in CPU usage on startup. Then in the version where I did not change the flag, I opened "Nio Settings" and saw that MIDI was set to ALSA while Audio was set to JACK. As soon as I set MIDI to JACK, the CPU usage dropped. 

Solved!

**Comment by ctsexton** [comment]
From zynaddsubfx/src/CMakeLists.txt:
https://github.com/zynaddsubfx/zynaddsubfx/blob/ac451cbd554714cc95a778517d307e3900287077/src/CMakeLists.txt#L127-L141
```
# Give a good guess on the best Input/Output default backends
if (JackEnable)
    SET (DefaultOutput jack CACHE STRING
        "Default Output module: [null, alsa, oss, jack, portaudio]")
    # Override with perhaps more helpful midi backends
    if (AlsaEnable)
        SET (DefaultInput alsa CACHE STRING
            "Default Input module: [null, alsa, oss, jack]")
    elseif (OssEnable)
        SET (DefaultInput oss CACHE STRING
            "Default Input module: [null, alsa, oss, jack]")
    else ()
        SET (DefaultInput jack CACHE STRING
            "Default Input module: [null, alsa, oss, jack]")
    endif ()
```
Why choose ALSA midi over JACK midi? I am not an expert on the differences between the two, but if the user is using JACK for audio do we not assume they are also using it for midi? I use the command `a2jmidid -e -u` to bridge ALSA midi to jack midi - maybe that was the cause of the problem?

**Comment by fundamental** [comment]
> Why choose ALSA midi over JACK midi?

First time users of jack tend to expect to be able to connect physical
MIDI devices without extra setup (from what I've seen in the past).
So, ALSA MIDI, JACK audio made sense as a default.
Users who are making more extensive use of the standalone will
eventually gravitate towards JACK MIDI, JACK audio, though at that point
there is a tendency to spot the difference and change setting or use
shortcuts which change the applications initial MIDI/audio pairing.

**Comment by ctsexton** [comment]
Fair enough, thank you for taking the time to explain and for all your great work on Zyn. Hoping to contribute more as I get familiar with the codebase. Closing issue.
