### ISSUE TITLE
SUBsynth filter view empty if filter LFO selected in another view

### ISSUE THREAD

**Issue by pdesaulniers** [zynaddsubfx/zyn-fusion-issues#198]
To reproduce:
1) Go to PADsynth > envelopes & LFOs > filter > LFO
2) Go to SUBsynth > filter
![2019-01-06-12 08 59](https://user-images.githubusercontent.com/23723605/50739319-736bc300-11ac-11e9-8909-fa877e10f109.png)

**Comment by fundamental** [comment]
https://github.com/mruby-zest/mruby-zest/blob/master/example/ZynSubFilter.qml#L76-L80 needs an else case to fix the invalid :vis pos. This issue might also impact other sub synth views since they don't have any LFO.

**Comment by pdesaulniers** [comment]
Should be fixed by https://github.com/mruby-zest/mruby-zest/commit/5e200b6cac48e8c8fe6a0adb6c4edd17796d024a

The issue doesn't seem to impact the other sub synth views.
