### ISSUE TITLE
storing midi bindings in main menu mixed up

### ISSUE THREAD

**Issue by friedolino78** [zynaddsubfx/zyn-fusion-issues#204]
quite counterintuitive in MainMenu.qml:116

        elsif(opt == "load midi bindins")
            $remote.action("/save_xlz", val)
        elsif(opt == "save midi bindings")
            $remote.action("/load_xlz", val)

**Comment by fundamental** [comment]
Fixed via https://github.com/mruby-zest/mruby-zest/commit/ef5c9317d77f3b8b3ab99bf78a40ffaca04f4831

Thanks for spotting that. I must have tested the functionality via the old UI and via OSC, but not in the new GUI.
