### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by trebmuh** [zynaddsubfx/zyn-fusion-issues#209]
Building a 3.0.4 from the bz2 tarball from sourceforge, I've got those wrong version number:

In the window's decoration (still mentionning 3.0.3):

![zyn](https://user-images.githubusercontent.com/8705846/54495006-6b34b000-48e0-11e9-9ded-6e0d681f2c9b.png)

When clicking on the ZynFusion logo:

![zyn1](https://user-images.githubusercontent.com/8705846/54495007-6b34b000-48e0-11e9-8281-a7261483e908.png)
![zyn2](https://user-images.githubusercontent.com/8705846/54495008-6bcd4680-48e0-11e9-969b-f989b8bb34ce.png)

**Comment by trebmuh** [comment]
Same with building from git head master https://github.com/zynaddsubfx/zynaddsubfx/commit/5829c8c17bd90794723f36c25238ec0f1c8b7e5c

**Comment by fundamental** [comment]
Ah, the title is populated by mruby-zest and the root repository
(mruby-zest-build) which uses that (I think) is using a submodule which is
one or two commits behind the title version id change.

**Comment by unfa** [comment]
I think commit 05a1f4eea816b88a38796e726ba411c982948377 in mruby-zest fixed that.

**Comment by dsheeler** [comment]
Should this get bumped now to 3.0.5, as in, while we develop 3.0.5?

**Comment by fundamental** [comment]
As per https://github.com/zynaddsubfx/zynaddsubfx/blob/master/TODO-release version numbers are typically updated right before the release. I'm not sure that's the best convention for all scenarios, but it is the current approach (when I don't forget to bump a number before creating the tarballs).

**Comment by fundamental** [comment]
If any one wants to sanity check things, at some point today the next release will be tagged, but the official announcement won't be until tomorrow.
