### ISSUE TITLE
Provide all required sources for mruby

### ISSUE THREAD

**Issue by dvzrv** [zynaddsubfx/zyn-fusion-issues#214]
For zynaddsubfx 3.0.5 I was attempting to build the zyn-fusion GUI for the Arch Linux package.
However, during build the mruby setup tries to git clone all of its mgem dependencies.

It would be good to provide them (in their required versions!) with the source of the new interface, as this kind of behavior doesn't work during a package build (e.g. some distributions actively prevent network access to the building container during build) and it's also nothing I would want to promote as a package maintainer, as it generates an absolutely unreproducible package build.

**Comment by Bleuzen** [comment]
Hi, are there any news on this?
Would be really nice to see zyn fusion in arch repos anytime soon.

**Comment by fundamental** [comment]
Resolved via https://github.com/mruby-zest/mruby-zest-build/pull/18
