### ISSUE TITLE
Piano keys light up in a color that doens't match the rest of the UI

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#22]
Right now the pressed keys lit up in green, that doesn't match anything in the new UI.

![zynkeys](https://cloud.githubusercontent.com/assets/491704/20245133/bbdaf592-a99a-11e6-89ea-53a8f37352b4.png)

I sampled a color from the UI and replaced the keys lightup: #52fafe

**Comment by fundamental** [comment]
Fixed
