### ISSUE TITLE
Ghost patches on the bank

### ISSUE THREAD

**Issue by allkhor** [zynaddsubfx/zyn-fusion-issues#223]
https://github.com/zynaddsubfx/zyn-fusion-issues/issues/19  it marked as resolved, but bug reproducible on current master.
![ghost_patches](https://user-images.githubusercontent.com/1049442/58372532-85be8180-7f40-11e9-9ee5-e687bc9da532.gif)
Possible fix it's disable selection on the empty bank.

**Comment by fundamental** [comment]
My current best guess would be the tooltip field not getting cleared at https://github.com/mruby-zest/mruby-zest/blob/master/example/SelColumn.qml#L198-L208

**Comment by allkhor** [comment]
A fix has been merged: https://github.com/mruby-zest/mruby-zest/commit/924a8c7fb17238c0dc24b6b3897f7dee5de854c9
