### ISSUE TITLE
No standalone on MacOS?

### ISSUE THREAD

**Issue by gagarine** [zynaddsubfx/zyn-fusion-issues#224]
I just downloaded and installed the demo from http://zynaddsubfx.sourceforge.net/demo.html on MacOS. I didn't find a standalone version in the /Applications folder. Their is a VST plugin I was able to launch on my daw (REAPER64).

**Comment by fundamental** [comment]
Correct. On OSX due to limited support for native audio/MIDI a standalone can be built but is not distributed with the fusion binaries.

**Comment by gagarine** [comment]
Thanks. Perhaps simply changing the title "Mac users:" to "Mac users (standalone only):" will avoid future confusion.

**Comment by fundamental** [comment]
Resolved via https://github.com/zynaddsubfx/zyn-website/commit/6150941cdee77514c76ad0ed2361d69f2162f13d
