### ISSUE TITLE
Zyn-fusion reporting 1x1 px as its window size

### ISSUE THREAD

**Issue by Spunge** [zynaddsubfx/zyn-fusion-issues#227]
I'm using zyn-fusion & synthpod on Arch linux.

While playing around with the zyn-fusion lv2 plugin, sporadically the GUI window does not show when opening it. This happens as zyn reports 1 px width & 1 px height for it's window size.

For more information, please see the report i filed with synthpod: https://github.com/OpenMusicKontrollers/synthpod/issues/38

**Comment by fundamental** [comment]
I suspect that this issue may be resolved by simply updating the DPF
submodule. If you're interested I can point you to steps of how to test
that.

**Comment by Spunge** [comment]
> If you're interested I can point you to steps of how to test
that.

Please do

**Comment by fundamental** [comment]
You should be able to make a checkout of the zynaddsubfx repo, then cd
DPF, git checkout master (on the DPF submodule), git pull (on the DPF
submodule).
Then you should be able to build ZynAddSubFX with cmake, i.e. go to the
root directory of zyn and mkdir build, cd build, cmake .., ccmake . (to
set GuiModule to 'zest'), and make.
You should be able to swap out the system installed
/opt/zyn-fusion/ZynAddSubFX.lv2/ZynAddSubFX.so with the one built in the
corresponding build dir and that should let you test the impact of a
newer DPF version.

It's possible that there might be some small tweaks needed to code
elsewhere after updating DPF, but if they're needed, they should be
pretty sparse.
