### ISSUE TITLE
Building ZynFusion for WIndows

### ISSUE THREAD

**Issue by Klusterofstars** [zynaddsubfx/zyn-fusion-issues#231]
when I run "build-windows.rb" I get an error 
`git apply ../../mruby-float-patch.patch
error: patch failed: src/backtrace.c:209
error: src/backtrace.c: patch does not apply
ERROR: 'git apply ../../mruby-float-patch.patch' failed`
I have absolutely no idea what this means and I would be very thankful for some assistance

**Comment by fundamental** [comment]
That specific patch needs to be updated to the newer version of the mruby interpreter used. Pull requests are appreciated, though this should be addressed in the medium term.
