### ISSUE TITLE
Carla does not save and load zynfusion settings

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#236]
Carla works fine at saving and loading the old zynaddsubfx settings. However the zynfusion settings are not correctly saved/loaded.,
Carla has a file ending in .carxp where all the settings are saved.
This contains readable xml.
When saved, the Zynfusion section within that file has html entities &lt; and &gt; instead of <> symbols
I suspect that is why it doesn't reload.
I think this is a zynfusion rather than a carla problem.

[CarlaZyn3.carxp.txt](https://github.com/zynaddsubfx/zyn-fusion-issues/files/4486240/CarlaZyn3.carxp.txt)

**Comment by zynmuse** [comment]
The browser has altered the html entities appersand lt; and ampersand gt; in the above

**Comment by fundamental** [comment]
@falkTX anything carla specific that I should know about? Nothing should have changed with the save format with fusion vs non-fusion modes of operation.

**Comment by falkTX** [comment]
is this an issue with carla, or the lv2 in general?
let's try with another host first

nothing I recall changed in carla that would trigger this.

**Comment by fundamental** [comment]
@zynmuse please confirm that this issue also exists in Ardour using the LV2 version.

**Comment by zynmuse** [comment]
I don't have the same problem in Ardour. Ardour saves and loads ZynFusion LV2  settings with no problem.

**Comment by zynmuse** [comment]
Ardour save files appear show the correct < > characters when viewed in an editor. SO that is different to the Carla save file.

**Comment by falkTX** [comment]
the way carla saves the file has nothing to do with it, it has always been that way.
carla just encodes and decodes the reserved characters used in XML, so it does not conflict with the rest of the project

**Comment by zynmuse** [comment]
Carla works well.  It's a great piece of software. The only problem I have is that it isn't able to restore the ZynFusion settings. 
Try running Carla with ZynFusion plugin - load in some patch and check the sound then save Carla, Quit Carla. Start Carla and load your saved configuration and check that ZynFusion is restored with the same patch. If it works for you but not for me then I must have something wrong!
I'm concerned that maybe it's a problem with my setup, but I can't figure out what!
ZynFusion works well in Ardour and saves/restores in Ardour sessions.
If you need me to try anything else to help solve the problem please ask.

**Comment by fundamental** [comment]
Spent some time updating some system dependencies, built a new version of Carla, installed the current zynaddsubfx LV2, and it seems to save/load fine.

**Comment by zynmuse** [comment]
Thanks for trying.
I was working with binaries I got from KXStudio recently.
Maybe I need to update again.
