### ISSUE TITLE
Standalone GUI is only refreshed/drawn when moved beyond edge of the screen (on Windows 10 64bit)

### ISSUE THREAD

**Issue by DerAndere1** [zynaddsubfx/zyn-fusion-issues#245]
Version: source code  (https://github.com/zynaddsubfx/zynaddsubfx/commit/22a5f8da76c16c47c3814eedaec8f9fe0ff4248b
OS: MS Windows 10 64 bit
Build: built natively in release mode on Windows 10 by copying the build repository from https://github.com/zynaddsubfx/zyn-fusion-build/pull/43 or https://github.com/zynaddsubfx/zyn-fusion-build/pull/39 and running build-mingw64.sh from the mingw64 shell of my MSYS2 installation.

Steps:

1. run the zynaddsubfx.exe standalone
-> a console window is opened and the last line printed is: `[INFO:ZYN] zest_tick()`
Then a frame for the ZynFusion GUI is displayed but the content stays black.
2. Drag the ZynFusion frame so that the GUI is (partially/completely) outside of the screen area
3. Drag the ZynFusion frame back to the center of the screen
-> additional log messages are printed to the console:
```
[INFO:Zyn] zest_open()
...
[INFO:Zyn] zest_setup()
[Debug:Zyn] setting up animation fps
```
-> GUI is drawn in those areas that were outside of the screen area in step 2
4. Interact with GUI using the mouse
-> GUI is not refreshed/redrawn
5. Repeat steps 2 + 3
->GUI is only refreshed in those areas that were outside of the screen area in step 2

**Comment by DerAndere1** [comment]
I found this forum thread about a similar Issue with Qt: https://forum.qt.io/topic/51003/window-partially-refreshed/16

**Comment by fundamental** [comment]
I've heard of similar reports on windows. I expect that it's a result of
changing the PUGL version used to interact with platform specific pieces
(in this case the expose action which triggers redrawing).

It's also possible like you've indicated with the thread that it's an
OpenGL issue, though the requirements are fairly mild. Zyn-Fusion
requires OpenGL 2.1+the framebuffer extension.

**Comment by DerAndere1** [comment]
I can confirm that this bug is not present in my Zyn-Fusion build for Windows 64 bit from 29.04.2018 . So a new version of some component is indeed likely causing the issue.

**Comment by fundamental** [comment]
Possibly fixed by https://github.com/mruby-zest/mruby-zest-build/pull/30 if this doesn't resolve, feel free to reopen (we really ought to get around to an updated binary release at some point...)
