### ISSUE TITLE
Crashes on Ableton 10 (Windows 10 64bit)

### ISSUE THREAD

**Issue by Jomme5** [zynaddsubfx/zyn-fusion-issues#251]
VST-plugin crashes when loaded including host(Ableton 10)
os: Windows 10 64 bit

-- Is there a possibility to get a 64 vit version of the originial ZynaddsubFX - with FLTK interface(that was very good, stable, fast never complained about that) without paying 45$ for a bunch of bugs?

Paul Nasca made the most complex part of ZynaddsubFX, then, years later, the UI-guys ask 45$ for their take. Common...

**Comment by fundamental** [comment]
https://www.kvraudio.com/forum/viewtopic.php?f=47&t=268277
