### ISSUE TITLE
Zyn-fusion crashes when trying to abort save instrument

### ISSUE THREAD

**Issue by grammoboy2** [zynaddsubfx/zyn-fusion-issues#252]
Working in NSM (assuming saving instrument, means export from session here), tried to save instrument, hit the x on the window the abort saving, zyn-fusion crashes.

**Comment by fundamental** [comment]
To confirm, this crash can be experienced in a recent git build of the UI?

**Comment by grammoboy2** [comment]
zyn-fusion-build$ git show
commit 59d0c4ee7abf3fe7a1f252a1cf6b0005816f2bf3 (HEAD -> master, origin/master, origin/HEAD)

**Comment by fundamental** [comment]
Looks like the only way I'm seeing this crash reading through the NSM code is if saving happens without an open nsm session. I've added a guarding clause. Let me know if that resolves the issue.

**Comment by fundamental** [comment]
Assuming this issue is resolved.
