### ISSUE TITLE
Addsynth global, you can edit parameters, but only effect when selected

### ISSUE THREAD

**Issue by grammoboy2** [zynaddsubfx/zyn-fusion-issues#254]
![zyn4](https://user-images.githubusercontent.com/378249/101261092-d9fd1100-3734-11eb-9f94-2de8ad3d0746.png)

Having this window open, you can edit any parameter. But when you edit: general -> filter stages, BUT you have 'envelop' instead of 'general' selected with your mouse, changes doesn't seems to be applied.

This is at least unexpected, but I think it's a bug.

**Comment by fundamental** [comment]
I feel like I'm missing something with that description. Can you break things down into a more explicit format like:

```
1. Click this
2. Click this
3. Click and drag this
4. etc

Expected behavior: Y
Actual behavior: Z
```

**Comment by grammoboy2** [comment]
Have this window open (see screenshot), filter section

1. click in the square area of envelope, just next to a knob for instance (you get the shape/graph of envelope)
2. edit stages in the left general square area ( 5 for instance)
3. click in the square area of general (you get the shape/graph of general)
4. now change the stages value with 1 value (4). Look at the shape of the graph. Then set it back to your first edited value (5). See the difference? The first time, it didn't affect anything. 

hth

**Comment by grammoboy2** [comment]
Soundwise, I don't think I hear a change in sound either way. Here the change in sound seems more obvious:

https://youtu.be/XNkUQhU7SZs?t=60

**Comment by grammoboy2** [comment]
Soundwise, I don't think I hear a change in sound either way. Here the change in sound seems more obvious:

https://youtu.be/XNkUQhU7SZs?t=60


I'm trying to replicate that guitar sound in the video. But I can't reach it. Probably me, but I hope the new interface gives me the same sound as the old one :)

[nasca_guitar02.zip](https://github.com/zynaddsubfx/zyn-fusion-issues/files/5647859/nasca_guitar02.zip)

**Comment by grammoboy2** [comment]
With the old interface I hear a difference. I think there is something wrong here with the new interface. I'm still fiddling with that nasca guitar sound. When I've more info, I'll report. 

Edit0: Replicating the sound with the same interface is easier, so there is always a chance I miss a setting with the new interface... But for now, I think there's something wrong

edit1: also this pow setting, seems to give me a different sound then what I remember from yesterday. Could be me using the wrong knob in the new interface... or ...
https://youtu.be/XNkUQhU7SZs?t=87

edit2: Guitar file made with the old interface (of course much easier to find the right knobs and values, because the example video is done with the old interface.
[nasca_guitar02_ntk_interface.zip](https://github.com/zynaddsubfx/zyn-fusion-issues/files/5648958/nasca_guitar02_ntk_interface.zip)

edit3: here is more or less the sound of that whole video
[nasca_guitar02_and_strings_ntk_interface.zip](https://github.com/zynaddsubfx/zyn-fusion-issues/files/5649025/nasca_guitar02_and_strings_ntk_interface.zip)

**Comment by fundamental** [comment]
General note: github does not provide notifications for edits, so unless the edits are well... edits of existing content keep in mind that they may be overlooked.

**Comment by fundamental** [comment]
Everything works locally with the described steps.
