### ISSUE TITLE
[Old idea, new issue?] export to SFZ

### ISSUE THREAD

**Issue by grammoboy2** [zynaddsubfx/zyn-fusion-issues#257]
Stumbled upon a interesting suggestion for improvement by P. Nasca himself on LAC 2005

"Add the posibility to export instruments as wav (or sfz)"

http://lac.zkm.de/2005/slides/paul_octavian_nasca_slides.pdf
page 29

Sfz is still a nice format and with Sfizz on the rise probably. 
https://sfzformat.com/

Whole paper here: http://lac.zkm.de/2005/papers/nasca_octavian_paul.pdf

**Comment by fundamental** [comment]
Given how things have developed it's outside of the scope of the project. PAD synthesis wavetables can be exported, but that's more of a novelty than anything.
