### ISSUE TITLE
[NTK/ FLTK interface] Editing PadSynth gives me a AddSynth window. Knobs give wrong (reversed?) values.

### ISSUE THREAD

**Issue by grammoboy2** [zynaddsubfx/zyn-fusion-issues#258]
I'm editing padsynth, but the window is named addsynth. The first vertical slider knob seems to be in the incorrect position.

The vertical knobs doesn't give me the expected values / graph, which leaves the synth broken I'm afraid. Hm first time I noticed it today.

Confirmed after restarting Zynaddsubfx. 

zynaddsubfx$ git show
commit a789866de4d45a784c1f4d95fcf5a1938347baef (HEAD -> master, origin/master, origin/HEAD)

![zyn_padsynth_addsynth](https://user-images.githubusercontent.com/378249/101292632-0c7c3c00-3811-11eb-9ac9-20e709d79473.png)

![zyn_padsynthknob](https://user-images.githubusercontent.com/378249/101292638-10a85980-3811-11eb-8aab-2cb7f5a9ae30.png)

**Comment by grammoboy2** [comment]
Same issues with the fltk interface.

**Comment by grammoboy2** [comment]
Knobs with wrong settings is also the case for the actual Addsynth window

![addsynthwindow](https://user-images.githubusercontent.com/378249/101348265-a680ca80-388b-11eb-887d-f2af0197052a.png)

**Comment by fundamental** [comment]
You're mentioning knobs plural, but the original issue appears to only note that the first slider appears to be wrong (large negative value rather than large positive value). Are there other controls which appear to be wrong besides that one in particular?

As a general note if something is wrong in the ntk version it should also be wrong in the fltk version (and vice-versa) since each one is a look and feel modification on the same base code.

**Comment by fundamental** [comment]
Issue is replicated and I'm guessing a moderately simple fix. The slider works normally without any OSC feedback, so likely it sends "Hey change this to 32" then the backend says "OK, I've updated it to -32", then the GUI updates the reflected value to -32. Ideally this should have been caught when some of the bits were modified to update those parameters, but sometimes bugs get through.

**Comment by grammoboy2** [comment]
I've posted some issues lately. If I had to prioritize one, it is this one. For now I prefer the old interface, above the new one, all though I see potential benefits in the new one.

**Comment by fundamental** [comment]
Simpler fix than I was thinking. This issue should be resolved.

**Comment by grammoboy2** [comment]
Fix confirmed. Thx!
