### ISSUE TITLE
zyn-fusion build fails

### ISSUE THREAD

**Issue by grammoboy2** [zynaddsubfx/zyn-fusion-issues#261]
Debian testing
following:
https://github.com/zynaddsubfx/zyn-fusion-build/wiki/Building-on-Linux

Scanning dependencies of target ins-test
[ 78%] Building CXX object src/Tests/CMakeFiles/ins-test.dir/InstrumentStats.cpp.o
[ 79%] Linking CXX executable ins-test
[ 79%] Built target ins-test
[ 79%] Generating TriggerTest.cpp
Traceback (most recent call last):
  File "/usr/bin/cxxtestgen", line 3, in <module>
    import cxxtest.cxxtestgen
  File "/usr/share/cxxtest/cxxtest/__init__.py", line 33, in <module>
    from cxxtest.cxxtestgen import *
  File "/usr/share/cxxtest/cxxtest/cxxtestgen.py", line 28, in <module>
    from . import cxxtest_fog
  File "/usr/share/cxxtest/cxxtest/cxxtest_fog.py", line 32
    print("Parsing file "+file, end=' ')
                                   ^
SyntaxError: invalid syntax
make[2]: *** [src/Tests/CMakeFiles/TriggerTest.dir/build.make:81: src/Tests/TriggerTest.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:3022: src/Tests/CMakeFiles/TriggerTest.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
ERROR: 'make' failed

**Comment by fundamental** [comment]
Looks like the problem is debian's fault. cxxtest is loading the installed python version. cxxtest has a variant for python2 and python3. Based upon the above trace debian has decided to install the python3 version of cxxtest but launch the python2 version.

**Comment by grammoboy2** [comment]
Tried to set my system to python 3, but I installed it cause zyn-fusion 
build said and says again now:


[ 99%] Generating MessageTest.cpp
Scanning dependencies of target MessageTest
[ 99%] Building CXX object 
src/Tests/CMakeFiles/MessageTest.dir/MessageTest.cpp.o
[100%] Linking CXX executable MessageTest
[100%] Built target MessageTest
Changing directory to ..
# Building Zest in demo mode
Changing directory to mruby-zest-build
make clean
cd mruby             && MRUBY_CONFIG=../build_config.rb rake clean
Environment is:

false
rm -f 
/home/debian/myhome/develop/zyn-fusion-build/mruby-zest-build/mruby/build/host/mrbgems/mruby-file-stat/config.h
Cleaned up target build folder
cd mruby             && rm -rf build/w64
rm -f package/qml/*.qml
ruby rebuild-fcache.rb
length(IR) = 209
Total time is 410.972275 ms
make
ruby ./rebuild-fcache.rb
length(IR) = 209
Total time is 395.82294099999996 ms
cd deps/nanovg/src   && cc nanovg.c -c -fPIC
ar rc deps/libnanovg.a deps/nanovg/src/*.o
cd deps/pugl         && python2 ./waf configure --no-cairo --static --debug
/bin/sh: 1: python2: not found
make: *** [Makefile:10: all] Error 127
ERROR: 'make' failed

**Comment by fundamental** [comment]
In virtually all distros I've worked with it is possible to have python be mapped to python3 and python2 to be mapped to some python2.7 era version. Python 2 support is being (rightfully so) dropped at this point, so the pugl build will be altered to either update it to python3 or remove the need for python in that stage of the build. There's a user who was asking about the pugl modifications fairly recently, so perhaps that's a work-in-progress, but I'm not sure if that's the case or not.

**Comment by grammoboy2** [comment]
$ sudo update-alternatives --list python
/usr/bin/python3.9

I'm a bit confused about the suggested solution. Maybe because pugl build says me not much. Do I've to wait till the build process of zyn-fusion is updated?

**Comment by pgervais** [comment]
pugl has switched to the Meson build system since January 2021. https://github.com/lv2/pugl/commit/69d5d2adde1d13578a94e8b1934235987cf9b2bd

A possibility would be to upgrade pugl and revisit this ticket.

**Comment by fundamental** [comment]
AFAIK pugl only ends up using python2 for the (untested) MacOS build. So, this issue may be stale.

**Comment by pgervais** [comment]
Indeed, python2 is only used for the Mac build. It looks like reviving the Mac build is worth another ticket.
