### ISSUE TITLE
zynadsubfx can't lanch

### ISSUE THREAD

**Issue by KristijanZic** [zynaddsubfx/zyn-fusion-issues#264]
It crashes when launched and it crashes Ardour with the following output from Ardour on Ubuntu 20.04:
`
$ ardour
WARNING: Your system has a limit for maximum amount of locked memory!
         This might cause Ardour to run out of memory before your system runs
         out of memory. You can view the memory limit with 'ulimit -l', and it
         is normally controlled by /etc/security/limits.conf

Ardour6.3.0~ds0 (built using 6.3.0~ds0-0ubuntu0.20.04.1 and GCC version 9.3.0)
Ardour: [INFO]: Your system is configured to limit Ardour to 1048576 open files
Ardour: [INFO]: Loading system configuration file /etc/ardour6/system_config
Ardour: [INFO]: Loading user configuration file /home/aresminos/.config/ardour6/config
Ardour: [INFO]: CPU vendor: GenuineIntel
Ardour: [INFO]: AVX-capable processor
Ardour: [INFO]: CPU brand: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
Ardour: [INFO]: Using AVX optimized routines
Ardour: [INFO]: Loading plugin meta data file /usr/share/ardour6/plugin_metadata/plugin_tags
Ardour: [INFO]: Loading plugin statistics file /home/aresminos/.config/ardour6/plugin_metadata/plugin_stats
Ardour: [INFO]: Loading default ui configuration file /etc/ardour6/default_ui_config
Ardour: [INFO]: Loading user ui configuration file /home/aresminos/.config/ardour6/ui_config
Ardour: [INFO]: Loading 449 MIDI patches from /usr/share/ardour6/patchfiles
Gtk-Message: 00:58:56.325: Failed to load module "canberra-gtk-module"
Ardour: [INFO]: Loading color file /usr/share/ardour6/themes/dark-ardour.colors
Ardour: [INFO]: Loading ui configuration file /etc/ardour6/clearlooks.rc
Ardour: [INFO]: Loading bindings from /etc/ardour6/ardour.keys
Loading ui configuration file /etc/ardour6/clearlooks.rc
Found nothing along /home/aresminos/.config/ardour6/templates:/usr/share/ardour6/templates
Scanning folders for bundled LV2s: /usr/lib/ardour6/LV2
Set cursor set to default
 loading from /home/aresminos/Music/Ardour/Untitled-2020-12-27-00-59-00 as Untitled-2020-12-27-00-59-00 templ  is_new 1 bp 2
locate took 317 usecs for 1 tracks = 317 per track
locate took 22 usecs for 1 tracks = 22 per track
locate took 20 usecs for 1 tracks = 20 per track
Reading MIDI took 835 microseconds, final size = 0
lo server running on 12585
WARNING: this host does not send sample-rate information for LV2 UIs, using 44100 as fallback (this could be wrong)
[INFO] Opened the zynaddsubfx UI...
[INFO] Ready to run
[INFO:Zyn] zest_open()
[INFO:Zyn] zest_open(osc.udp://127.0.0.1:12585)
[ERROR:Zyn] QML Not Found At "/usr/lib/zynaddsubfx/./qml/MainWindow.qml"...
[ERROR:Zyn] Zyn Fusion Assets Missing, Please Check Install...
Segmentation fault (core dumped)
`

**Comment by fundamental** [comment]
On 12-26, Kristijan Žic wrote:
> [ERROR:Zyn] QML Not Found At "/usr/lib/zynaddsubfx/./qml/MainWindow.qml"...
> [ERROR:Zyn] Zyn Fusion Assets Missing, Please Check Install...

Zyn-Fusion was not correctly installed on your system and is missing
resources necessary to launch.
After those are installed it should at a minimum progress to the next
stage of setup.

**Comment by ghost** [comment]
> Zyn-Fusion was not correctly installed on your system and is missing resources necessary to launch. After those are installed it should at a minimum progress to the next stage of setup.

what resources should i install? i have this same issue with the kxstudio repos

**Comment by KristijanZic** [comment]
It's probably Ubuntu Studio repository issue.
