### ISSUE TITLE
Missing OSC paths

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#271]
Maybe these have been added to the new release?
Part insertion equalizer controls - Freq, Gain and Q are not accessible via OSC on the version I have.

**Comment by fundamental** [comment]
Sounds like you might be using a newer version of the GUI, but an older version of the backend. Is that the case?

**Comment by zynmuse** [comment]
That may have been.
I have since installed the new release candidate.
I hope I now have a compatible front and back end. At least it reports 3.0.6 in the banner!
However now cannot see any of the "effects". The effects screen just shows all 6 panels blank even when I try to enable effects. the panels remain blank so I cannot alter any parameters.
I'm running on manjaro.
I'm not very clever with git. What I did was to modify my build-linux-rb script to tell it to fetch the RC1 versions like below.
I would appreciate any help with this as it could be that I am making a big mistake somewhere! 

It would be really useful if the UI could report the backend version number and indicate any compatibility problems.

Also would be useful if you could give more idiot proof instructions how to install the release candidate.

excerpt from build-linux-rb:
```
def get_zynaddsubfx()
    stage "Getting ZynAddSubFX"
    cmd   "git clone -b 3.0.6-rc1 --depth=1 https://github.com/zynaddsubfx/zynaddsubfx"
    chdir "zynaddsubfx"
    cmd   "git submodule update --init"
    chdir ".."
end
def get_zest()
    stage "Getting Zest"
    #Clone the unreleased UI submodules
    cmd   "git clone -b 3.0.6-rc1 --depth=1 https://github.com/mruby-zest/mruby-zest-build"
    chdir "mruby-zest-build"
    cmd   "git submodule update --init"
    cmd   "ruby rebuild-fcache.rb"
    #cmd   "mv testing-cache.rb src/mruby-widget-lib/mrblib/fcache.rb"
    cmd   "make setup"
    cmd   "make builddep"
    chdir ".."
end
```

**Comment by fundamental** [comment]
> However now cannot see any of the "effects". The effects screen just shows all 6 panels blank even when I try to enable effects. the panels remain blank so I cannot alter any parameters.

Yep, that's the 3.0.6 build. That drawing bug along with 2-3 more similar mistakes have been fixed.


> I'm not very clever with git. What I did was to modify my build-linux-rb script to tell it to fetch the RC1 versions like below.
I would appreciate any help with this as it could be that I am making a big mistake somewhere!

Looks right to me. It's something that ideally the build scripts would be setup to do, but well, they're still overall a sloppy build setup... (my fault)

> It would be really useful if the UI could report the backend version number and indicate any compatibility problems.

I've considered doing it, though I haven't gotten around to doing so. I forget if the backend exposes the version info or not. If not it's pretty trivial to add that port and a bit more involved to add the reporting on the GUI side.

**Comment by zynmuse** [comment]
Yep, that's the 3.0.6 build. That drawing bug along with 2-3 more similar
mistakes have been fixed.
--
How can I pick up those fixes?
I tried cloning the current  master and still has no effects!

**Comment by fundamental** [comment]
The fixes were in a submodule (which I'm ready to get rid of soon) which needed updating. It should be good for you now.

**Comment by zynmuse** [comment]
That's good.
Currently I'm back with an earlier working version, but I'll switch back to the RC1 once the fixes are available.
