### ISSUE TITLE
Saving loading part via osc

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#277]
Is there an OSC message pair to save and to load just one part from/to zynaddsubfx?
I'm hoping for something similar to /save_xmz and /load_xmz but to overwrite just one part rather than all 16 parts?

If not, is it possible for me to delete all parts but one from the xml file and then import it to zynaddsubfx? will that just overwrite the one part that has xml references?

Many thanks
John

**Comment by fundamental** [comment]
/save_xiz:is and /load_xiz:is is what you're looking for arguments are: 
- 0 based index of the part to operate on
- filename to be accessed

**Comment by zynmuse** [comment]
Thank you Mark!
I'll give that a go now.
Are they documented anywhere?

I was checking the "oscdoc" file and was trying to use /load-part and
/part#[0-15]/savexml but I think maybe thet are for internal use?
John

**Comment by zynmuse** [comment]
/save_xiz:is and /load_xiz:is

worked perfectly!

Thank you very much for your prompt help!
John

**Comment by fundamental** [comment]
> Are they documented anywhere?

I don't think so. There's some non-realtime ports which due to how the auto-gen documentation is created are not explicitly listed. The documentation should go into the user manual, but that hasn't been seeing much attention in the past few years.

**Comment by zynmuse** [comment]
OK .
I can't think of any other messages I would need, but sometimes if you know
some feature is available you can see a way to use it!
Thanks
John
