### ISSUE TITLE
How to debug zynaddsubfx

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#279]
I've installed 1.3.6-rc3 and have had it crash for no apparent reason whilst running. This is quite infrequent!
I had similar problems with zynaddsubfx 1.3.5.
I wanted to complile with debugging and run zynaddsubfx using gdb, but the build structure is too complicated for me to understand.
Can someone give me some instructions how to do this.
In return I will provide stack traces whenever I have crashes.

**Comment by fundamental** [comment]
1.3.6-rc3 is not a zyn version that I know about.

**Comment by zynmuse** [comment]
Sorry
3.0.6-rc3

**Comment by zynmuse** [comment]
Numbers confuse me!

**Comment by fundamental** [comment]
I'm guessing you're referring to 3.0.6-rc1. So, a few bugs have been fixed. Likely things should move to a -rc2 as a result. You should be able to build from the zyn-fusion-build repo using the build-linux.rb script (to be replaced by some makefiles later). When it comes to building things you can run the GUI and backend separately. Generally quite helpful for debugging where a problem exists (unless it's LV2/VST2 specific). Per backtraces on the GUI side, there's some upcoming fixes there, but there's "make run" "make gdb" and "make valgrind" targets within the GUI subproject.

**Comment by zynmuse** [comment]
Hello Mark
Sorry for the earlier confusion!

There are -rc2 and -rc3 tags on the github zynaddsubfx site.
I had tried the -rc1 some while back but a problem with some missing osc paths in the effects section prompted me to go back to 
the older 3.0.5 build that I have been using for the past year or more.
I assumed the fixes to -rc1, which you mentioned in an earlier issue I reported, would have now been included in the -rc2 and -rc3 tags.
I thought you would know about  the new release candidates.

I'll see if I already have, or can figure out how to build the targets you mention. When I see a crash I like to be able to gather some stack info if possible!

**Comment by fundamental** [comment]
If it's the backend crashing it should be possible for you to run programs with 'ulimit' setup to allow for core dumps. Then you should be able to run 'gdb /path/to/zynaddsubfx /path/to/core' after the fact. With regards to the GUI after https://github.com/mruby/mruby/pull/5395 we can get full backtraces from the GUI side. All of those are dumped to the command prompt which the program was started in. Of course that is from the more recent versions of the GUI which are after some updates to more recent MRuby versions. (Of note, although the needed changes have been merged upstream we've got to update the built in submodule).

I think this is answered, but if not feel free to reopen.
