### ISSUE TITLE
Request for improvement to drum kit entry screen

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#280]
I find the drum kit screen very hard to use.
One major improvement, which should be easy to implement, would be to include the note name alongside the key number.
Currently each row displays MIn Key and Max Key with values available between 0 and 255.
I would display the note alongside the value . Examples
126 (F#9)
72 (C5)
0 (C-1)

**Comment by fundamental** [comment]
Sounds like a reasonable enhancement. It should be fairly straight forward to implement for someone interested in doing so.

**Comment by zynmuse** [comment]
now implemented
