### ISSUE TITLE
ZynFusion does not accept MIDI PGM change above 10

### ISSUE THREAD

**Issue by phil123456** [zynaddsubfx/zyn-fusion-issues#281]
Hi,

on raspbian (RPI4) Zynfusion (build from repo) receives midi program changes and I see the programs being loaded in the interface

**but it stops at pgm 10** while there are many others programs in the default first bank

also **it does not appear to be reacting on bank changes messages**

thanks for helping me on this

Phil

**Comment by phil123456** [comment]
anyone ? is this project dead ?

**Comment by fundamental** [comment]
Not dead, just low on resources to handle support requests. Last I checked program change works with MSB and LSB changes. I have not personally built on ARM in quite a while. I wouldn't assume that's related to the issue, but I don't have the time to replicate the current vauge bug description myself. Please provide minimal steps to trigger the issue with headless zynaddsubfx on an x86_64 setup and then this issue should be able to proceed forward.
