### ISSUE TITLE
When typing in Zyn-fusion plugin, Ardour reacts to some keys and these don't appear in Zyn

### ISSUE THREAD

**Issue by martinvlk** [zynaddsubfx/zyn-fusion-issues#282]
I use Zyn Fusion 3.0.6 as a plugin in the Ardour DAW (version 6.6).

The problem is that when I want to, say, search for an instrument in Zyn, some keys are used by Ardour and they don't appear in Zyn at all.

The expected behaviour would be for Zyn to capture keypresses as long as focus is in the plugin UI window.

**Comment by mnstine** [comment]
I dont have Ardor loaded so I dont know if this is standard plugin functionality or just in Cakewalk....

I have a button in the right side of the title bar that you click to give all keystrokes to the plugin.

**Comment by fundamental** [comment]
> if this is standard plugin functionality or just in Cakewalk....

Each host has a habit of doing things slightly differently. Sometimes it provides the windowing modes such that system window events are directly handed over and sometimes they're routed through the VST2 API for events. Sometimes you get both and have to deduplicate events.

**Comment by martinvlk** [comment]
@mnstine yeah, now I see there is a little keyboard button in Ardour too - thanks!
