### ISSUE TITLE
Voice Configurations getting Lost

### ISSUE THREAD

**Issue by mnstine** [zynaddsubfx/zyn-fusion-issues#285]
I keep making selections in the Browser for each channel but they do not stay in place.  Sometimes they dissapear sometimes they move up or down.  I saved them in the Cakewalk plugins presets and they dont get saved there.  This is all in the full Windows version.

**Comment by fundamental** [comment]
To the best of my knowledge retaining browser/patch file information was only partially implemented. So I would expect it to do the wrong thing with multiple channel assignment, but generally the right thing with a single channel. For the most part it's a missing feature, but since it's going to be a bit quirky I've also added the bug label.

**Comment by mnstine** [comment]
I think I figured out what is happening here and likely not this plugin.  I have taken all the patch commands out of the midi file and still when I start the file from the begining it seems like it resets the midi voices on all channels.  I figured out how to use the presets which now allows me to reload them after I get it started playing.  I will keep reviewing cakewalk and the midi file to see if I can figure out why this is happening.

**Comment by mnstine** [comment]
VST Plugin Crashed.  Not sure how to debug this but will post it here in case someone else can advise.
![VST Crash](https://user-images.githubusercontent.com/65842646/119917069-6392dc00-bf2b-11eb-9bf1-277f40c66607.png)

[Test_05272021_203218.dmp.txt](https://github.com/zynaddsubfx/zyn-fusion-issues/files/6557597/Test_05272021_203218.dmp.txt)
This file is not a txt file but a dmp file.

**Comment by mnstine** [comment]
I have confirmed the voices are lost when ever Cakewalk goes from stop to play.  If I pause and unpause it keeps the voice mappings.  Also I have confirmed this voice loss when clicking play can happen any where in the midi timeline.  I have confirmed there are no patch changes on any channel in the midi data.  So I do not believe this is related to the midi data but to Cakewalk/Zyn.  I will try later this weekend to try with other midi data.

**Comment by mnstine** [comment]
I have confirmed the same happens with a new MIDI composition when I hit record.  The voice assignment disappears.

**Comment by fundamental** [comment]
This does make me curious about what cakewalk does to 'idle' plugins. With plugin specs it's possible to stop running the audio thread (effectively) when the plugin isn't being supplied with events. Additionally it would be legal for a plugin host to serialize a plugin and unload it if it is not getting used. It sounds like that might be happening as there are a very small number of things which aren't saved and this might be one of those circumstances.

**Comment by mnstine** [comment]
Just to make sure I am not making some newbie mistake... 
To build the latest non release build I should be doing the following?

rm -rf zyn-fusion-build/
git clone https://github.com/zynaddsubfx/zyn-fusion-build
cd zyn-fusion-build/
ruby build-windows.rb 

I found a number of people having the same issue with patches being reset for Cakewalk.   I need to experiment with another DAW.  Need to find a good free one with unlimited tracks.

**Comment by fundamental** [comment]
On 06-14, mnstine wrote:
> Just to make sure I am not making some newbie mistake... 
> To build the latest non release build I should be doing the following?
> 
> rm -rf zyn-fusion-build/
> git clone https://github.com/zynaddsubfx/zyn-fusion-build
> cd zyn-fusion-build/
> ruby build-windows.rb 
> 
> I found a number of people having the same issue with patches being reset for Cakewalk.   I need to experiment with another DAW.  Need to find a good free one with unlimited tracks.

That should be the standard way of running the windows build (cross
compiling from linux). Of note though I'm planning on merging in some
build system updates. (see the open PR on the zyn-fusion-build repo if
you're curious)

They should be pretty much the same with "ruby build-windows.rb"
changing into "make -f Makefile.windows.mk", but otherwise things
remaining the same.

Optimistically I should have a candidate for merging those changes
today, but we'll see which day they replace the old scripts.

**Comment by mnstine** [comment]
This can be closed.  I found I had patch information in the channel setups that was causing it to remap everything at start.  My bad.  Nice synth.  Now I can take all 37 midi tracks, on their own synth channel and put them on an audio track where I can individually tune the EQ add VST plugins etc for each one.  Only thing I dont know is that some of the commercial plugins you can add them (in a particular way) and have Cakewalk create all 16 channels for you.  Not sure what triggers this but would be nice.

Thanks for all the support here.

**Comment by fundamental** [comment]
> and have Cakewalk create all 16 channels for you

That sounds like multi-channel plugin output. I know it's doable for zyn in LV2, but for the other plugin standards I'm not sure how many host specific extensions are involved.
