### ISSUE TITLE
Previous macro slots not cleared when changing presets

### ISSUE THREAD

**Issue by TimG73** [zynaddsubfx/zyn-fusion-issues#286]
Hi, using the LV2 plug-in in either Carla or Ardour, I see that macro slots are not cleared upon change of preset.

Example
Preset A has macro slot 0 bound to say 2 parameters, e.g. effect amount and vol
Preset B has slot 0 bound to a filter cut-off

If preset A is loaded first, it will pull in these bindings and naming of Slot 0. However, if the plugin preset is then changed to preset B, the slot bindings and namings are combined.
The Slot 0 naming remain as the naming from preset A, but over-write if the name is set in preset B, The filter cut-off binding from preset B is appended to the retained bindings of preset A. The result is an ugly combination of current and prior presets that has an undesirable and effectively unpredictable result on the sound.

The selection of a new preset should completely clear down all previous bindings and naming from the previous preset for all 16 slots so that the preset sounds correct and macro assignments work as they did when that preset was saved.

Cheers,
Tim

Zyn-fusion 3.0.5-2

**Comment by fundamental** [comment]
Thanks for pointing out the bug. It should be resolved via https://github.com/zynaddsubfx/zynaddsubfx/commit/9507e7b4745af35312f980467031ff06633dd76b
