### ISSUE TITLE
Portamento not working

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#290]
I tried to use portamento feature and I can't get it to work.
I'm sure it used to work so maybe it is broken?

**Comment by zynmuse** [comment]
Having played around a bit more,
now I have discovered that portamento works in polyphonic mode but not in monophonic mode.
I still think that is a bug!

**Comment by fundamental** [comment]
In legato mode at least portamento only happens when you have A-ON, B-ON, not A-ON, A-OFF, B-ON. The latter case triggers portamento in poly mode. I'd expect mono mode to function like the former.

**Comment by zynmuse** [comment]
I hadn't expected it to work like that. But now you have explained it I can make use of that feature. So in monophonic mode if  I overlap two notes, then I do indeed get the portamento effect. So by overlapping or not overlapping notes I can effectively make portamento work on some notes but not on others. That could be a useful feature that I had not expected!
