### ISSUE TITLE
Recalculating waveform when harmonic parameters changed leaks memory

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#291]
(Built from master the other day, Zyn-Fuson presenting itself as v3.0.6, running on Debian Buster using the self contained application).

Every time APPLY is clicked for instance in the Harmonic Structure tab for the PAD engine, the zynaddsubfx process eats about 0.2% of memory (as shown in top) on my dual core machine with 4 GB of memory. I can't find anything that resets this, for instance I tried loading a new patch from the browser panel.

I noticed this the other day when after playing around with the harmonics parameters the machine started running out of memory, with zynaddsubfx consuming 64% of the available memory, and it started swapping and zyn-fusion getting really slow (although the engine was still responsive to MIDI events and there were no audible glitches).

**Comment by fundamental** [comment]
Confirmed See https://github.com/zynaddsubfx/zynaddsubfx/blob/master/src/Params/PADnoteParameters.cpp#L99 for where the fix needs to be added.

**Comment by polluxsynth** [comment]
Ok, I see it's been an issue for quite some time. I'm assuming it's not a trivial thing to fix?

Putting on my developer hat, is the problem something along the lines that there is no easy way to know when the sample data is to be deallocated; simply deallocating an old table when a new one is generated could be disastrous as it might actually be in use, so some form of usage counter would be necessary as part of the memory management scheme?

**Comment by fundamental** [comment]
It should be pretty trivial to fix, just a forgotten issue. Once the new wavetable is installed, the old one just needs to be returned to the non-realtime thread for deallocation using the "/free" OSC message.

**Comment by polluxsynth** [comment]
Fixed in https://github.com/zynaddsubfx/zynaddsubfx/pull/145 so closing issue.

BTW what does the 'good first issue' actually mean? A good first issue to start with for a newbie wanting to contribute to the code base, or something else?

**Comment by fundamental** [comment]
There are two labels for beginner issues. Good-first-issue generally
indicates low complexity and can be approached by anyone. Roughly I'd say
about 1 hr or less if I was solving a random one. First-timers-only
explicitly walks beginners through the problem, the issue tracker workflow,
parts of the solution, and the contribution workflow. It takes a while to
setup those issues, so they are restricted to first time contributors.
Those easily take an hour or two to simplify the steps, but would only take
an experienced contributor a few minutes to have a done PR. I think there
might be a label to indicate something could be rewritten as a
first-timers-only issue, but I don't recall the label name at the moment.
