### ISSUE TITLE
Adding dll's and banks folder to VST directory in Ableton doesn't show ZynAddSubFX in the "plug-ins" section.

### ISSUE THREAD

**Issue by eindacor** [zynaddsubfx/zyn-fusion-issues#292]
After downloading the paid full version, I copied all of the dll files and the banks directory into my VST folder, yet nothing shows up in the plug-ins section in Ableton even after re-scanning.

**Comment by fundamental** [comment]
The intended usage is copying all files in the .zip download into your VST search path. If that doesn't work I unfortunately don't have any other steps for you to run.

**Comment by eindacor** [comment]
Worked like a charm, thank you!
