### ISSUE TITLE
PAD synth update harmonic structure and harmonic phase without apply button

### ISSUE THREAD

**Issue by muziker** [zynaddsubfx/zyn-fusion-issues#293]
Is it possible to update the harmonic structure and harmonic phase of PAD synth without having to use the apply button? In SUB synth the harmonics and bandwidth can be updated in realtime, which has a lot of performance possibilities. Can PAD synth be developed to do the same?

**Comment by fundamental** [comment]
It is not possible for padsynth to work in that manner. The apply button does have an auto-apply mode, however padsynth wavetables take a considerable amount of time to generate before being usable for audio synthesis.
