### ISSUE TITLE
Strange effect in mixer screen

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#294]
Adjusting a level control in the Mixer screen affects the volume of other channels.
Typically if two channels are both showing above 50% (on the cyan bars) and one is increased towards saturation, the other channel gets audibly quieter.
It didn't used to do this on earlier versions.
I would expect a channel to saturate/clip if it is  too loud, but not affect the other channels.

Furthermore With two channels in use and one panned fully left and the other panned fully right, Increasing the level of the channel that is panned to the left causes the channel that is panned to the right to lower in volume.

I'm using the release 3.0.6-rc3

**Comment by zynmuse** [comment]
Actually I have since found that I was using a master version taken from GitHub on 24 July.
The problem was not evident in the 3.0.6-rc3 version so must have been introduced to the master version since 3.0.6-rc3.
This was my error, and I appreciate that the master version I was using had not yet been part of a release candidate, so may have been in process of debugging!

**Comment by fundamental** [comment]
Just to confirm, this issue is present with the current git HEAD, correct? It sounds like some compressor code is floating around, but I was under the impression that the code was limited to the OSS audio output. I could be wrong though.

**Comment by zynmuse** [comment]
Hi Mark
I did a complete Git Clone of the master on 24 July and Picked up the new version using the makefiles ( rather than CMake).
I was hoping to pick up any recent changes.
The master version on 24 July has this problem.
I'm running this on Linux manjaro on an AMD processor and I'm using Jack.
Hope that helps!
I will try a new clone soon and check if the problem is still present.

**Comment by zynmuse** [comment]
I can confirm this problem is still apparent in the GitHub master as of August 28.

**Comment by friedolino78** [comment]
When I recently did some valgind profiling stumbled upon the compressor code also in JackEngine.
https://github.com/zynaddsubfx/zynaddsubfx/blob/2c8937521bf8566e04b9e31e2d54a049c9722f7d/src/Nio/JackEngine.cpp#L354
`stereoCompressor(synth.samplerate, audio.peaks[0], l, r);`
locally i already removed it. For a permanent solution i think, we should disable it by default but make it a (command line?) option or a global setting.

**Comment by friedolino78** [comment]
> I can confirm this problem is still apparent in the GitHub master as of August 28.

I deactivated the before mentioned StereCompressor in a first step.
Would you please check if this solves your problem in the mixer screen? 

[https://github.com/friedolino78/zynaddsubfx/tree/CompressorAsOption](https://github.com/friedolino78/zynaddsubfx/tree/CompressorAsOption)

**Comment by friedolino78** [comment]
I added a port to make it optional:
[https://github.com/zynaddsubfx/zynaddsubfx/pull/137](https://github.com/zynaddsubfx/zynaddsubfx/pull/137)
and a gui toggle button in zest:
[https://github.com/mruby-zest/mruby-zest-build/pull/59](https://github.com/mruby-zest/mruby-zest-build/pull/59)

**Comment by zynmuse** [comment]
The change to ZynSettings.qml not yet in the github Master that I have just checked out.
The global settings screen is scrambled - all the labels are at the top of the screen.

**Comment by zynmuse** [comment]
This original problem is fixed.
I'm not convinced that the Global Setting "Audio Compressor" switch does anything!

**Comment by friedolino78** [comment]
> This original problem is fixed.
> I'm not convinced that the Global Setting "Audio Compressor" switch does anything!

The global settings take effect only after restart of the backend. They are stored in .zynaddsubfxXML.cfg on backend shutdown and are only evaluated at startup. (an only Audio Compressor and Stereo Swap are wired for now).

**Comment by zynmuse** [comment]
OK thanks. I didn't restart after making the change!
