### ISSUE TITLE
Paraphonic mode

### ISSUE THREAD

**Issue by ampetrosillo** [zynaddsubfx/zyn-fusion-issues#296]
It would be great if Zyn were able to work as a string machine (and/or something in between), with paraphony only for the amplifier or the filter or both. There are some classes of sounds where you would want for instance the release phase of the previous chord to be cut short when a new chord is played. At the moment the workaround to this is using sustain, but for some things paraphony is better.

**Comment by fundamental** [comment]
Thanks for the feature request. Given the current backlog I'm going to have to say that this feature is fairly unlikely to be implemented, so I'm going to close this issue. If you're personally interested in coding something in this domain, let me know and I'll reopen.
