### ISSUE TITLE
Note left hanging

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#297]
Some great improvements have gone into the Master recently. In addition to the Mixer compression problem and the filter punch problem which now appear to have been fixed by Friedolino and fundamental, I now see that the Oscillator screen right hand graph is now animated, which was a bug I reported ages ago and thought it was forgotten!
One new problem is that often a note remains hanging as if the noteoff is being ignored. This happens  with some but not all configurations. I first assumed it may be my problem, but I then found I can get the same problem using the zynfusion virtual piano keyboard.
I haven't yet discovered what parameter causes this effect. I will work on it. I could provide an xiz file if that would be of help.

**Comment by fundamental** [comment]
I personally haven't encountered hanging notes in quite a while. If it's a very recent bug then it could be related to the note latch mode introduced in the past month, but I don't recall seeing anything suspicious in that PR, so I suspect it's something earlier. It might just be some patches with exceptionally long releases, but I'll let you identify steps to replicate before moving this bug forward.

**Comment by friedolino78** [comment]
> Some great improvements have gone into the Master recently. In addition to the Mixer compression problem and the filter punch problem which now appear to have been fixed by Friedolino and fundamental, I now see that the Oscillator screen right hand graph is now animated, which was a bug I reported ages ago and thought it was forgotten!
> One new problem is that often a note remains hanging as if the noteoff is being ignored. This happens with some but not all configurations. I first assumed it may be my problem, but I then found I can get the same problem using the zynfusion virtual piano keyboard.
> I haven't yet discovered what parameter causes this effect. I will work on it. I could provide an xiz file if that would be of help.

i think, that is my fault. The new latch mode is intended to do this. but it should be off by default. i think i missed the initialization of the latchmode variable.

fix is coming.

**Comment by zynmuse** [comment]
I can confirm that I no longer see this problem
