### ISSUE TITLE
It would be helpful to have an operation description in the file browser

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#300]
When clicking on file operations like "Load Instrument", it would be helpful if this would be displayed in the file browser, so that one can quickly verify that one hasn't mis-clicked and chosen the wrong operation. I'm currently trying out running Zynaddsubfx with a touch screen which I find makes editing much more direct, but it makes it easier to mis-click on small menu items, like File operatons.

In general, mis-clicking in the newer GUI its not a problem, it's obvious what has happened and it's just a question on re-clicking, but in cases like this it can be destructive (e.g. overwriting a file instead of loading from it).

**Comment by fundamental** [comment]
Agreed, this would be a reasonable design enhancement.

**Comment by friedolino78** [comment]
https://github.com/mruby-zest/mruby-zest-build/pull/61

**Comment by polluxsynth** [comment]
Tested it, looks good to me FWIW.

**Comment by fundamental** [comment]
Merged
