### ISSUE TITLE
zyn-fusion segfaults

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#301]
Occasionally zyn-fusion segfaults arbitarily; running it under gdb yields the following:

Thread 1 "zyn-fusion" received signal SIGSEGV, Segmentation fault.
__memmove_sse2_unaligned_erms ()
at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:497

(gdb) frame 1
#1 0x00007ffff72f1007 in br_tick (br=0x555555add4b0) at src/bridge.c:888
888 memmove(base, base+N, sizeof(void*)(M-N));
(gdb) l
883 } else {
884 char *base = br->rlimit;
885 int N = br->frame_messages;
886 int M = br->rlimit_len;
887 //printf("[INFO] Shrinking rate limit queue %d=>%d\n", M, M-N);
888 memmove(base, base+N, sizeof(void)(M-N));
889 br->rlimit_len = M-N;
890 }
891 //wait 10ms
892 //usleep(10000);
(gdb) p br->rlimit
$4 = (char **) 0x5555565ef630
(gdb) p base
$5 =
(gdb) p br->frame_messages
$6 = 128
(gdb) p br->rlimit_len
$7 = 126

Looking at the preceding code, this looks like a race, if I understand the code, br->frame_messages is bumped by calling do_send(), so it should never be larger than br->rlimit_len, so if it is, something else must have been calling do_send() in the meantime.

I've got a patch which seems to fix this; not sure how to submit it though.

**Comment by fundamental** [comment]
Before checking the issue tracker to see what's new I think I found this same bug, fixed it and also identified why the backtraces aren't showing up on your end (I forgot to update a submodule with some changes that I got merged upstream). I'll have the fix pushed in a short while and if it doesn't fix things on your end then we'll go with your patch.

**Comment by fundamental** [comment]
The issue should be resolved.

**Comment by polluxsynth** [comment]
I had a quick look, my patch attempted to fix what yours does, but yours is better as it actually counts the number of successful do_sends() (I just replaced the rate limit queue length with the number of messages sent to do_send() in the loop (i.e. the final value of the loop variable i), which doesn't handle all possible cases.

I have one question about your patch though: In the rate limit queue send loop in br_tick(), if do_send() fails, it will actually have put the message on the rate limit queue, so in the final iteration before the break, the last message attempted to be sent from the queue will be duplicated and put at the end of the queue, while still remaining in the queue (as messages_sent won't have been bumped for this entry). I don't know if that's a problem in practice, having a duplicated message like that, but it seems an unnecessary side effect. One solution would be in the loop to check if br->frame_messages >= BR_RATE_LIMIT before calling do_send(), and simply break if that is the case, leaving the message in question where it is in the queue, without duplication.

**Comment by fundamental** [comment]
Ah, that makes better sense than my patch. Just to make sure, you're suggesting:

```
--- a/src/osc-bridge/src/bridge.c
+++ b/src/osc-bridge/src/bridge.c
@@ -296,15 +296,12 @@ static void send_cb(uv_udp_send_t* req, int status)
 //I know that 300 messages within a single frame results in lost packets, so
 //lets identify a reasonable limit of 100 messages per frame
 
-//Returns 0 on success
-//        1 on error (aka the rate limit is reached)
-static int do_send(bridge_t *br, char *buffer, unsigned len)
+static void do_send(bridge_t *br, char *buffer, unsigned len)
 {
     if(br->frame_messages >= BR_RATE_LIMIT) {
         br->rlimit_len++;
         br->rlimit = (char**)realloc(br->rlimit, sizeof(char**)*br->rlimit_len);
         br->rlimit[br->rlimit_len-1] = buffer;
-        return 1;
     }
     br->frame_messages++;
     req_t *request = (req_t*)malloc(sizeof(req_t));
@@ -315,7 +312,6 @@ static int do_send(bridge_t *br, char *buffer, unsigned len)
     uv_ip4_addr(br->address, br->port, &send_addr);
     uv_udp_send(&request->send_req, &br->socket, &buf, 1, (const struct sockaddr *)&send_addr, send_cb);
     uv_run(br->loop, UV_RUN_NOWAIT);
-    return 0;
 }
 
 void osc_request(bridge_t *br, const char *path)
@@ -876,9 +872,10 @@ void br_tick(bridge_t *br)
         int messages_sent = 0;
         for(int i=0; i<br->rlimit_len && i<BR_RATE_LIMIT; ++i) {
             char *msg = br->rlimit[i];
-            //printf("[DEBUG] message = \"%s\"\n", msg);
-            if(do_send(br, msg, rtosc_message_length(msg, -1)))
+            if(br->frame_messages >= BR_RATE_LIMIT)
                 break;
+
+            do_send(br, msg, rtosc_message_length(msg, -1));
             messages_sent++;
         }
         if(messages_sent == br->rlimit_len) {
```

**Comment by polluxsynth** [comment]
Yes, exactly. Except obviously the `return 1` shouldn't be removed completely but reverted to the original `return`.

**Comment by fundamental** [comment]
Great. The patch has been applied.

**Comment by polluxsynth** [comment]
One thing bothers me here: If there are messages arriving to the message queue while the rate limit queue is being processed, this indicates that do_send() needs to have some form of thread safety so it can be called from two places concurrently. It apparently works well enough in practice though, I'm just worried that there's a bug here that will manifest itself very seldomly and wreak havoc in the message queue when it does.

**Comment by fundamental** [comment]
libuv is single threaded, It just happens that when you tell it to do something it might check up on other work it has scheduled for it. So, threading isn't a concern, function re-entrancy is.

**Comment by polluxsynth** [comment]
Ah, good. Thanks for the explanation.
