### ISSUE TITLE
zynaddsubfx engine locks up when CPU load goes over 100% on certain platforms

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#302]
I've built zyn-fusion + zynaddsubfx (commit daa23b3c23384cc8d8a5782e82ea642e95f67058) on two machines, one core i3 (2310M) and one Core2Duo (P8600). When running, on the former machine, when the CPU load gets up to 100% (i.e. playing lots of notes, causing xruns) zynaddsubfx fairly quickly locks up and refuses to do anything. Tried both standalone (with jack, in which case jackd drops the connection) and in Carla (in which the engine in Carla basically freezes, including the CPU meter, and requires a kill -9 to stop it). Both machines are running Debian Buster, so they should be identical from a software point of view.

**Comment by polluxsynth** [comment]
I have noted however, that the thread priorities in htop are different on the two machines. On the i3, zynaddsubfx has two threads with user priority (20), and to real time threads, one at -91, which seems to be handling the sound, as it's CPU goes up when playing, and one at -61 which seems to be idle. On the Core2Duo, the zynaddsubfx thread handling the sound runs at priority -6. The other realtime one is at -61, again idle. So there's a difference. Also, on the former machine, the jackd thread which is consuming CPU time is running at priority -96, whereas on the latter it's at -11. I'm thinking it could be some priority inversion problem, but what exactly causes zynaddsubfx to set it thread priorities in a given way? /etc/security/limits.d/audio.conf are the same on both machines (rtprio 95 and memlock unlimited for the audio user).

**Comment by fundamental** [comment]
> (i.e. playing lots of notes, causing xruns) zynaddsubfx fairly quickly locks up and refuses to do anything

Pretty normal for a realtime application. It keeps working at 100% and as it is repeatedly missing deadlines it's going to take a lot longer than normal for notes to decay away. The panic button should help resolve things, but it might take a bit for it to respond to that button (it gets added to a message queue, so other messages take priority).

> with jack, in which case jackd drops the connection

Normal

> threads

Generally the headless standalone threads should look like:

1. The original thread/middleware worker thread (non-realtime priority)
2. N middleware child threads only spawned for pad synth computation (non-realtime priority)
3. The audio generation/output thread (realtime priority)
4. The midi input thread (realtime priority) note - this can be the same thread as 3 in situations like jack input jack output.

I'd double check and make sure that both machines are running the same input/output combination as the threading setup should be the same if that's identical.

**Comment by polluxsynth** [comment]
Ok, so first of all, the reason for the different priorities is because I'd set the jackd priority to 99 in qjackctl on one of the machines; setting the priority to default there results in the realtime jackd thread running at priority -11 on both machines. And as a consequence, the two zynaddsubfx realtime threads run at priority -6 (I'm assuming this is the audiogeneration thread, as it's CPU goes up as notes are played) and -61 (for the MIDI one then), on both machines now.

First I thought I'd found the problem because of this, but unfortunately it doesn't make a difference to the behavior. On one machine it recovers from xruns, on the other, something locks up. The zynaddsubfx threads keep running at their respective priorities, but with 0% CPU. jackd seems to disconnect it. The UI freezes in the sense that the notes that were playing at the time of the lockup are displayed on the keyboard, and so does the output VU meter. Pressing Panic clears them but doesn't restore normal operation. Apart from that the GUI is responsive; it's as if zynaddsubfx has stopped responding completely, but I think it's a consequence of jack disconnecting it. In fact, there's this message from zynaddsubfx: "Jack reports error: jack_client_thread: zombified - exiting from JACK" . There's no message in the GUI about having lost contact with the engine though, so I'm assuming it is actually still running, just that there are no jack connections and hence no audio (and I guess that affects what the GUI gets in terms of updates regarding the keys and VU meters).

I wonder if there's some setting in qjackctl that I've missed, about rejecting clients which don't respond fast enough, or something like that. I double checked the settings in qjackctl though, and they look identical, as does the resulting jackd command line, as seen in htop.

**Comment by fundamental** [comment]
So if jack doesn't like a child process it zombifies it (I think that's the term). That will mean that the audio output thread will no longer get calls into it. I think for zyn it can be recovered by changing the audio output engine back and forth with the "/io/sink" OSC parameter, though I'm only 80% sure it handles things well after the audio thread is 'broken'.

**Comment by polluxsynth** [comment]
The $100000 question is why jack seems perfectly happy with a crazily overrunning zyn on one machine, but dislikes it on another. Oddly enough, since I rebuilt zyn from master earlier today, I no longer get the message "Jack reports error: jack_client_thread: zombified - exiting from JACK" ; it just disconnects silently.

**Comment by fundamental** [comment]
Jack 1 vs Jack 2? Different settings? There is a no zombie flag for jack which qjackctl might have set.

**Comment by polluxsynth** [comment]
Thanks for the clues. I think the difference comes down to the difference in raw CPU speed on these two platforms (the i3 is actually slightly slower than the Core2Due), coupled with a behavior in ZynSubAddFX that you perhaps can shed some light on.

By default qjackctl sets a timeout (-t) parameter to jackd of 500ms (nitpick: 500 is actually jackd's default so that particular value is not set). On the i3 machine, if I set the timeout to 1000ms, after setting a long release time in the Zyn patch, I can hammer away at the keyboard to my hearts content, eventually there are far too many notes to generate any audio, but I can see in the envelope display that Zyn is still running, albeit slowly. As the notes decay away, it comes back to life. Setting the timeout to the default 500ms causes jackd to zombifiy Zyn as soon as there are more than a few overruns. On the slightly faster Core2Duo machine, 500ms seems to be enough to avoid this.

I initially didn't think the timeout would have anything to do with it, because I was figuring that with a buffer size of 256 and consequentially a latency of 5.8 ms, going just above the limit at which Zyn starts causing xruns would not cause Zyn to use anywhere near 500 ms per buffer, so I thought that the timeout was some form of worst case to detect clients locking up completely.

So it would appear that simply setting the qjackctl timeout to 1000 ms is the solution to this problem. But I'm bewildered as to why this is the case - does Zyn essentially keep processing until it has processed all audio for a given period, but has an internal timeout related to the number of buffers processed after which it returns to jackd no matter what? Something like that would explain the behavior.

On a related note, it would seem beneficial if one could set a maximum number of voices to be used for each part, and Zyn would then to classic voice allocation to see that not more voices were played than specified.

**Comment by fundamental** [comment]
> does Zyn essentially keep processing until it has processed all audio for a given period, but has an internal timeout related to the number of buffers processed after which it returns to jackd no matter what? 

Zyn gets a request from jack to generate X samples of data. It then goes and runs the internal audio generation callback which generates buffersize samples. Typically buffersize==X in jack output modes. Whenever it's done computing those samples it hands them off to jack and waits for jack to pull another block of X samples.

> it would seem beneficial if one could set a maximum number of voices to be used for each part, and Zyn would then to classic voice allocation to see that not more voices were played than specified.

The feature is already there, though it might not fully behave as you'd expect see the "/part0/Pkeylimit" OSC handle for example.

**Comment by polluxsynth** [comment]
> Zyn gets a request from jack to generate X samples of data. It then goes and runs the internal audio generation callback which generates buffersize samples. Typically buffersize==X in jack output modes. Whenever it's done computing those samples it hands them off to jack and waits for jack to pull another block of X samples.

Strange then that this would be able to take more than 500 ms just by causing a few xruns. I instrumented the code, printing out "." at the start of JackEngine::processCallback() and "+" just before exiting the function, expecting to see something take extra long time at some point, 500 ms being clearly noticable compared to the steady stream of ".+" at 5 ms intervals. However this was not the case, when playing more and more notes, there are a few xrun messages, then more, and then a final ".+" and then nothing more. Sometimes an error message is printed when jack zombifies the process but often not. It's likely I just don't know enough about how jack determines if a process is over the limit.

At any rate, it seems that the direct solution to the problem in this issue is to increase the jack timeout; in my specific case from the default 500 ms to 1000 ms. I can't see zyn obviously malfunctioning, so I think the issue should be closed.

> 
> > it would seem beneficial if one could set a maximum number of voices to be used for each part, and Zyn would then to classic voice allocation to see that not more voices were played than specified.
> 
> The feature is already there, though it might not fully behave as you'd expect see the "/part0/Pkeylimit" OSC handle for example.

At a quick glance it looks as if the associated functionality limits the amount of simultaneous keys played, which is not really the same thing, no matter what the limit is set to it won't affect the case when there is a long release and consequently the notes sustain for a long time after the note off event.

There doesn't seem to be a corresponding Pkeylimit parameter in the GUI; is there some form of command line OSC client which permits manually sending and receiving OSC messages?

I guess this would be better discussed in a forum thread so I'll start one to avoid cluttering up this ticket. EDIT: Alternatively, I could submit a separate issue for discussion of simultaneous notes limits.

**Comment by fundamental** [comment]
>  It's likely I just don't know enough about how jack determines if a process is over the limit.

Same. It's been a long time since I've looked at the internals of jack that much.

> is there some form of command line OSC client which permits manually sending and receiving OSC messages?

You're in for a treat if you haven't used this one before https://github.com/fundamental/oscprompt

>  it won't affect the case when there is a long release

Precisely correct. Honestly I'd be fine with it behaving like a more classical note stealing, but when the note allocator was rewritten I mostly tried to keep behavior identical to the old one.

> I guess this would be better discussed in a forum thread so I'll start one to avoid cluttering up this ticket. EDIT: Alternatively, I could submit a separate issue for discussion of simultaneous notes limits.

Your call. For the most part this is the same as anything else to me as it ends up in the same spot in my inbox.

**Comment by polluxsynth** [comment]
> You're in for a treat if you haven't used this one before https://github.com/fundamental/oscprompt

Thanks, I'll have a look at it!

> Precisely correct. Honestly I'd be fine with it behaving like a more classical note stealing, but when the note allocator was rewritten I mostly tried to keep behavior identical to the old one.

I created a new issue for the maximum polyphony thing: https://github.com/zynaddsubfx/zyn-fusion-issues/issues/303

Will close this one as it seems a solution has been reached and there doesn't seem to be anything wrong with zyn.
