### ISSUE TITLE
Settable polyphony limit per part

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#303]
Carried over from this isue: https://github.com/zynaddsubfx/zyn-fusion-issues/issues/302 .

Running zynaddsubfx on my (somewhat antiquated) touchscreen laptop (but which I think is comparable to the Zynthian platform in terms of CPU resources), it's easy when playing a lot of notes to get xruns not so much due the number of simultaneous notes played, but due to the release phase of previous notes consuming CPU time. Apparently it's possibly to set a cap on the number of simultaneous notes played using the "/part0/Pkeylimit" OSC handle, but that doesn't really solve the problem, as it doesn't cap the number of voices sounding, as in a classical voice allocation algorithm on synthesizer with a limited number of voices. Although it wouldn't completely solve the problem of xruns due to large number of voices, it would at least give the user some control over the behavior.

My proposition would be have something along these lines:

- A settable polyphony limit per part, which can be configured in the GUI.
- Implement a classic voice allocation algorithm, whereby currently played voices are silenced when new note-ons are received, according to some prioritization algorithm. 
- E.g. the first voices to be received are those which are in their release phase with the oldest age, followed by those which are held by the sustain pedal, followed by those which are still actively playing. I've noticed other synths (such as the Nordlead) prioritizing notes which are at the extremes of the currently played note range, I think with the philosophy that it's the lowest and highest notes that are most prominent. But those are details.

Thinking a bit too far ahead, I'm wondering if some form of automatic prioritization scheme could be based on the amount of available CPU resources. I.e. measuring the interval and length of the 'process' call from jack, and capping down on the number of played voices depending on the apparent CPU resources.

**Comment by polluxsynth** [comment]
I'll see if I can have a look at this in the coming week, it would be an interesting experiment/challange. I tried out setting Pkeylimit via OSC (using https://github.com/fundamental/oscprompt - excellent tool BTW!) and it seems that the limiting function actually implements voice stealing so there is already a lot in place.

**Comment by polluxsynth** [comment]
A question, while poking around enforceKeyLimit(): what is the difference between kill() and entomb()? The former seems to kill off a voice abruptly, resulting in a slight click, whereas the latter just seems to terminate it silently (it doesn't go through the release phase or anything).

**Comment by fundamental** [comment]
Looking through the routines kill is "deallocate immediately" and entomb is "Bring this to the final life stages (released envelopes and states reflecting that it should not be playing much longer"

**Comment by polluxsynth** [comment]
I think what I'm trying to understand is the logic behind the following snippet in enforceKeyLimit(():

        auto &tk = *to_kill;
        if(tk.released() || tk.sustained())
            kill(*to_kill);
        else
            entomb(*to_kill);

the result being that if the Pkeylimit is reached by holding down more notes than the limit, the stolen voices are entombed, meaning they just go silent, whereas if they are reached by playing and releasing them with the sustain pedal held, the stolen voices are killed, with obvious albeit fairly discrete artifacts in the form of clicks. Is there a reason not to go with entomb() for both cases? I would imagine that the advantage of kill() is that it immediately frees up the DSP resources but I'm not sure that's important here.

**Comment by fundamental** [comment]
What's important varies use case to use case. The primary goal is to keep the key limit with minimal artifacting when possible. Given that notes won't naturally die with long releases there is a need for the hard note killing, but ideally things are more often than not entombed which gives them a chance to fade out quickly. There's more clever ways of dealing with things in regards to checking into notes to see what is the state of various envelopes, but nothing is trivial given the complexity of zyn's patches.

**Comment by polluxsynth** [comment]
In this case it seemed mildly illogical that if I actually hold down more notes than the Pkeylimit, the excessive notes are entombed, but if I hold them with the sustain pedal, they are killed, with audible clicking as a result. Does the note on processing take place in the same thread as the DSP for the synth voices? If not, it would seem that since note limiting takes place after the new note is triggered, if the goal is to minimize the DSP load by keeping the number of voices down, the resources for the new voice(s) have already been allocated by the time the note limiting takes place, regardless if kill or entomb is used.

I've got a working prototype for limiting the number of voices rather than the number of notes played. I see that there is some form of test strategy with automatic tests run during build which I haven't had a look at though. But perhaps I should issue a pull request on what I do have and you can see if seems worth while going on with?

**Comment by polluxsynth** [comment]
Patch series for zyn and zest respectively:
https://github.com/zynaddsubfx/zynaddsubfx/pull/142
https://github.com/mruby-zest/mruby-zest-build/pull/64

**Comment by fundamental** [comment]
> Does the note on processing take place in the same thread as the DSP for the synth voices?

Yes

> But perhaps I should issue a pull request on what I do have and you can see if seems worth while going on with?

Yep, that's going to be the best way forward. You might see there's a few other PRs pending, so there's a bit of a backlog. That just means that I've got to up the daily time that the issue tracker/PRs are getting to catch back up, but that shouldn't take too long to sort out.

**Comment by polluxsynth** [comment]
It struck me that an alternative implementation would be to reuse the voice that is to be stolen, in a similar manner to the way I'm assuming the monophonic modes work. I.e. after identifying which voice is to be stolen, it is not entombed or killed, but simply retriggered with the new parameters. I'll see if I can experiment with that; it would avoid the peak in DSP usage when voices are stolen due to one voice being triggered while the "stolen" one is dying off after having been entombed.

**Comment by fundamental** [comment]
Monophonic mode is a bit weird in that it involves two notes in the pool and hopping between them as new note ids appear. If any of that can be simplified without regression that would be nice.

**Comment by polluxsynth** [comment]
Is that true also for legato mode?

The two voice thing explains why I noted a slightly surprising difference in the behavior when limiting the number of voices to one in monophonic mode, like the release was being cut off prematurely with voice limiting applied in a way that it wasn't when played without voice limiting.

Sounds like it's more complex than I imagined it then. I'll have a look once I get the tests for the ongoing pull request sorted.

**Comment by fundamental** [comment]
> Is that true also for legato mode?

Yep. Legato should always have 2 copies floating around with one being the active and one being the previously active.

**Comment by polluxsynth** [comment]
Interesting. There must be a good reason for this. Instinctively it sounds harder to accomplish a legato mode with two alternating voices that just one.

**Comment by fundamental** [comment]
The easy answer is in regards to the initialization process for notes of different frequencies. It's somewhat complex and for things like add note wavetables it will differ considerably. As a result you need 2 copies of the wavetable at a minimum and I forget which other datastructures this holds true for. As a result I guess it was easier to just have two notes and treat the internals more as a black box, but that's speculation on my part. The merging of mono/legato were before my involvement with this project.

**Comment by polluxsynth** [comment]
Ok, so this is interesting. I've been playing around with the Mono and Legato modes, to start with from a user perspective.

First of all, mono mode is not really mono at all, if you've got a long release you can basically play as many notes as you like. The two things that are 'mono' about the mode is
a) if a note is playing when you play another note, the first one is put in its release state, and
b) if you hold one note done and play another, and then release the second one, the first one is retriggered, sort of like a classic monophonic analog synth with last note priority.

So it's rather cool in its way, because while it's only the last note that is actually in the playing state, all previous notes are in their release state, rather than being killed or entombed, which means that with long release times, you still get the full polyphony of what was played. On the other hand, if the intention is to mimic a monosynth, it doesn't really do that, for the same reason.

In Mono mode, only a single note descriptor is used for each note played. There is no doubling of any sort, which however there is Legato mode.

I noted two distinct things about legato mode. First of all, when playing legato, the wave parameters for the first note played seem to be carried over to the second note, which means that the sonic character is not the same as when playing the second note on its own. For instance, the patch I'm testing with uses the Add synth, and when playing a low note, holding it and then a high one, the resulting sound is much noisier than when the high note is played on its own. Playing a high note and going downwards doesn't incur any severe artefacts for this patch, but the tonal character is different than when the second, low, note is played on its own.

The other thing about legato is that even with portamento disabled, the filter tracking still exhibits portemento! I.e. I can hear the filter slowly opening or closing, related to the Portamento Time setting. I think this is really a bug.

As you mentioned, each note played results in two note descriptors. The second of these has the legatoMirror flag set. Both descriptors are set to PLAYING for the note. Both are apparently necessary, because if I only set one descriptor, every second note played is silent. But it doesn't seem to be the tonal qualities that are the reason for this. More investigation is needed.

Key assignment wise, Legato behaves similarly to Mono in that when a note is released, it is not cut short by killing or entombing it, meaning that playing a lot of staccato notes with long release times result in a lot of voices slowly dying away, again very unlike a classic monosynth. Because two voices are used per note, it means the synth runs out of DSP twice as fast as in other modes. On the other hand, unlike Mono mode, when actually playing legato (i.e. holding one note while playing another), the two assigned voices are apparently reused. In the note pool it looks like the first one is always the non-legato one and the second one is the legatoMirror one.

From a personal perspective, I'd consider putting stolen voices in the release state rather then entombing a bug, as it doesn't mimic the way I'd expect mono modes to work. However, this can easily be accomplished by setting the newly introduced Voice limit parameter to 1. And I would guess that users are accustomed to the current behaviour, so changing the implementation of the existing modes would be viewed as a degradation. Alternatively one could introduce two new modes, "True Mono" and "True Legato", but I guess that would over complicating things.

**Comment by fundamental** [comment]
> First of all, mono mode is not really mono at all,

Preaching to the choir. Mono mode as currently implemented is weird.

> the resulting sound is much noisier than when the high note is played on its own

Likely related to the anti-aliasing implementation within adsynth which bakes antialiasing into the waveform at noteon.

> I think this is really a bug.

Heh, I wouldn't have spotted that one. I almost always have portamento on when noodling about with legato mode.

>  I'd consider putting stolen voices in the release state rather then entombing a bug, as it doesn't mimic the way I'd expect mono modes to work.

I am fine with this sort of change in behavior. At least with the notepool it's easy to make this sort of swap, previously it was a mess of code to change anything with note spawning/state-changing. 

> And I would guess that users are accustomed to the current behaviour, so changing the implementation of the existing modes would be viewed as a degradation.

It's possible, but I would think even those users would recognize they were relying on software doing the 'wrong' thing. There might be the need for another mode to accommodate those situations (i.e. such that loading up the plugin version in a daw doesn't render a radically different song), but in general the 'true-X' modes would be preferable IMO.

**Comment by polluxsynth** [comment]
Thanks for your comments. I can have a look at replacing the release of stolen voices in mono mode with entombment; that should be trivial. OTOH, as I mentioned, the same behavior can be reached by setting a voice limit of 1, assuming the PR for that patch is ok. I think I'll open a separate issue for that in that case however. The 'portamento always on for filter tracking' thing is probably a bit hairier, I haven't looked into the reason for that at all.

I had a late night debugging session studying legato mode last night. (Current gory details in https://github.com/polluxsynth/zynaddsubfx/tree/legato-debug). The patch I was using was using ADsynth only, so more research is needed for the behaviour of the other engines. There is an elaborate fade-over algorithm implemented in the Legato class in SynthNote.cpp which fades over from one of the two legato voices to the other which I believe is intended to implement the algorithm you mentioned so that the waveform parameters are suitable for the new pitch rather than the old one. I'm suspecting that there's a bug here somewhere, because disabling the fade-over mechanism, and only having a single voice in legato mode, reveals first of all that this works fine in itself, but also that the dual voice paradigm doesn't seem to fix the waveform parameters as the same change of tonal properties is evident whether a single voice or two voices are used. And in the two voice mode I've verified that the two voices really are alternated between, by patching out the registration of the second legato voice, with the fade-over algorithm in place; in that case, only every second voices is heard, as is to be expected.

EDIT:
Thinking about this, in a way it's a bit of a loosing battle.

Assume that one is using legato mode, with portamento, which I agree is a common usecase. Let's say the portamento time is rather long. The fade-over between the two legato voices happens fairly quickly, the code mentions 0.0005 * fs, so about half a millisecond (unless the unit is not samples but something else - incidentally, does Zyn have a "k-rate", i.e. a rate at which parameters for filters etc is (re)calculated, which is a set fraction of the sample rate, or does that thing happen at the buffer refill rate, or is there some other strategy?). So when sliding to a new note, there would be two possible strategies: either recalculate the waveform based on the target pitch, which means that there will be a marked and sudden change in harmonic character at the start of the portamento glide up to the new note, which is how I think the code is intended to work, or, we could do what is happening now, i.e. just retain the waveform parameters, meaning that they will not be correct for the target pitch, but at least the transition between pitches will have been without sudden changes. A third alternative would be to recalculate the waveform repeatedly along the way, but I think that would incur zipper artifacts as it is migrated in steps along the way.

**Comment by fundamental** [comment]
> ... And in the two voice mode I've verified that the two voices really are alternated between ...

Yep, sounds like you're understanding the strange dance that the code does exactly. I've mostly only refactored code around the dance to eliminate duplication of code, but not too much to address the underlying weirdness.

> incidentally, does Zyn have a "k-rate", i.e. a rate at which parameters for filters etc is (re)calculated

Yes, though the answer to that has gotten more complicated in this past year. Previously the general rule of thumb was that everything meaningful outside of adsynth modulation was calculated at most once per buffer (between 32 and 256 samples typically with a hard minimum of 8) and then interpolation between computed values is somewhat crude. Now some of the filters get recalculated more often to have smoother filter responses. The easier solution would be to favor filters which have better interpolation characteristics, but then you'd have people confused about the old filters sitting there and whatnot.

> I think the code is intended to work

That would be the intent original intent (I think), whether the intent was accomplished in whole or part is another matter entirely. As per how to smooth out the transition, that's another complicating factor. Certainly if the discontinuity is too audible the current incorrect behavior would be preferable to something popping and hissing at the user though.

> A third alternative would be to recalculate the waveform repeatedly

It's possible, but the add note wavetable computation is reasonably expensive, so retriggering it a bunch would be non-ideal. There's some ongoing work to convert add synth into a precomputed wavetable configuration like pad synth, though it hasn't been merged yet. In those cases then there'd be a more natural sliding across multiple wavetables (each wavetable built for a target frequency+antialiasing cutoff). Somewhat expensive, but it would be effectively the right solution and perhaps the complexity would be avoidable if run in a 2x or 4x oversampling mode.

**Comment by polluxsynth** [comment]
This original topic of this issue has now been fixed in
https://github.com/zynaddsubfx/zynaddsubfx/pull/142
and
https://github.com/mruby-zest/mruby-zest-build/pull/64
so will close this issue. I'll raise a new one for the legato stuff
