### ISSUE TITLE
Volume envelops parameter layout

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#311]
This is a fairly small issue, and possibly mostly a newbie one, but it still bugs me. So I thought I'd bring it up and it can either be fixed or dismissed.

I might have missed some, but basically, there seem to be three basic types of envelopes (when not operated in FREE mode) in Zyn: ADR (filters), AR (pitch) and ADSR (volume including modulation).

For the first two, the 'time' parameters are in the top row, and the 'level' parameters are in the bottom row. However, for the ADSR, the top row has Attack time, Decay time and Sustain level, and the bottom row has the Release time to the left.

I think it would be better (= more consistent and intuitive) if all the 'times' parameters were consistently on the top row and all the 'level' parameters were on the bottom row. It would be a simple matter of swapping Release time for Sustain level for the ADSR envelope.

As a secondary suggestion, since the ADSR envelope type is canonical in synthesizers, I'd suggest putting all for parameters in a row. I think in all panels with ADSR envelopes there's certainly space for this. That way all 'time' parameters are still on the top row, and there is additionality familiarity of having the A-D-S-R parameters beside each other, as for most synthesizer front panels. 

A simple thing to accomplish, but the question is if this would be a good move. I think so, but those used to the interface might find it confusing to have to unlearn the fact that the Release time parameter is not in the same place for all envelopes.

**Comment by fundamental** [comment]
Well, I started out trying to say "Don't people usually put the levels on the top of time?" and after some research I've realized this is 100% Zyn being weird territory. It's almost completely standard for other synths that it's ADSR (time,time,value,time) vertical sliders (if they've got the space) and then it's routed into a single envelope sense value for the input into whatever is getting modulated. Also pretty universally no one has a dedicated envelope always connected into the pitch of the note, that's something which gets patched in. Changing to that style of interface would be far more natural, but somewhat more of a mismatch for what's under the hood and it involves shuffling some features into the more advanced mode. I could see it as overall beneficial. 

I could go either way based upon how such a change shuffles around extra parameters such that they're still accessible, but more out of the way when they're significantly less common (e.g. think about how few people use the pitch envelope in more advanced modes).

![quick-env](https://user-images.githubusercontent.com/766621/135880064-48fa3a5f-f9c0-4fed-9ea5-3babe744cf15.png)
 though.

**Comment by polluxsynth** [comment]
> Well, I started out trying to say "Don't people usually put the levels on the top of time?" and after some research I've realized this is 100% Zyn being weird territory. It's almost completely standard for other synths that it's ADSR (time,time,value,time) vertical sliders (if they've got the space) and then it's routed into a single envelope sense value for the input into whatever is getting modulated. 

Well, in this case I was aiming for consistency within Zyn with a minimum of changes to avoid disrupting users' familiarity, I  agree that having the levels in the top row would be more ... logical? intuitive? as somehow the concept would then be "here's a level, and below that is the time it takes to get there" for each vertical pair of level-time parameters.

I agree that for ADSR type envelopes (including ones with a one or two more stages) have all the controls in line, either horizontally (most common) or occasionally vertically (Korg MS-20 for instance, but its front panel is dressed up to look modular in appearence). The Zyn envelopes bring to mind the filter envelopes in the Yamaha CS-80, which are a variant of the ADSR, with five parameters: Initial level, Attack level, Attack time, Decay time, Release time. (http://www.cs80.com/pix/CSR80panel2.jpg, http://www.cs80.com/pix/CSR80panel3.jpg). (The envelope concept is different from Zyn though, with the initial level being settable from 0 to some negative value, and the attack level from 0 to some positive value, so not nearly as flexible.)

But in Zyn I think having all the filter envelope parameters in line would make the envelope parameters too cluttered with the controls having to be made smaller to fit.

A synth with a similar envelope concept as Zyn would be the Yamaha DX7, which has four levels and four rates. The DX7 doesn't have a knobby front panel of course, but the Dexed DX7 emulator has the envelopes in a 2 row by 4 column matrix with the levels on top: https://www.kvraudio.com/product/dexed-by-digital-suburban. At least one other DX7 editor I found during a quick search had the rates on top and levels below though: https://mididesigner.com/qa/3160/layout-yamaha-dx7-tx7 .

I actually find Zyn's way of having for instance the filter envelope have separate level parameters for each segment to be refreshingly different from the standard ADSR configuration. It's familiar enough to be instantly understandable, yet different enough to trigger slightly different thought processes.

Whether the sense knob for the envelope amount fed to the filter is part of the envelope panel or the filter panel in my experience is a 50-50 thing. Certainly, if you look at a Prophet-5 or Minimoog which are the archetypes for analog synths, the envelope amount is in the same panel/box/zone as the rest of the filter controls such as frequency and Q.

> Also pretty universally no one has a dedicated envelope always connected into the pitch of the note, that's something which gets patched in. Changing to that style of interface would be far more natural, but somewhat more of a mismatch for what's under the hood and it involves shuffling some features into the more advanced mode. I could see it as overall beneficial.

Do you mean you'd rather have a patchable envelope generator of sorts? IMHO, the fact that Zyn has dedicated envelopes I think is one of its large plus points: Rather than having a complex modulation matrix that makes it hard to determine what is actually going on in terms of modulation, everything for a given aspect of the sound (filter, envelope, pitch) is all on a single panel. And there is already an on/off switch for the pitch envelope so it can easily be disabled.

The way I see it, the idea of having a small number of patchable envelopes was originally a limitation brought on in hardware synths to reduce component count (and consequentially, size, weight and most importantly price). On a digital synth envelopes are very cheap in terms of DSP resources, so there's no technical reason to limit the number of envelopes, however, with either a knobby interface or with single parameter access, minimizing the number of modulators reduces either the panel space, or the number of menus needed to find everthing, so there's still a reason to minimize the envelope (and LFO for that matter) count. In a synth like Zyn for instance with its excellent panel based interface, there's no need to limit either the number of envelopes or the number of parameters, as doing that would make the interface more convoluted. "Ya' want to modulate yer pitch, well it's there right in front of ya'."

> I could go either way based upon how such a change shuffles around extra parameters such that they're still accessible, but more out of the way when they're significantly less common (e.g. think about how few people use the pitch envelope in more advanced modes).

When the FREE mode is switched on, don't the knobs become essentially unusable? So they should really be crossed over in that mode I suppose.

As for having a dedicated pitch envelope, the thing with that is that it's always there, I was playing with a patch the other day and just dragged the pitch attack level up a bit and it really had an interesting effect on the sonic character. The current paradigm invites the user to try that sort of thing, rather than the more long winded route of "let's see, if I wanted to try modulating the pitch I'd have to find a free envelope, then patch it in to the pitch in this voice". There are doubtlessly a lot of synths that do it this way (in the realm of softsynth the Vember Surge is one that comes to mind), but I find Zyn refreshingly different and at the same inviting because of this.

(As might be hinted from the above, I'm not fond of modulation matrixes. I guess it's a personal thing, but to me, the best synths are those were there is a well designed architecture that after a learning curve allows the user to interact with the instrument on an intuitive level. Examples would be classic instruments like the Minimoog, Prophet-5 or CS80 In contrast, IMHO modulation matrixes are a bit of a cop-out on the part of the designer - "I couldn't come up with a good architecture, so I'll leave it up to you guys". When looking at the front panel or parameters for such a machine, you really don't know how anything is connected until you dive into the mod matrix and build a mental image of what the architecture looks like for the current patch. So with Zyn, I immediately felt that the synth had been _designed_ rather than just a number of random modules thrown together with a pretty user interface.)

My suggestion at this point given the discussion so far would be to leave the filter and pitch envelopes as they are, as that seems to be the way it's laid out for synths that have similar types of envelopes (i.e. multi-stage with a time and level for each stage), such as the DX7, or rather, editors for it) possibly swapping the level and time rows as I think it's a trifle more intuitive (but I'd feel sorry for existing power users who have etched the knob layout into their heads), but going with the classic ADSR layout (all four knobs in a row) for the volume and modulation envelopes for the sake of familiarity.  

EDIT: But if I understand what you were driving it, you were hinting at a) replacing all envelopes with ADSR to get away from the weirdness of the existing types, and b) moving the pitch envelope out of sight, having it patchable when needed?

**Comment by fundamental** [comment]
> But in Zyn I think having all the filter envelope parameters in line would make the envelope parameters too cluttered with the controls having to be made smaller to fit.

Agreed.

> A synth with a similar envelope concept as Zyn would be the Yamaha DX7, which has four levels and four rates. The DX7 doesn't have a knobby front panel of course, but the Dexed DX7 emulator has the envelopes in a 2 row by 4 column matrix with the levels on top: https://www.kvraudio.com/product/dexed-by-digital-suburban. At least one other DX7 editor I found during a quick search had the rates on top and levels below though: https://mididesigner.com/qa/3160/layout-yamaha-dx7-tx7 .

Good hunting for prior work :)

> Do you mean you'd rather have a patchable envelope generator of sorts?

If Zyn was designed today that's what would likely have happened. Not saying it's intrinsically better, but it's how things have shifted. I wouldn't say we should necessarily change things to work that way. In this issue I'm mostly spitballing about the various design choices.

> On a digital synth envelopes are very cheap in terms of DSP resources, so there's no technical reason to limit the number of envelopes, however, with either a knobby interface or with single parameter access, minimizing the number of modulators reduces either the panel space, or the number of menus needed to find everthing, so there's still a reason to minimize the envelope (and LFO for that matter) count.

Agreed.

> In a synth like Zyn for instance with its excellent panel based interface, there's no need to limit either the number of envelopes or the number of parameters, as doing that would make the interface more convoluted. "Ya' want to modulate yer pitch, well it's there right in front of ya'."

I personally find the interface to be quite fun, though there's always complaints about the various design choices which shuffle controls around, put them in different tabs, etc. It's pretty darn tricky to change things and be confident that it's an objectively better design choice.

> When the FREE mode is switched on, don't the knobs become essentially unusable? So they should really be crossed over in that mode I suppose.

Once you've added another set point that's the case (which is the only time you really need free mode anyhow). Until that's done the changes in the envelope graph should propagate backwards to the knobs. Once free mode is engaged then the knobs should be disabled (and they really need a better drawing routine for the disabled state). Alternatively the panel could be replaced with something other than the knobs such that there aren't disabled controls, but something which immediately hints that the envelope is going to behave differently. Hard to say which one would feel more natural to users. Adding the disabled state is certainly the easier option from an implementation perspective.

> I find Zyn refreshingly different and at the same inviting because of this.

This is a core element of creative tool UX IMO. Different design choices with how a user interacts with a tool means that the tool is used to produce different outputs even if the underlying functionality is effectively the same. It's the 'every problem looks like a nail if you only have a hammer' sort of idea, but on a much more complex and nuanced scale.

> As might be hinted from the above, I'm not fond of modulation matrixes.

In a sense my mental model of zyn is a feed forward modulation matrix with just all options having something already connected. A strictly feedforward one is reasonably simple and in the case of some of zyn, it could be a simplifying tool in terms of showing where modulation exists rather than adding anything new. No right answer to this though.

> My suggestion at this point given the discussion so far would be to leave the filter and pitch envelopes as they are, as that seems to be the way it's laid out for synths that have similar types of envelopes (i.e. multi-stage with a time and level for each stage), such as the DX7, or rather, editors for it) possibly swapping the level and time rows as I think it's a trifle more intuitive (but I'd feel sorry for existing power users who have etched the knob layout into their heads), but going with the classic ADSR layout (all four knobs in a row) for the volume and modulation envelopes for the sake of familiarity.

Seems reasonable. Low complexity of the modifications, easy for users to get used to things, and slightly more intuitive for new users.

> EDIT: But if I understand what you were driving it, you were hinting at a) replacing all envelopes with ADSR to get away from the weirdness of the existing types, and b) moving the pitch envelope out of sight, having it patchable when needed?

That's all more spitballing rather than any fixed plan of work. I'm kept pretty busy with just managing bugs and new standalone features. That sort of rearchitecting is something that I haven't done for a while. Feel free to ignore those comments that I made before.

**Comment by polluxsynth** [comment]
In the end, after the thorough discussion above, this resulted in a mere rearrangement of the parameters for ADSR envelopes (mruby-zest commit b74e7119e494e43e7b9374113f72fbf49afb4911), so closing the issue.
