### ISSUE TITLE
Master build zynaddsubfx currently broken

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#318]
Having started from scratch cloning master as per build instructions for linux. Build fails while trying to build zynaddsubfx due to missing file:

[ 77%] Building CXX object src/Plugin/ZynAddSubFX/CMakeFiles/ZynAddSubFX_vst.dir/__/__/__/DPF/distrho/DistrhoPluginMain.cpp.o
In file included from /JohnsMounts/PDevelopmentB/ZynAddSubFx_SourceCode/Master/src/zynaddsubfx/DPF/distrho/src/../../dgl/src/WindowPrivateData.hpp:24,
                 from /JohnsMounts/PDevelopmentB/ZynAddSubFx_SourceCode/Master/src/zynaddsubfx/DPF/distrho/src/DistrhoUIPrivateData.hpp:26,
                 from /JohnsMounts/PDevelopmentB/ZynAddSubFx_SourceCode/Master/src/zynaddsubfx/DPF/distrho/src/DistrhoUIInternal.hpp:20,
                 from /JohnsMounts/PDevelopmentB/ZynAddSubFx_SourceCode/Master/src/zynaddsubfx/DPF/distrho/src/DistrhoPluginVST2.cpp:31,
                 from /JohnsMounts/PDevelopmentB/ZynAddSubFx_SourceCode/Master/src/zynaddsubfx/DPF/distrho/DistrhoPluginMain.cpp:29:
/JohnsMounts/PDevelopmentB/ZynAddSubFx_SourceCode/Master/src/zynaddsubfx/DPF/distrho/src/../../dgl/src/pugl.hpp:44:10: fatal error: pugl-upstream/include/pugl/pugl.h: No such file or directory
   44 | #include "pugl-upstream/include/pugl/pugl.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by fundamental** [comment]
submodules now need to have a recursive initialization. I would have liked to avoid that, but it's part of the DPF update.

**Comment by zynmuse** [comment]
Ive added  --recursive 4 times in Common.mk
	git submodule update --init --recursive

Compiles OK and runs now. Thanks
