### ISSUE TITLE
Zynaddsubfx using more CPU resources than before

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#320]
I had a fairly heavy sequence/composition driving zynaddsubfx. I noticed lots of X-runs and sounds missing and slowing down.
I checked my sysmon and (I have 16 cores) Core 1 was at 100%. All other cores were barely above zero.
Zynaddsubfx was using 6% of total cpu time. Much more that anything else.

I tried powering down the system and starting just essential processes but still the same problem.

I decided to go back to an earlier version of the master.  With the same test this used about 30% of core 1 and ran perfectly.

Looking at the dates of my master copies.
Something has changed between 10 September and 4 October clones to make zynaddsubfx significantly more resource hungry!
while performing the same task.

I'm aware that this could be something I am doing, but I'm looking for suggestions!

**Comment by fundamental** [comment]
Thanks for reaching out with this sort of issue. You can do things like using git bisect or even faster, run a profiler on the known fast version and the known slow version. Comparing the two should show which component now takes more time and then git logs on that component should highlight the source of the regression. The profiler I use tends to be valgrind + kcachegrind.

**Comment by zynmuse** [comment]
Thank you for the ideas. I'll look in to both your options and try to get a better handle on this.

**Comment by zynmuse** [comment]
FYI I spent some time using the profiler. It was hard make a sensible comparison as both versions ran at different speeds and valgrind slowed down both. The newer version slowed  so much that very little sound made it's way to the speaker!

The cpu heavy functions were in the area of reverberation, chorus and effects.

I couldn't make a lot of progress with git versions.
I tried building earlier branches in the zynaddsubfx folder, but compilation failed due to a DPF compile error. I think the DPF library was updated recently and older versions would not build. I was getting in too deep for my understanding so decided to give up.

Finally I have cloned the current Master again and compiled it (I think leaving out the -g flags). zynaddsubfx runs with about 50% cpu usage (of one core). The other cores are barely used. I can't be certain if some of my past  changes to assist in debugging were responsible for the slowing down.

This leads me to a question.
I have a processor with 8 cores (16 threads).
Is there any reason why zynaddsubfx appears to use just one CPU thread?
Maybe this is down  to some configuration of my system!

**Comment by zynmuse** [comment]
I'm sure my original problem was caused by a combination of debugging compiled in to the sources, and one zyn part that was generating a quick sequence of notes with a long envelope resulting in many notes being processed together. Sorting out that has reduced core loading and now it does appear that other cores are being used when that composition is being played.

**Comment by fundamental** [comment]
No problem at all. Generally my approach is running valgrind --tool=callgrind zynaddsubfx -I null -O null running through the patch expecting a bunch of lag and then seeing where the heavy hitters are in kcachegrind. As per thread usage, the only major multithreading in zyn is when padsynth wavetables are calculated. Otherwise you have the worker thread for general non-realtime computation and the single realtime thread for audio generation.
