### ISSUE TITLE
Zynaddsubfx osc loading

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#321]
Hi
This is just a question.

Has anyone done any tests with zynaddsubfx on a typical system to determine the frequency of osc messages that can be handled without any lost messages, slowing down etc...

I currently have a problem which most likely results from the frequency of messages that I am sending to zynaddsubfx.

There must be a limit and I'm sure that depends on system parameters and cpu speed etc....
But there must be a ball park figure that perhaps I should aim not to exceed.

I guess that if messages are not handled as quickly as they are received they are either lost or they backup in the "pipe" until there is no more space and must be thrown away.

**Comment by fundamental** [comment]
I don't have a figure here, but I will say that the zyn-fusion GUI explicitly has a "we didn't get a response, resend the request" feature in it to handle cases where many parameters are requested at once and a message or two gets dropped.

**Comment by zynmuse** [comment]
It looks like I start to get problems at about 10000 messages sent per second.
This will provoke responses from zynaddsubfx to both the gui and my program.

Typically now I'm running with below 1000 mps and that covers quite a complex piece of music with a lot of automation.
That's OK for me with my current PC. 

The most obvious indication of the problem is the obvious missing sounds - stuck notes etc...

It also causes high CPU usage - cores hitting the 100% mark.
