### ISSUE TITLE
Zynaddsubfx crash when switching filter type

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#324]
Following crash in zynaddsubfx (latest Master) when switching adsynth global fitter filter type  to moog (I think). 

zynaddsubfx: /JohnsMounts/PDevelopmentB/ZynAddSubFx_SourceCode/master/src/zynaddsubfx/src/DSP/AnalogFilter.cpp:260: static zyn::AnalogFilter::Coeff zyn::AnalogFilter::computeCoeff(int, float, float, int, float, float, int&): Assertion `false && "wrong type for a filter"' failed.

**Comment by fundamental** [comment]
I cannot replicate this issue, so steps to trigger the bug are required.

**Comment by zynmuse** [comment]
I have repeated this. 
Using current master cloned yesterday.
In addsynth
select global and filter,
select analog (filter class)
click GENERAL to see the filter graph,
select (filter type) notch,
use cutoff to move the notch left and right.
select moog ( filter class)
Zynaddsubfx has now crashed.

**Comment by fundamental** [comment]
This issue should be resolved via https://github.com/zynaddsubfx/zynaddsubfx/commit/05fb681ca20f9489e2ec5c8a59222773fd7265d3
