### ISSUE TITLE
Zest crash at mruby-zest-build/mruby/src/class.c:1737

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#326]
I found zest had crashed while playing a few long notes and using a longish freeform amplitude envelope  in pulse modulation screen.
I had just been adjusting the sequence I was sending when I found zest had frozen at:
mruby-zest-build/mruby/src/class.c:1737

This still has the old debugging in place.

[zestCrash%211122.txt](https://github.com/zynaddsubfx/zyn-fusion-issues/files/7583833/zestCrash.211122.txt)

**Comment by fundamental** [comment]
I'm not sure what would have caused a crash at the linked line. It's essentially walking through a class hierarchy in the MRuby VM, which isn't code that I've altered. It seems like there's likely memory corruption, though there isn't a hint of the source in the debug output. From what I see it's the sort of thing where valgrind/address sanitizer needs to point to an issue, but unfortunately I haven't had any luck replicating the issues.

**Comment by zynmuse** [comment]
Thanks for looking into this.
Unfortunately I haven't seen this since. If I come across a similar crash and am able to reproduce it then I will run valgrind.
The system is now far more stable since the previous bugfix!

**Comment by pgervais** [comment]
Given the time since the last activity on this ticket, I think it's safe to close it.
