### ISSUE TITLE
Disabling a part in the mixer causes individual part audio output to loop over the last audio buffer generated

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#327]
I haven't noticed this when running ZynAddSubFX on my laptop, where I feed the combined stereo output to the sound card. However, on the Zynthian, the individual part outputs are used, and if a part is muted in the mixer screen while it is still playing audio, it seems that the last audio buffer generated is looped until the part is re-enabled. This happens sometimes in Zynthian supposedly when it mutes a part during reconfiguration, but is easily reproduceable in that environment by connecting a remote Zest using OSC, and muting a part in the mixer screen while audio is being generated for that part.

**Comment by polluxsynth** [comment]
Sorry, did I post this issue in the wrong repository initially?

A thing I don't yet understand is why on my laptop ZynAddSubFX only exports two ports (at least according to the Connect window in Qjackctl), while on the Zynthian box it has not only two master ports but also two per part. Perhaps its a jack1 vs. jack2 thing? I have a sound card with 18 inputs (-> read ports) and Qjackctl correctly finds all of them.

EDIT: Realized it was because Zynthian starts zynaddsubfx with **-O jack-multi** which causes it two create one pair of ports for each part in addition to the master outputs. Using this option I can reproduce the problem on my PC.

**Comment by fundamental** [comment]
Reopening as if you can replicate the issue it's an active bug.

**Comment by polluxsynth** [comment]
Sorry, didn't mean to close it. Must have clicked 'Close with comment' rather than 'Comment'. I've got a patch now, but I'll sleep on it before i submit a PR...it turned out to be slightly more intricate than I initially thought.

**Comment by polluxsynth** [comment]
Fixed in https://github.com/zynaddsubfx/zynaddsubfx/pull/164 .
