### ISSUE TITLE
Can bank and preset root be set from the command line?

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#329]
When starting Zyn it would be practical to be able to specify the preset root on the command line. As it is, it seems to be equal to the current working directory, which is a bit awkard.

**Comment by fundamental** [comment]
There's a few approaches viable, OSC messages can be set to configure global settings, or the global settings can be edited where they exist on disk ~/.zynaddsubfxXML.cfg . No command line arguments are available to adjust either bank or preset root. IMO it doesn't make sense for there to be a command line arg to zyn as the current design would save that information in future zyn executions as both search paths are stored in the global config.

**Comment by polluxsynth** [comment]
Ok, apologies first: first of all I was completely ignorant of the settings file. Secondly, after studying the documentation, it seems that my use of the term 'presets' was wrong. 'presets' in the sense of PRESETROOT, don't seem to refer to presets in the sense of 'synth patches', but rather snippets of patches that can be cut and pasted into patches, according to the documentation (doc/saving.txt). The data saved in instrument files (.xiz) is referred to 'patches' in the documentation, and the root for patch files is the same as for banks, BANKROOT (naturally, since patches are grouped into banks). 

I note that the browser window in the GUI refers to 'patches' as 'presets' which is confusing. (I'm not sure how to actually save 'presets' meaning copied portions of patches.)

Is there any way to save a new patch using the browser window? It's possible to read and (over)write patches in the banks, but I haven't found a way to write new ones that way. Which means that it's necessary to use the FILE menu to write instrument files. Which brings me back to the original issue: the initial directory seems to simply be the current working directory (or, more precisely, after some experimentation, $PWD, which technically should be the same, but of course it's possible to at least temporarily assign $PWD to another value before starting the application), meaning that if one has set up a specific BANKROOT, then when saving a patch, one must first navigate to that directory. (I think this is simply the default behaviour of the underlying fltk toolkit.) As a user knowing exactly where one has put one's local patch banks (and they are likely not far from the root of the user's home directory) it is perhaps just a minor annoyance, but I came across this on the Zynthian platform, where it's not obvious how to navigate from the WD where zyn is started (/zynthian/zynthian-ui) to where the patches are stored (/zynthian/zynthian-my-data/presets/zynaddsubfx).

Perhaps the configuration file could contain a FILEROOT similar to BANKROOT and PRESETROOT, which would be the default directory for the FILE operations? Or perhaps separate FILEROOTs for different file operations (i.e. one for instrument files, one for master files, etc)?

**Comment by fundamental** [comment]
Yeah, the 'preset' term is somewhat overloaded and AFAIK basically no one used it in the old GUI anyhow. So when the fusion rewrite occurred I basically hid at the user level that copy/paste style presets existed at all and let the term fall back to how people would more commonly use it for either full program state or for state of one of the 'instruments'/channels/etc.

> Is there any way to save a new patch using the browser window?

Yes, but I'll admit upfront it's a clunky process that I was never entirely happy with. While the UX of a lot of other workflows were pretty carefully examined the saving to a bank workflow was pretty much an afterthought all things considered. I think it ends up being "put the bank view into write mode and click on an empty slot after selecting the destination bank at which point the name of the instrument will be written to that slot".

> Perhaps the configuration file could contain a FILEROOT similar to BANKROOT and PRESETROOT, which would be the default directory for the FILE operations?

Not a bad idea. Right now I think it should default to $HOME, not $PWD, though it's been a while since I wrote that code. I could see users being very opinionated about where the file dialog starts from, though I'm not sure what's the best fit option for the broad community.

**Comment by polluxsynth** [comment]
> Yeah, the 'preset' term is somewhat overloaded and AFAIK basically no one used it in the old GUI anyhow. So when the fusion rewrite occurred I basically hid at the user level that copy/paste style presets existed at all and let the term fall back to how people would more commonly use it for either full program state or for state of one of the 'instruments'/channels/etc.

Ok. That makes sense. So that means that the saving/loading of "presets" is essentially deprecated - indeed, I can't find a way to access the functionality in Zyn-Fusion, but perhaps there is a way?

I have actually used copy/paste within a patch while editing, to copy filter and envelope settings from, say, the individual voice slots to the global one.

> > Is there any way to save a new patch using the browser window?
> 
> Yes, but I'll admit upfront it's a clunky process that I was never entirely happy with. While the UX of a lot of other workflows were pretty carefully examined the saving to a bank workflow was pretty much an afterthought all things considered. I think it ends up being "put the bank view into write mode and click on an empty slot after selecting the destination bank at which point the name of the instrument will be written to that slot".

I think something is broken here. 

First of all, I don't really understand what 'write mode' does. Whenever I want to replace an existing patch after an edit, I click on 'overwrite' which seems to replace it regardless of 'read mode' or 'write mode'. The only difference between read and write modes I can see is that in read modes, the patches are loaded when clicked on, but in write mode, nothing really happens.

Clicking on an empty patch slot (or any patch slot) in write mode doesn't seem to do anything in itself. If I first click on a slot and then click 'Overwrite', it sometimes overwrites the original .xiz file, and sometimes it creates a new one (called, <patch number>-<name>, e.g. 0001-test patch.xiz). In either case, it doesn't show up in the preset column, but if I click 'Rescan', the preset column is filled with entries named 'EMPTY PRESET', and in the case of a new .xiz file actually being written, the new patch file will be listed at the top. I can't really see any consistency as to under which conditions the patch file actually does get written, it seems to be arbitrary. In any case, when it does create a new .xiz file, it also seems to overwrite the one from which the patch originated.

Restarting zest brings back normality, and I then get the list of patches I have in the bank directory when I select the bank in question. Patches with a number (i.e. prefixed by 0001 etc) are shown without the patch number.

Then again, I realize now that the patch bank I'm working with doesn't have patch numbers in the file names, as I've saved them one by one from the file menu. Perhaps that confuses the UI code.

Hm, I also realized that when I do get zest into the mode where it shows EMPTY PRESET, it seems to assume there are 128 (?) slots, and shows the existing patch files in their appropriate position in the list, see for instance the factory Guitar bank where the files are not numbered contiguously.

Is write mode perhaps supposed to list the presets that have been written with number prefixes, with unused preset numbers (no .xiz file prefixed with that nunber) displayed as EMPTY PRESET? This doesn't seem to happen, even in banks which have only numerically prefixed .xiz files, such as the factory banks.

> > Perhaps the configuration file could contain a FILEROOT similar to BANKROOT and PRESETROOT, which would be the default directory for the FILE operations?
> 
> Not a bad idea. Right now I think it should default to $HOME, not $PWD, though it's been a while since I wrote that code. I could see users being very opinionated about where the file dialog starts from, though I'm not sure what's the best fit option for the broad community.

After a bit of experimentation, It definitely seems to be $PWD now anyway. As it stands, it's actually not a bad thing, because then it's possible to have some sort of control of where the default file directory is...

**Comment by fundamental** [comment]
> Ok. That makes sense. So that means that the saving/loading of "presets" is essentially deprecated - indeed, I can't find a way to access the functionality in Zyn-Fusion, but perhaps there is a way?

Correct, the functionality isn't in the new GUI.

> I have actually used copy/paste within a patch while editing, to copy filter and envelope settings from, say, the individual voice slots to the global one.

Yep. The traditional copy/paste is supported, but the new UX is to treat copy/paste buffers as transient instead of a serializable/persistent structure. The old workflow involved users having a favorite envelope or favorite oscillator config and saving that specific copy/paste buffer for future reference.

> I think something is broken here.

Unfortunately I wouldn't be surprised at all if something is broken in bank saving. Comparatively few issues have been raised about the functionality which tends to mean that it's seldomly used. That's not to say it's unimportant, just less likely that users spot and report bugs with it.

> Clicking on an empty patch slot (or any patch slot) in write mode doesn't seem to do anything in itself.

Odd, that's the workflow I remember setting up ages ago, though perhaps it was subsequently changed.

>  if I click 'Rescan', the preset column is filled with entries named 'EMPTY PRESET'

Sounds like a second bug if only EMPTY PRESET is being shown.

> it seems to assume there are 128 (?) slots

Almost exactly correct. The old UI did a better job at presenting this part of the model, though the old UI was significantly worse for searchability. Each bank was designed to have a fixed number of entries which were displayed in a grid. I think I recall the number being a bit over 128 because when bank select and program select midi messages were integrated there were a few initially unreachable instruments using the 7-bit MIDI representation. At various points I think I tried to shift it to a more fixed 128 representation to avoid exposing that quirkyness to end users.

> Perhaps that confuses the UI code.

I don't recall the GUI parsing the file names, I think that the backend returns (slot ID, name) pairs. The backend does parse the file names though (I think in Bank.cpp or BankDb.cpp), so it could be confused at that level. I think the fallback is all files are listed in sorting order and put into those slots?

> Is write mode perhaps supposed to list the presets that have been written with number prefixes, with unused preset numbers (no .xiz file prefixed with that nunber) displayed as EMPTY PRESET? 

That sounds likely and modifies the bug to not showing non-empty presets correctly. Either way, I'd expect EMPTY PRESET should have some indicator for what slot it's referring to. I'm not sure if that information is in a tooltip though.


> After a bit of experimentation, It definitely seems to be $PWD now anyway. 

I looked up the code out of curiosity:
```
      {"file_home_dir:", 0, 0,
          rBegin;
          const char *home = getenv("PWD");
          if(!home)
              home = getenv("HOME");
          if(!home)
              home = getenv("USERPROFILE");
          if(!home)
              home = getenv("HOMEPATH");
          if(!home)
              home = "/";
  
          string home_ = home;
  #ifndef WIN32
          if(home_[home_.length()-1] != '/')
              home_ += '/';
  #endif
          d.reply(d.loc, "s", home_.c_str());
          rEnd},

```

**Comment by polluxsynth** [comment]
> > if I click 'Rescan', the preset column is filled with entries named 'EMPTY PRESET'
> 
> Sounds like a second bug if only EMPTY PRESET is being shown.

Sometimes it actually saves something, and that patch then turns up at the top of the list; upon examining the bank directory, it has been saved with a numerical prefix. Sometimes, I would say more often than not, it doesn't save anything at all, or possibly overwrites the original patch, I haven't checked extensively, but I have noticed that it has happened at least a couple of times even though that patch wasn't selected when I was in write mode. In any case, when it doesn't write a new file, the whole bank is filled with EMPTY PRESET.

When glancing through the code I've noticed references to some form of cache. If so, my instinctive reaction would be that something is amiss in terms of which slot in the cache is actually updated and how the cache is flushed.

> > Perhaps that confuses the UI code.
> 
> I don't recall the GUI parsing the file names, I think that the backend returns (slot ID, name) pairs. The backend does parse the file names though (I think in Bank.cpp or BankDb.cpp), so it could be confused at that level. I think the fallback is all files are listed in sorting order and put into those slots?

Yes, sorry, I think I meant 'something in the road from file name to UI' rather than specifically the UI code.

> > Is write mode perhaps supposed to list the presets that have been written with number prefixes, with unused preset numbers (no .xiz file prefixed with that nunber) displayed as EMPTY PRESET?
> 
> That sounds likely and modifies the bug to not showing non-empty presets correctly. Either way, I'd expect EMPTY PRESET should have some indicator for what slot it's referring to. I'm not sure if that information is in a tooltip though.

Mousing over a patch name in both read and write modes shows the complete file name and search path in the upper of the two status printout lines in the UI (I guess this is what you mean by tooltip, I think of tooltips as small popups which occur when hovering over an item with the mouse). It doesn't show any slot numbers that I can see though.

So if I understand it, the correct behavior should be something like this:

- In READ mode, valid patches are listed, with no EMPTY PRESETs.
- In WRITE mode, unused slots are filled with EMPTY PRESET. By default, the backend fills in the slots from 0 and upwards if there are no numerical slot prefixes in the filenames.
- In order to actually write a patch, one clicks OVERWRITE, which either overwrites the selected patch file, or creates a new one if the slot is marked EMPTY PRESET.

You're probably right that few people use this feature, I think a lot of the time people view ZynAddSubFX as a preset instrument and just select from the presets. But that could also be related to the fact that it doesn't seem to work properly ...

> > After a bit of experimentation, It definitely seems to be $PWD now anyway.
> 
> I looked up the code out of curiosity:
> 
> ```
>       {"file_home_dir:", 0, 0,
>           rBegin;
>           const char *home = getenv("PWD");
>           if(!home)
>               home = getenv("HOME");
>           if(!home)
>               home = getenv("USERPROFILE");
>           if(!home)
>               home = getenv("HOMEPATH");
>           if(!home)
>               home = "/";

Isn't the priority wrong here? $PWD is normally set to the current working directory by the shell, so none of the other fallbacks would ever trigger unless the user specifically unsets $PWD? I don't know if this is true in a Windows environment though.

I would expect something specific like $USERPROFILE (or even $ZYNBANKS or something similar) to be the first priority, and then $HOMEPATH, $HOME, $PWD and / in that order.

**Comment by fundamental** [comment]
> Isn't the priority wrong here? 

You'd think, but between Linux, Linux window managers, MacOS, embedded pi setups, Windows, BSD, etc you get weird environmental variable combinations. IIRC the PWD may have been put in place for use with zynthian, though I could be mistaken.

> I guess this is what you mean by tooltip, I think of tooltips as small popups which occur when hovering over an item with the mouse

Yep. Early on in development they were designed to appear like traditional tooltips, but I liked the lower clutter version. Invalid nomenclature on my part, though I don't quite know what else to call them.

> Yes, sorry, I think I meant 'something in the road from file name to UI' rather than specifically the UI code.

No problem. I'm likely just being a bit pedantic thinking about where various issues exist in the underlying codebase.

> When glancing through the code I've noticed references to some form of cache. If so, my instinctive reaction would be that something is amiss in terms of which slot in the cache is actually updated and how the cache is flushed.

While I'm not going to say it's impossible, the cache should be utilized in terms of repeated searching. Any writes should be instantaneous. There is the possibility that there isn't a cache invalidation upon a write (not in the test suite), but symptoms of that would include not seeing a patch in the GUI while seeing it appear on disk as soon as a save action is performed.

> You're probably right that few people use this feature, I think a lot of the time people view ZynAddSubFX as a preset instrument and just select from the presets. But that could also be related to the fact that it doesn't seem to work properly ...

Which is a giant shame. If you just want note in sample out behavior, get a sampler IMO. The fun bits of zyn is the giant pile of configurable knobs that makes up the beast.


Now to run some tests to see if I'm observing anything different to the rest of the post.

**Comment by fundamental** [comment]
- Bank.cpp blist is what produces 'empty preset' and it does indeed walk through 128 elements. It loads the bank right before listing the elements, so the cache is bypassed.
- Clicking on an empty slot will intend to fill it. It does so using the slot id which is stored as the index in the list of 128 elements. (via /bank/save_to_slot) 
- Overwrite will attempt to overwrite the current instrument regardless of any additional selection (i.e. the last loaded instrument).
- An alert on a failed save is sent back to the GUI. I know the fltk GUI responds to /alert messages, though I don't recall if the zest GUI responds to /alert messages. A common failure mode is saving to a bank which the user doesn't have permissions to write to.
- No indication of success is available.


> So if I understand it, the correct behavior should be something like this:
>    In READ mode, valid patches are listed, with no EMPTY PRESETs.
>    In WRITE mode, unused slots are filled with EMPTY PRESET. By default, the backend fills in the slots from 0 and upwards if there are no numerical slot prefixes in the filenames.
>    In order to actually write a patch, one clicks OVERWRITE, which either overwrites the selected patch file, or creates a new one if the slot is marked EMPTY PRESET.

Close, but the actual case is:

- Read mode presents the results of a search/filtering operation. As such blank bank elements are never returned. The closest you get to a bank in isolation is to have other parts of the search query empty, just "only give elements in bank X" which empty slots don't contribute towards (currently).
- Write mode doesn't use columns other than the bank to perform the search, but other columns configure information about the tagging of the patch to be written. As such each bank is presented as something containing a fixed number of elements where the user can write into a bank at any location of their choosing (assuming they have write permissions). Write permissions are not checked until the file is written (or the write fails). Clicking will immediately send a message to try to write the active instrument to the desired bank at the desired bank slot.
- Overwrite uses whatever patch the user is currently working on and overwrites it with the current state. The system assumes the most recently loaded patch (to that part?) is the active patch.

**Comment by polluxsynth** [comment]
> > Isn't the priority wrong here?
> 
> You'd think, but between Linux, Linux window managers, MacOS, embedded pi setups, Windows, BSD, etc you get weird environmental variable combinations. IIRC the PWD may have been put in place for use with zynthian, though I could be mistaken.

It doesn't seem that Zynthian took advantage of this, although I recently made a patch for Zynthian which uses the current behavior, and changes the current working directory and sets PWD to the appropriate user bank directory before starting zynaddsubfx.

> > I guess this is what you mean by tooltip, I think of tooltips as small popups which occur when hovering over an item with the mouse
> 
> Yep. Early on in development they were designed to appear like traditional tooltips, but I liked the lower clutter version. Invalid nomenclature on my part, though I don't quite know what else to call them.

I'd stick with 'tooltip, Zyn style' ! :-) It really is a tooltip, even if its behavior is slightly unconventional. It suits the Zyn UI I think.

> > Yes, sorry, I think I meant 'something in the road from file name to UI' rather than specifically the UI code.
> 
> No problem. I'm likely just being a bit pedantic thinking about where various issues exist in the underlying codebase.

As well you should, it helps understanding of where things actually happen.

> > You're probably right that few people use this feature, I think a lot of the time people view ZynAddSubFX as a preset instrument and just select from the presets. But that could also be related to the fact that it doesn't seem to work properly ...
> 
> Which is a giant shame. If you just want note in sample out behavior, get a sampler IMO. The fun bits of zyn is the giant pile of configurable knobs that makes up the beast.

Agreed. The oscillator parameters in particular are a great unknown to explore.

But If I may say so, I think the current behavior of the GUI enforces it. I know it did for me, it didn't seem intuitive, and still doesn't, and I couldn't get write mode to do anything useful, nor what is it clear how to set up my own banks. I started using the File menu to save and load patches, and the Browser pane seemed to be for presets only in practice.

> Now to run some tests to see if I'm observing anything different to the rest of the post.
> 
> * Bank.cpp blist is what produces 'empty preset' and it does indeed walk through 128 elements. It loads the bank right before listing the elements, so the cache is bypassed.
> 
>     * Clicking on an empty slot will intend to fill it. It does so using the slot id which is stored as the index in the list of 128 elements. (via /bank/save_to_slot)
> 
>     * Overwrite will attempt to overwrite the current instrument regardless of any additional selection (i.e. the last loaded instrument).
> 
>     * An alert on a failed save is sent back to the GUI. I know the fltk GUI responds to /alert messages, though I don't recall if the zest GUI responds to /alert messages. A common failure mode is saving to a bank which the user doesn't have permissions to write to.
> 
>     * No indication of success is available.
> 
> 
> > So if I understand it, the correct behavior should be something like this:
> > In READ mode, valid patches are listed, with no EMPTY PRESETs.
> > In WRITE mode, unused slots are filled with EMPTY PRESET. By default, the backend fills in the slots from 0 and upwards if there are no numerical slot prefixes in the filenames.
> > In order to actually write a patch, one clicks OVERWRITE, which either overwrites the selected patch file, or creates a new one if the slot is marked EMPTY PRESET.
> 
> Close, but the actual case is:
> 
> Read mode presents the results of a search/filtering operation. As such blank bank elements are never returned. The 
> closest you get to a bank in isolation is to have other parts of the search query empty, just "only give elements in bank X" 
> which empty slots don't contribute towards (currently).

Yes, this part seems to work and is fairly intuitive.

> Write mode doesn't use columns other than the bank to perform the search, but other columns configure information 
> about the tagging of the patch to be written. As such each bank is presented as something containing a fixed number of 
> elements where the user can write into a bank at any location of their choosing (assuming they have write permissions). 
> Write permissions are not checked until the file is written (or the write fails). Clicking will immediately send a message to try 
> to write the active instrument to the desired bank at the desired bank slot.

So clicking on a slot in write mode should immediately write the currently loaded patch for the part to that slot?

This seems to be where there are the most problems: 

- Unused slots are not listed as EMPTY PRESET when clicking on Write, so if the write column is full, there are no free slots to which to write. At least this is not the case for my user bank, which doesn't have slot numbers in the patch names, but it seems to be the case for the factory preset banks as well.
- It doesn't seem like anything is written when clicking on a slot.
- There is no write confirmation (as you said)

However, IMHO, writing a patch just on the basis of clicking on the relevant slot seems rather dangerous in terms of unintended overwrites to me. I would much rather have clicking around in the preset column just select the patch for writing, and then click on a well-defined and separate Write button to actually accomplish this fact, with success or failure showing up as a tooltip.

This would seem to mimic the behavior of writing patches in hardware synths, where one purposely has to enter a special meny, or hold a WRITE button down while pressing patch selector button, etc.

> Overwrite uses whatever patch the user is currently working on and overwrites it with the current state. The system 
> assumes the most recently loaded patch (to that part?) is the active patch.

This also seems unintuitive to me, although perhaps less so if clicking in the patch column in Write mode would perform a write. IMHO, there should be a single Write button which does the write based on an earlier selection.

In my case I use a touch screen for Zest, which works admirably 99% of the time, but it is easy to mis-click. Granted, I'm very likely in the minority, but even so, I think that just clicking on a patch seems to dangerous a way to overwrite it, especially without an 'Are you sure?' type of mechanism. 

I'm no UX expert by any means though, but I honestly think the current behavior is unintuitive both in terms of how it is intended to work, if I understand your description correctly, and the way it actual does work (which of course is more of a bug than intended behavior). Would it be ok if it were changed (of course only after reaching a consensus on how it should work)?

**Comment by fundamental** [comment]
> So clicking on a slot in write mode should immediately write the currently loaded patch for the part to that slot?

I think so?

> Unused slots are not listed as EMPTY PRESET when clicking on Write, so if the write column is full, there are no free slots to which to write. At least this is not the case for my user bank, which doesn't have slot numbers in the patch names, but it seems to be the case for the factory preset banks as well.

Hm. I might be misparsing 'when clicking on Write' 'is full' 'no slots' as this doesn't seem to match what I've seen the code should be doing, but none the less I agree there's non-intuitive behavior abound.

> This also seems unintuitive to me, although perhaps less so if clicking in the patch column in Write mode would perform a write. IMHO, there should be a single Write button which does the write based on an earlier selection.

Perhaps, though if such a button exists, there still has to be some way to encode in the tags and destination bank. Right now that's accomplished through the different modes.

> In my case I use a touch screen for Zest, which works admirably 99% of the time, but it is easy to mis-click. 

I'm thrilled to hear. The original development sprint was done using a touch screen for testing. That guided the implementation of knobs/buttons/hit boxes/etc. Certainly not perfect, but good to know I'm not the only person to utilize a touch screen here.

> I'm no UX expert by any means though, but I honestly think the current behavior is unintuitive both in terms of how it is intended to work

Nor am I. I try to learn from existing hardware, software, ux choices elsewhere, but egads are synths weird. They're bespoke software designed to let a largely non-technical audience control a whole lot of really complicated and fiddly math. Representations and idioms are constantly distorting reality, managing information overload, making homages to other tools that have been built up, and there's a lot of custom code to generate different modes of interaction which you'll see once and then never again.

> Would it be ok if it were changed (of course only after reaching a consensus on how it should work)?

I'm 100% good with changing the workflow I was never happy with the workarounds I wrote for this section.

**Comment by polluxsynth** [comment]
> > So clicking on a slot in write mode should immediately write the currently loaded patch for the part to that slot?
> 
> I think so?

It doesn't seem to do that at all, at least not all of the time.


> > Unused slots are not listed as EMPTY PRESET when clicking on Write, so if the write column is full, there are no free slots to which to write. At least this is not the case for my user bank, which doesn't have slot numbers in the patch names, but it seems to be the case for the factory preset banks as well.
> 
> Hm. I might be misparsing 'when clicking on Write' 'is full' 'no slots' as this doesn't seem to match what I've seen the code should be doing, but none the less I agree there's non-intuitive behavior abound.

Clicking Overwrite, and then Rescan does actually cause the write column to fill up with EMPTY PRESET, though at the same time the existing patches are not to be seen (although occasionally it arbitrarily seems to write to a new preset (I have yet to figure out the condition under which this happens), which is given a numeric prefix of 000, at least in my user bank where the preset files were written from the file menu and have no numbers).

> > This also seems unintuitive to me, although perhaps less so if clicking in the patch column in Write mode would perform a write. IMHO, there should be a single Write button which does the write based on an earlier selection.
> 
> Perhaps, though if such a button exists, there still has to be some way to encode in the tags and destination bank. Right now that's accomplished through the different modes.

What I meant was to retain the current Read and Write modes, but the Overwrite button would be labelled Execute Write, or something to that effect. Clicking on a slot in Write mode only selects that slot for potential writing, which occurs when Execute Write is clicked (and the button should be greyed out or in Zyn terms have a diagonal strike in Read mode to clearly show that it does not work in that mode).

Read mode would function like it seems to do today, listing the available presets, with the list of presets compressed into a contiguous list. Going into write mode, by clicking on Write, should immediately additionally display all preset slots which are empty, filled with EMPTY PRESET, without regards to two search column tags. E.,g. in a trivial case, if there are two preset files labelled 000-something.xiz, 001-something-else.xiz, these will be listed at the top, followed by 126 EMPTY PRESETs. The Execute Write should by ungreyed, and clicking on it (and only by clicking on it) will overwrite the slot currently selected in the preset column, with the tags set appropriately.

> > In my case I use a touch screen for Zest, which works admirably 99% of the time, but it is easy to mis-click.
> 
> I'm thrilled to hear. The original development sprint was done using a touch screen for testing. That guided the implementation of knobs/buttons/hit boxes/etc. Certainly not perfect, but good to know I'm not the only person to utilize a touch screen here.

That's interesting. Given how well it works it stands to reason it has actually been designed that way. I'm especially pleasently surprised at how well moving the envelope points works in touch mode.

The whole reason for getting a touch screen laptop was to see how more more physical a synth UI would seem, compared to using a trackpad or mouse, even though there are actually no physical buttons.

I think the only thing I've found which doesn't work well in touch mode is the four sector apply control which comes up when clicking Apply in some engines (the one where it's possible to select timed auto apply), because it requires a right click or something.

To compare, for instance, on my machine, QJackCtl has the strange behavior that clicking with a finger on any button changes focus, but does not actually execute the click. I have to use the Wacom stylus supplied with the computer, or mouse, to do that. I'm guessing that there are several types of clicks, and QJackCtl (or the underlying framework) for some reason has missed one them.

Anyway, I might have a go at presenting a bugfix/suggestion, although there are a couple of things like finalizing the portamento Auto mode which I want to complete before jumping into something new. And I recently got my Zynthian box running, which has also provided opportunity for a lot of coding... all I really wanted to do was explore some Linux softsynths, but it's too fun to actually do some coding to get any music done... :-)

**Comment by fundamental** [comment]
> I think the only thing I've found which doesn't work well in touch mode ... clicking Apply

I was going to implement this prior to the recent release, but it seems there's never enough time in the day. The apply button is a solid candidate for "click and hold is equivalent to right click" behavior. I think that would involve capturing on click time in the mouse handler, and then if nothing stops the click checking if enough time has elapsed in the animate() handler.

> all I really wanted to do was explore some Linux softsynths, but it's too fun to actually do some coding to get any music done... :-)

And so the cycle of linux-audio development continues.

**Comment by polluxsynth** [comment]
I've been fiddling about a bit, trying to figure out what works and what doesn't and what messages are actually sent etc.

One thing I've discovered is that write mode actually does work to some degree, i.e. clicking on a slot in write mode causes that slot to be overwritten ... well, not exactly, for some reason it's always the first slot in the selected bank that is overwritten. The fault is in the UI, as the /bank/save_to_slot <part> <slot> overwrites the correct slot when initiated from oscprompt.

The UI is however very reluctant to update anything, which is why I initially thought nothing was being written. For instance, if overwriting the first slot with a different patch name, the new name is not shown until another bank has been selected, and then the original bank selected again. (Incidentally, this results in an error if trying to immediately load the saved slot, if the file name has changed, as it tries to load the original file name, not the overwritten one).

Similarly, in write mode, the unused slots are not shown as EMPTY PRESET until another bank has been selected and
then the original selected again. Same thing with Rescan, which again doesn't seem to do anything, but changing to
another bank causes the rescanned slots to be shown.

So, so far, the two underlying issues seem to be in the UI: Slot 0 is always selected for write, and it's reluctant to update
the preset list when things change. 

Other issues are consequences of this. One interesting one is that when no bank is selected, selecting a slot in write mode attempts to write to //0001-patch-name.xiz, which is (normally) unwritable. In practice, this sortof makes sense as you can't obviously write to a non-bank.

Another oddity is that the /bank/save_to_slot OSC message is not shown when typing /bank in oscprompt. I'm assuming there's something missing in the OSC code somewhere in the engine, but I haven't understood enough about how this works to see what is missing.

**Comment by polluxsynth** [comment]
Although there are some interesting suggestions in this issue, the original question was answered, and the preset management cleared up in a related issue noted above, so closing this one.
