### ISSUE TITLE
[NSM] zyn-fusion doesn't sent 'dirty' state

### ISSUE THREAD

**Issue by grammoboy2** [zynaddsubfx/zyn-fusion-issues#332]
It looks like zyn-fusion doesn't sent is_dirty or is_clean. It's handy to know when a client needs to be saved.

http://non.tuxfamily.org/nsm/API.html#n:1.2.4.3.

**Comment by fundamental** [comment]
Thanks for the feature request. As the dirty flag is optional per the NSM spec and it is very non-trivial to implement given zyn's internal architecture we are electing not to implement this specific feature.
