### ISSUE TITLE
Segmentation fault when trying to automate amplitude envelope parameters with pad synth

### ISSUE THREAD

**Issue by ChromaCat248** [zynaddsubfx/zyn-fusion-issues#338]
How to recreate:
1. Create a pad synth patch
2. Click on "Learn" in the top bar and click on any of the dials in the box my mouse is hovering over in this image
![zynaddsubfx](https://user-images.githubusercontent.com/50424765/153517767-a4bbb811-49cd-44d1-add2-1ba493dad41e.png)
3. Go to the macro learn screen and try to automate it, it shouldn't work
4. Go back to the screen with the parameter that was just learned, the entire DAW should crash

My software:
- Arch Linux with linux-zen 5.16.8 from the Arch standard repos
- zynaddsubfx 3.0.6-2 from the Arch standard repos
- reaper-bin 6.46-1 from the AUR
- pipewire / pipewire-jack 1:0.3.45-1 from the Arch standard repos

**Comment by ChromaCat248** [comment]
> Can you replicate this with the standalone? Right now I can see some warnings, but no crashes using the included steps.

https://user-images.githubusercontent.com/50424765/153690309-724c9b54-d6e9-4c04-8f0b-97f5af78e0fc.mp4

It still crashes, for some reason it doesn't segfault. It might've been Reaper that was segfaulting.

**Comment by fundamental** [comment]
Excellent. I can replicate the issue. Now to track down the origin of the NaN now that I know it's appearing in the envelope rendering.

**Comment by fundamental** [comment]
Current diff which resolves the issue. I might tweak the lower bound of the range before committing.

```diff --git a/src/Params/EnvelopeParams.cpp b/src/Params/EnvelopeParams.cpp
index 0dd9f3db..999edb0b 100644
--- a/src/Params/EnvelopeParams.cpp
+++ b/src/Params/EnvelopeParams.cpp
@@ -117,7 +117,7 @@ static const rtosc::Ports localPorts = {
     rToggle(Prepeating, rShort("repeat"), rDefault(false),
             "Repeat the Envelope"),
     rParamDT(A_dt ,  rShort("a.dt"), rLinear(0,127), "Attack Time"),
-    rParamF(A_dt,  rShort("a.dt"), rLog(0.0f,41.0f), rDefaultDepends(loc),
+    rParamF(A_dt,  rShort("a.dt"), rLog(0.0001f,41.0f), rDefaultDepends(loc),
               rPreset(ad_global_freq, 0.254f),   rPreset(ad_global_filter, 0.127f),
               rPreset(ad_voice_freq, 0.127f),    rPreset(ad_voice_filter, 0.970f),
               rPreset(ad_voice_fm_freq, 3.620f), rPreset(ad_voice_fm_amp, 1.876f),
@@ -132,7 +132,7 @@ static const rtosc::Ports localPorts = {
               rDefault(64),
               "Attack Value"),
     rParamDT(D_dt, rShort("d.dt"), rLinear(0,127), "Decay Time"),
-    rParamF(D_dt,  rShort("d.dt"), rLog(0.0f,41.0f),  rDefaultDepends(loc),
+    rParamF(D_dt,  rShort("d.dt"), rLog(0.0001f,41.0f),  rDefaultDepends(loc),
               rPreset(ad_global_amp, 0.127f),    rPreset(ad_global_filter, 0.970f),
               rPreset(ad_voice_amp, 6.978f),    rPreset(ad_voice_filter, 0.970f),
               rPreset(ad_voice_fm_amp, 3.620f),
```

**Comment by fundamental** [comment]
Thanks for @friedolino78 for doing some code review. I've committed the changes and those two controls should no longer be capable of generating NaN values on the realtime side of things which was the root cause of the issue.
