### ISSUE TITLE
Saving audio to a file

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#342]
I use Zynaddsubfx as a stand alone process ( ie. not as a plugin).

The old (FLTK) interface has a set of options:
 Record -> Choose wav file
 Rec., Pause, Stop buttons 

 This works and saves stereo to a wav file. However the file format is not generally acceptable to music players - which is a pity.
 
 I found that it could only be loaded in to audacity using options:
 File ->Import-> Raw Data

Similar record buttons exist on zynFusion, but its less obvious how they work;
 - you can select a file via File-> Setup Record
  - No indication that "record file" is set up, or that the file name has been registered.
  - The buttons are not animated. So can't tell whether a file is being saved or paused or ready to record. 
    I had to check if the file was still growing in size to know if it was still recording.
  - I saved some stereo but one of the stereo tracks recorded OK, 
    while other track was full of saturated sound in time with the sound  on the good channel.
    This is different to what happened using the fltk interface where both tracks were OK.
    

 I cant find any way to save all 16 (stereo) tracks although jack can see them if you use multi-jack
 when you start zynaddsubfx.
  (When starting zynaddsubfx use 	-O jack-multi)

  LMMS (for example) has an option to export all tracks - it makes each track into a separate stereo wav file.
  Audacity can read all these tracks in in one operation for further mixing/editing.
  ZynFusion ought to work in the same way.

**Comment by fundamental** [comment]
> This works and saves stereo to a wav file. However the file format is not generally acceptable to music players - which is a pity.

The output of that level should still work fine, though due to the design of the wave file format you can't finish writing the header until you complete a recording. I'm guessing that the zyn backend isn't being told to finalize the recording and thus you don't have the wave header.

**Comment by zynmuse** [comment]
OK. Thanks.
I'm trying to understand the osc interface.
I can find references to ports
/HDDRecorder/start
/HDDRecorder/stop
/HDDRecorder/pause
/HDDRecorder/preparefile

That suggests these operations are available via OSC interface. I don't see them in the test.json.
Maybe I'm a bit confused how this works!
Can you give me any pointers?

**Comment by zynmuse** [comment]
I've actually played a bit more using oscprompt.
I have used the 
/HDDRecorder/start
/HDDRecorder/stop
/HDDRecorder/pause
/HDDRecorder/preparefile

The ports do work although they do't appear in json file. I assume they are generated when the interface is run?

**Comment by fundamental** [comment]
The original design of the json file included information about actions as well as parameters, but the actions never ended up getting dumped. I forget if it's because they weren't needed for the programatic parsing of the OSC data or if the oscdoc tooling just didn't support them. Either way it looks like you've found the relevant ports. preparefile seems to set the filename and stop should finalize the file.

**Comment by zynmuse** [comment]
Thanks. I'm figuring that out and about to add a remote record to my project which should be straight forward.

I believe there is still a requirement in Zest interface to give user some feedback when start, stop and pause buttons are activated similar to what happens in the old fltk interface. 
Also the missing missing cursor when trying to enter a file name ( on linux version at least). I have seen mentioned elsewhere and is the same at other places where text has to be entered.

The ability to dump individual channels to audio files is desirable, but would  be a new feature rather than a bug fix, so I guess I'm hoping someone may be able to add this in future!

**Comment by fundamental** [comment]
> I believe there is still a requirement in Zest interface to give user some feedback when start, stop and pause buttons are activated similar to what happens in the old fltk interface.

That would make for a good enhancement.

> Also the missing missing cursor when trying to enter a file name ( on linux version at least).

IIRC the basic text entry forces the cursor to the end, but the multi-line edit tracks cursor state.

**Comment by zynmuse** [comment]
Selection from the folder and file list is OK. No files or folder are highlighted but It is natural to use the mouse.
Editing the text in the file entry box is poor.
There is no visible cursor, and it is not possible to edit your entry only add characters on the end and use back arrow to remove characters from the end. It isn't obvious that a file name can be entered there. I feel this could be much user friendly.

**Comment by zynmuse** [comment]
Potential bug within record audio functionality within zynaddsubfx.

1. When I stop recording using /HDDRecorder/stop  it carries on recording.

`src/misc/recorder.cpp line 81 Nio::waveStart();`  doesn't look right. I commented out that line and now the audio does stop recording.

```
void Recorder::stop()
{
    Nio::waveStop();
    Nio::waveStart();
    status = 0;
}
```

2. The file that is written is not recognised by any audio software I have. It can be imported to audacity but only by using import raw data option which determines it to be 
- signed 16 bit PCM, little_endian, 2 channel stereo, 44100Hz
I can then play the file in audacity. 

Since I don't have much idea  how any of  the zynaddsubfx recorder code works, I'm hoping somebody can come up with some ideas.

**Comment by zynmuse** [comment]
In addition I have to manually set the file parameters when importing into audacity to 48000HZ. It is clear that the wav file is missing some data!

**Comment by fundamental** [comment]
Possible untested patch to resolve the issue:

```diff
diff --git a/src/Nio/WavEngine.cpp b/src/Nio/WavEngine.cpp
index 1410a756..316b695f 100644
--- a/src/Nio/WavEngine.cpp
+++ b/src/Nio/WavEngine.cpp
@@ -63,6 +63,7 @@ void WavEngine::Stop()
     work.post();
     pthread_join(*tmp, NULL);
     delete pThread;
+    destroyFile();
 }
 
 void WavEngine::push(Stereo<float *> smps, size_t len)```

**Comment by zynmuse** [comment]
Thanks!
I'll test this asap and let you know.

**Comment by zynmuse** [comment]
Excellent.
I confirm that with the above fix the recording  is now working correctly. The file can now load into audacity and vlc and plays back correctly.
Thanks!

**Comment by fundamental** [comment]
Merged
