### ISSUE TITLE
Bank searches with empty search results no longer update the presets window

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#343]
In fusion, If a /bank/search call results in a /bank/search_results with an empty list, the presets column is not updated, and thus the search results from the previous search remains.

To reproduce:
1. Start zyn as usual
2. Select the bank ARPEGGIOS
3. All patches in the arppegios bank are shown
4. Select type ORGAN
5. As expected, the single patch with this tag is displayed in the preset column (HYPER ORGAN1)
6. Select type PIANO
7. There are no patches in the arpeggios bank with this tag, so the preset column should be empty, but instead it retains the previous contents.
8. Deselect PIANO. The complete bank is now shown again.
9. Select type PIANO. Again, the preset column should be empty as in 7, but instead retains the previous contents, which this time is the complete bank.

This problem was introduced in commit dd3d45ba333011f2359e86f9a758d9836e53fe5f "osc-bridge: Only treat 2+ arg messages as vectors"; reverting it fixes the problem.

I'm suspecting though that the real fix is more intricate, as there must have been a good reason for that commit in the first place.

**Comment by fundamental** [comment]
That commit was designed to fix a few bugs where a zero arg message was getting received, being turned into a value, handed back to ruby, and then the code was trying to index a non-array value (or an array which was zero length?). IIRC I wasn't able to replicate the issues fully on my end, but recognized that if those types of messages were handled differently it would squash that class of bugs.

**Comment by polluxsynth** [comment]
So essentially, the original bug would cause zest would to crash when Ruby subsequently tried to index into a zero length array? 

I'm thinking of a few solutions here:
1. Revert the commit and try to replicate the issues (any idea which one(s)?) and fix them in another place.
2. When doing a /bank/search, clear the SelColumn so that it's empty to start with, and will then be filled in with the result, if it appears. I though SelColumn.clear would accomplish this, but after trying it (this was my initial attempt at fixing the issue) it appears that's not what it does, or perhaps there's bug in .clear (no damage_self to the SelColumn itself?).
3. When a zero length vector is received, synthetically create a one-length vector with a zero-length string (or perhaps, two-length vector, as the results from a /bank/search come in pairs with the patch name and filename path in each pair).

**Comment by fundamental** [comment]
> Revert the commit and try to replicate the issues (any idea which one(s)?) and fix them in another place.

I don't recall which ones specifically, though I think they should be the ones authored by zynmuse on system crashes.

I'd avoid option 2 as it's going to introduce flicker in the GUI

As per option 3 right now the response argument list is going to be something like one of `,ssssss ,sss ,s ,` OSC does add in `[]` as valid parts of the typestring and rtosc should handle those fine. Perhaps using them to signify "This is a message which is array valued, but explicitly an empty array? There's also N which from the OSC 1.1 spec:

> N Null: (aka  nil,  None,  etc). No  bytes  are  allocated  in the argument data

Option 1 would be the best, but I never had full luck tracking down all of the origins of the bad messages: zynaddsubfx sending the wrong messages, zyn-fusion's osc-bridge getting the wrong data, osc-bridge interpreting the data wrong, something else, etc

**Comment by polluxsynth** [comment]
> I don't recall which ones specifically, though I think they should be the ones authored by zynmuse on system crashes.

I think I found the thread: https://github.com/zynaddsubfx/zyn-fusion-issues/issues/307

> I'd avoid option 2 as it's going to introduce flicker in the GUI

Indeed it does, I tried it out, it doesn't look to nice, although the flicker actually has the slight advantage that it alerts the user to the fact that something has changed. 

> As per option 3 right now the response argument list is going to be something like one of `,ssssss ,sss ,s ,` OSC does add in `[]` as valid parts of the typestring and rtosc should handle those fine. Perhaps using them to signify "This is a message which is array valued, but explicitly an empty array? There's also N which from the OSC 1.1 spec:
> 
> > N Null: (aka  nil,  None,  etc). No  bytes  are  allocated  in the argument data

So basically, adding [] or alternatively ,N instead of sending an empty list from the engine, with possibly some work on the zest side to correctly handle it at the receiving end?

> > Option 1 would be the best, but I never had full luck tracking down all of the origins of the bad messages: zynaddsubfx sending the wrong messages, zyn-fusion's osc-bridge getting the wrong data, osc-bridge interpreting the data wrong, something else, etc

Yeah, looking at the thread that would seem to reopen a whole different can of worms, although it is compelling to fix the actual problem rather than workarounding it.

**Comment by fundamental** [comment]
> So basically, adding [] or alternatively ,N instead of sending an empty list from the engine, with possibly some work on the zest side to correctly handle it at the receiving end?

Yep, though to be clear that would be sending those as argument types, not as string values. Another undiscussed option would literally be sending a string value to say "we don't have any results for the search", though IMO that's less clean than using ,N or ,[].

**Comment by polluxsynth** [comment]
Yes, sorry, certainly ,N as the type tag. After reviewing the code I opted for N as it seemed cleaner somehow - the /bank/search_results reply normally does not contain the array type tags [ ] so it seemed lopsided to only do so when the list was empty (although of course they could be added always, but I didn't feel the small added complexity was warranted).

As it turns out, the fix for this particular thing was simple - just have Zynaddsubfx send the ,N type code when the list is empty. No change was actually required in Zest, it picks up the single argument as the `nargs == 1` case, and the rtosc functions correctly return an empty argument string when the type tag is ,N.

Ok, good to get this sorted out, now back to the real task at hand.

While working on this I've tried to emit some helpful messages to the message area, both in case of a successful write and also in the case of failures. One step was simply to have Zest pick up /alert messages and display them, which brings me to a suggestion when it comes to using the two lines of the messaging area: I was thinking if the top line should be reserved for tooltips, and the bottom line for messages (/alert OSC messages as well as messages generated by Zest itself)? I think it would make it more obvious to users the distinction between tooltips vs. messages (or put another way, informational messages explaining the various widgets, vs. error and affirmative messages as the result of verious operations such as write).

**Comment by fundamental** [comment]
Seems reasonable. I'm not sure if there are any long tooltips which justify using both lines. For those I could see a policy of having tooltips _usually_ be on the first line and have messages _usually_ be on the second line. If that route is taken, then some sort of color/font difference would be useful.

**Comment by polluxsynth** [comment]
Fixed in the first commit ("MiddleWare.cpp: Send OSC type tag ,N for empty bank search") in https://github.com/zynaddsubfx/zynaddsubfx/pull/181, although I forgot to reference this issue in the commit.
