### ISSUE TITLE
Modulation amount doesn't change when modwheel.depth or modwheel.exponential changed

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#345]
When adjusting the modwheel.depth or modwheel.exponential parameters, the actual applied modulation amount does not change until the modulation control (MIDI CC#1) is changed. While not critical, this makes adjusting the parameters confusing, as the change is not effected until the modwheel is moved.

**Comment by fundamental** [comment]
Thanks for raising and fixing the issue.

**Comment by polluxsynth** [comment]
Thanks for merging the PR - I've since realized that there are couple of other parameters which have a similar issue, so I'll create a separate PR fixing the rest of them. I don't think it's worth raising a new issue though.
