### ISSUE TITLE
Sustain pedal weirdness

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#346]
Set up a patch with a long release, say 5 seconds. Set key mode to Legato

Do the following:
- Press a key and hold it until the volume envelope reaches the sustain phase.
- Press the sustain pedal
- Release the key. (Now no keys are pressed on the keyboard). The note is still in its sustain phase as expected.
- Release the sustain pedal. The envelope starts its release phase. (Now neither any keys nor the sustain pedal are depressed).
- Try to play another key. While the new pitch is heard during the release phase, the note doesn't retrigger. First when the original note has completed its release phase can a new note be retriggered.

It is as if releasing the sustain pedal allows the voice to begin its release phase, as expected, but is still not counted as the key being released as far as the legato voice mode is concerned, i.e. the key assigner still believes a key is depressed and thus will not retrigger any new voices.

**Comment by polluxsynth** [comment]
Fixed in https://github.com/zynaddsubfx/zynaddsubfx/pull/191 .

@fundamental: I'm not sure if it's ok for me to close issues that I've reported and that have been solved, or in a more general sense, if the original author of the issue should close the issue once he/she deems it has been satisfactorily resolved, or it should be up to you?

**Comment by fundamental** [comment]
Ideally I'd remember to close some of the related issues (to save you the trouble), but I've got no problem with anyone else closing an issue if it is resolved.
