### ISSUE TITLE
Some filter questions - and a possible bug (or two)?

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#347]
This is something I've wanted to ask for a while but haven't dared ... :-)

To illustrate what I mean, bring up Strings Pad 1 in the Strings bank. Go to the Filter pane in the Envelope and Lfos tab. Press the filter heading ("General") to bring up the filter frequency graph, and select filter type LP2. Turn Sense down to remove all velocity sensiivity for the filter (to make it easier to illustrate my point). Q in this patch is set to 0.69.

The first question is, what are the LP1 and LP2 settings? The documentation mentions something about 1st and 2nd order filters, but there is a parameter for the number of stages of the filter which I would expect would correspond to the order, and the difference I can see from a user perspective is that LP1 seems to have a flatter response and doesn't respond to Q at all, whereas LP2 seems more like a classic synth filter. I haven't dived into the code which I can do of course, but I was hoping for a high-level description (which I might be able to put in the documentation if I can get my head around it).

My second question is this: The filter graph with the patch set up as above looks fairly straight up to the cutoff point, then rolls off nicely. However, when Q is decreased, the filter graph becomes affected long before the cutoff frequency - it looks as if the cutoff frequency is brought down at the same time as the rolloff is decreased. At first I thought there was some unwanted interaction between Q and the cutoff frequency, as audibly the sound gets increasingly darker when the Q is brought down from 0.69 to 0.1 (the minimum value). However, looking at the graph this seems to be solely because the resonance is brought down, although I've never seen a synth filter behave in this manner. I'm not saying its a bad thing, it was just unexpected to me. I assume it's one of those Zyn quirks that takes some getting used to. Without saying I know enough about the underlying mathematics, my gut feeling is that the 0.69 resonance value corresponds to a resonance setting of 0 for a classic synth filter, and going below that is something that normally would not be possible in the analog domain without introducing additional circuitry (read: cost) into the filter.

However, there's something else too: There also seems to be some sort of a time factor between the indicated value and the actual Q setting. To illustrate this, press and hold a note, and while holding it, bring up the Q by clicking on the knob and dragging the mouse upwards. Both audibly and in the graph, the filter resonance increases. Now pull the Q down to its minimum value (0.1) fairly quickly to remove all resonance. Note how there still appears to be some remaining resonance. Now retrigger the note. The sound is audibly darker, indicating that the Q now really is at the value set. Again, pull the Q up and then down again quickly, and notice how advancing the Q pulls it up but when the Q is pulled down to min again, it does not return the value it had when the Q was at its minimum value (0.1). However, if the note is retriggered, or the Q parameter re-clicked and dragged a bit, it jumps to the value it should be. Releasing the note also seems to bring the Q into line with what it sould be. It seems to be related to how fast the Q is changed; if the value is changed slowly the parameter actually does seem to track the indicated value in the UI better.

A final issue concerns adjusting the filter cutoff and Q using MIDI CC (#74 and #71 respectively). When the cutoff (CC#74) is changed, it is immediately heard in the sound. However, when the resonance (CC#71) is changed, it requires a change of the cutoff (CC#74) in order to be heard. Looking at the code in Controller.cpp and Part.cpp, there doesn't seem to be any specific update calls to the synth engine when either of the parameters are received, so I assume the synth engines monitor the cutoff parameter for changes but fail to do the same for Q (haven't had a look (yet)).

I'm wondering if this could be related to the fact that cutoff frequency changes are often cheap in terms of CPU power, whereas Q changes can require a larger recalculation of all filter coefficients, thus being more costly in terms of processing power, and consequently something that should not be done too often (is that the reason for the previously mentioned seemingly sluggish response of Q parameter changes too?).

**Comment by polluxsynth** [comment]
Ok, so I think I figured out LP1 and LP2, basically they seem to be 1st and 2nd order filters, with the 'stages' parameter governing how many stages are cascaded to form the final filter. This explains the lack of resonance for LP1 as a first order filter with its sole real pole cannot exhibit any resonance. I haven't penetrated if all the conjugate poles for LP2 are in the same place in the s plane, or they are spread out in any way (like along the circumference of the left half of a circle as would be the case for a Butterworth type filter), i.e. is the filter comprised of a number of identical stages cascaded, each with its own resonance control, or the resonance is around the whole filter. Not really important for this issues, just curious.

**Comment by fundamental** [comment]
> . is the filter comprised of a number of identical stages cascaded

Yep. Perfectly identical with your standard zyn filters. The filter coefficients are calculated once and don't change as the stages are layered on. I'd say that it would be more ideal if there was some pole spreading, but that design decision was made before I joined the project and would certainly alter the sound characteristic.

**Comment by fundamental** [comment]
(responding out of order as I got confused by the issue renaming in my email inbox
> The first question is, what are the LP1 and LP2 settings?

As you figured out it's first or second order filters. i.e. one pole/zero or two poles/zeros

> Without saying I know enough about the underlying mathematics, my gut feeling is that the 0.69 resonance value corresponds to a resonance setting of 0 for a classic synth filter,

Generally the transition point from being underdamped to overdamped in a resonant system (filters included) is sqrt(2)/2 i.e. 0.707, so you're pretty close to that value :)

> and going below that is something that normally would not be possible in the analog domain without introducing additional circuitry (read: cost) into the filter.

It's pretty easy to get out different Q values in physical circuits, but people are going to stick to what sounds good, whatever that may be. The key difference with any physical analog circuitry is that there's going to be some level of non-linear distortion which breaks all of the mathematical theory around filters, but also yields some great sounds and opens up the door for self oscillation. So, if you want a musical filter, quite often you're going to design it with a high Q value in mind (because they sound fun) and if you're building an instrumentation filter you're going to stick to that value of 0.707 to maximize your passband (as otherwise it droops or raises your response prior to F_c).

> However, looking at the graph this seems to be solely because the resonance is brought down, although I've never seen a synth filter behave in this manner.

I've got my own minor gripes with the exact formulation of zyn's filters as you can compensate for how some of the terms relate for each other, but I'd imagine a bit of the surprise is that most synths hide what they're doing under the hood. Generally you're not seeing a ton of calculated graphs elsewhere unless you get stuck in a signals and systems class.

> if the value is changed slowly the parameter actually does seem to track the indicated value in the UI better.

Sounds like you ran into the filter interpolation routines and by the sounds of the other issues reported after this one you've sifted through that system a bit. The general intent with any interpolation is to avoid zipper noise or other artifacts rather than to add intentional lag.

>  However, when the resonance (CC#71) is changed, it requires a change of the cutoff (CC#74) in order to be heard

I'm going to get to the PR related to Q updates in a bit, but I suspect you found the missing feature.

> I'm wondering if this could be related to the fact that cutoff frequency changes are often cheap in terms of CPU power, whereas Q changes can require a larger recalculation of all filter coefficients

They're both full recalculations. I think you might be able to get away with partial recalculations for some filter topologies, however that's not something that has appeared to be worthwhile so far.

**Comment by polluxsynth** [comment]
> > . is the filter comprised of a number of identical stages cascaded
> 
> Yep. Perfectly identical with your standard zyn filters. The filter coefficients are calculated once and don't change as the stages are layered on. I'd say that it would be more ideal if there was some pole spreading, but that design decision was made before I joined the project and would certainly alter the sound characteristic.

I suppose if one wanted to one could add another filter mode, but honestly I do think the filters sound pretty good, and there's always the Moog filter which I assume models the pole arrangement of its analog counterpart.

> > Without saying I know enough about the underlying mathematics, my gut feeling is that the 0.69 resonance value corresponds to a resonance setting of 0 for a classic synth filter.
> Generally the transition point from being underdamped to overdamped in a resonant system (filters included) is sqrt(2)/2 i.e. 0.707, so you're pretty close to that value :)

> > However, looking at the graph this seems to be solely because the resonance is brought down, although I've never seen a synth filter behave in this manner.
> 
> I've got my own minor gripes with the exact formulation of zyn's filters as you can compensate for how some of the terms relate for each other, but I'd imagine a bit of the surprise is that most synths hide what they're doing under the hood. Generally you're not seeing a ton of calculated graphs elsewhere unless you get stuck in a signals and systems class.

I should have said I've never _heard_ a synth filter behave in this manner. Before looking at the graph, I thought there was some erroneous coupling between Q and cutoff frequency, so that bringing the Q down for some reason brought the cutoff frequency down too.

> > if the value is changed slowly the parameter actually does seem to track the indicated value in the UI better.
>
> Sounds like you ran into the filter interpolation routines and by the sounds of the other issues reported after this one you've sifted through that system a bit. The general intent with any interpolation is to avoid zipper noise or other artifacts rather than to add intentional lag.

Yes I reallize that. Especially with computer based UI (rather than a hardware knob) I'd expect it's exacerbated by the fact that the update frequency is rather low (compared to the scan frequency for a potentiometer or encoder).

> > I'm wondering if this could be related to the fact that cutoff frequency changes are often cheap in terms of CPU power, whereas Q changes can require a larger recalculation of all filter coefficients
> 
> They're both full recalculations. I think you might be able to get away with partial recalculations for some filter topologies, however that's not something that has appeared to be worthwhile so far.

Ok, well then, the whole issue seems to be rooted to the lack of filter recalculation when just the Q is changed as addressed in the PR.

**Comment by fundamental** [comment]
> I suppose if one wanted to one could add another filter mode, but honestly I do think the filters sound pretty good, and there's always the Moog filter which I assume models the pole arrangement of its analog counterpart.

Yeah, zyn's filters have limitations, though they work. Generally their failing relate to behavior under higher modulation rates, the noted Q/Fc linkage, and lack of non-linearities in the basic filter types. Hard to fix the first and third issues though without running into other historic design decisions in zyn.

> I should have said I've never _heard_ a synth filter behave in this manner

Heh, guess I was being too literal.

**Comment by polluxsynth** [comment]
I think though that for Zyn, most of the character of the sound comes from the superb oscillator design, so the need to add character using non-linearities in the filters is reduced, compared to a classic analog synthesizer which uses mundane sawtooth etc waveforms where all the character needs to come from the filter.

**Comment by fundamental** [comment]
Agreed. The oscillator on it's own could make for a pretty competent synth
plugin.

**Comment by polluxsynth** [comment]
The questions have been answered, and the bugs addressed in PR's, so closing this thread.
