### ISSUE TITLE
SVF filter clicks when filter freq or Q changed in Fusion

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#348]
I've reproduced this by calling up factory preset Strings / Strings Pad 1, then changing the filter type to SVF. Changing the filter freq or Q in Fusion causes a lot of clicking, but only as long as the knob in question is changed; there seems to be a smoothing operation which continues some time after then knob is no longer turned, and during this time there is no clicking.

There is no clicking when changing MIDI CC#74 or #71 either, so this would indicate that it's not simply the fact that all coefficients are updated for the filter that causes the clicking (because both when the filter freq and Q are changed, all coefficients are updated), but rather something else.

**Comment by fundamental** [comment]
![2022-03-19-svf-glitch](https://user-images.githubusercontent.com/766621/159133130-1cf3b087-04ef-4ec5-b890-ce7f1ab25d47.png)

Confirmed. SVF should be very smooth with transitioning between values, so this is likely mostly a function of porting over interpolation logic which was implemented in the other filter class.

**Comment by polluxsynth** [comment]
The odd thing though is that the clicking is only heard while adjusting the parameter in the UI, while the final smooth_float smoothing is taking place after the UI changed has stopped, there is no clicking, and neither while swept by the envelope.

**Comment by fundamental** [comment]
Interestingly I can't seem to see an issue with the implementation from the point that updated frequency/q information is received in the OSC handlers in FilterParams, to the timestamp update in FilterParams, to how SVFilter is running the update. Seems like everything is right, though there are more artifacts than I'd expect...

**Comment by friedolino78** [comment]
from only reading this conversation I think it could be the smoothing filters having difficulties handling large jumps coming from gui while CCs come in more smoothly.

**Comment by polluxsynth** [comment]
Turns out the problem was that the setstages() method is called (among others) when the UI changes the frequency, Q, filter tracking or gain, resulting in cleanup() being called, which resets the filter state. Bringing in the same fix as in AnalogFilter.cpp, namely only call cleanup() if the number of stages is actually changed, cures the problem. (PR submitted now).

A bit bewildered why the design is such that several different parameter methods are called when only a single parameter is updated, but that is a different issue altogther...

EDIT: Regarding the smoothing filters, there seem to be a couple of different ones. The individual filters (well, at least Analog and SVF) implement a smoothing over the buffersize using the Value_Smoothing_Filter class, which spreads out the frequency change over the range of the buffer, keeping the filter frequency constant for 8 samples at a time. Then there's the smooth_float type, which is more sluggish, and operates on the values coming in via OSC from the UI, but not on CC changes.

**Comment by friedolino78** [comment]
so the Value_Smoothing_Filter is more of a linear interpolated control rate supersampling, while smooth_float is a true LP-filter. but i would think that it would be needed especially for smoothing the stair steps of the 7-bit CC-resolution.

**Comment by polluxsynth** [comment]
I'm a bit ambivalent when ti comes to CC smoothing, on the one hand as you say, the resolution is low, but on the other hand, I would think that the update rate of a CC control might be higher than updates from the UI, and also, in an automation scenario, a user might require quick CC changes and would not appreciate too much smoothing.

**Comment by fundamental** [comment]
Fixed
