### ISSUE TITLE
Format graphs are empty

### ISSUE THREAD

**Issue by zynmuse** [zynaddsubfx/zyn-fusion-issues#349]
When using any of the formant filters the frequency graphs show nothing.
Using the old (fltk) interface they work correctly.
![formant](https://user-images.githubusercontent.com/63783478/158685459-bfc0c92f-d3bc-43ea-a335-b10b40d496e5.jpg)

**Comment by fundamental** [comment]
Hm. Looks like a regression on mruby's side. d0b5096781d41e0362a6658ab870daee6ef8eb5a in mruby-zest-build should provide a workaround.

**Comment by zynmuse** [comment]
I don't understand how to implement the workaround. It hasn't been commited to mruby-zest-build archive and this issue has been closed.

**Comment by fundamental** [comment]
?

https://github.com/mruby-zest/mruby-zest-build/commit/d0b5096781d41e0362a6658ab870daee6ef8eb5a

**Comment by zynmuse** [comment]
Thanks.
Don't know what I was looking at!

**Comment by zynmuse** [comment]
I see. 
I was looking at zynaddsubfx/zyn-fusion-build. Your changes were to mruby_zest/mruby-zest-build.

**Comment by fundamental** [comment]
Yep. Ideally zyn-fusion-build should be changed exceptionally rarely with all the real changes going into the backend (zynaddsubfx/zynaddsubfx) or the fairly poorly named GUI repo (mruby-zest/mruby-zest-build)

**Comment by zynmuse** [comment]
I'm OK with that. Still learning!
The change works fine!

**Comment by fundamental** [comment]
I will say that there is still some quirkyness unrelated to this regression in the view. Mostly in that the fltk UI appears to assume fixed Q values, where the fusion GUI uses whatever Q value comes from the current filter, but doesn't update when the Q value is changed.
