### ISSUE TITLE
Clearly Document Pricing Info And Story On Home Page And Zyn-Fusion Page

### ISSUE THREAD

**Issue by fundamental** [zynaddsubfx/zyn-fusion-issues#35]

**Comment by mikobuntu** [comment]
After checking out Zyn-Fusion through Gumroad I noticed a typo for the linux package.
![zynconfuzion](https://cloud.githubusercontent.com/assets/335217/20680341/88c86682-b596-11e6-9f40-55427e293848.png)
It should be x86_64 not x86_62    . thanks :)

**Comment by fundamental** [comment]
> It should be x86_64 not x86_62    . thanks :)
This should now be fixed

--Mark
