### ISSUE TITLE
Toggle button labels

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#352]
This is a very minor but old peeve of mine: A few of the toggle buttons in Zyn have labels which don't actually indicate what the button does when it is depressed/illuminated.

For instance, the ADSR envelopes have a LIN/LOG button, but that just says that it toggles between those two, not which is the enabled or disabled value. So IMHO, the label should be LIN ENV or something, so that when it is enabled, it indicates that the envelope is linear. Of course this doesn't explain what the alternative value is, but I think it's more important given the choice to clearly indicate what the enabled value is - the alternative value is either fairly obvious or readable in the documentation.

Similarily, the portamento TR.TYPE button should be labelled >= THRESH or something similar to indicate what is actually does when enabled.

The corresponding tooltips should also be updated accordingly.

**Comment by fundamental** [comment]
I'm guessing something like 
![2022-03-23-linlog](https://user-images.githubusercontent.com/766621/159819120-1cbd549d-1d3c-4b7e-aa11-3420978a0f83.png)
 would be more ideal.

**Comment by polluxsynth** [comment]
Yes, absolutely. I don't think there are any such switches in Zyn anywhere yet?

**Comment by polluxsynth** [comment]
Alternatively, one could simply replace them with drop down lists, having only two items.

**Comment by fundamental** [comment]
I'd prefer some other element than a 2 element dropdown. Something just doesn't feel right to me about having a dropdown with so few choices.

**Comment by polluxsynth** [comment]
Yeah, I sortof agree with you, one would expect that a dropdown would have more than two elements.

Not too sure about the slide switch though, although it certainly mimics a common and easily understandable physical switch, it seems to break with the clean graphic design of Fusion.

One idea I had is a split button, where only one half lights up at any one time, with a corresponding legend in each half.

Another idea is to keep the buttons as they are currently, but change the label depending on the actual position, so that for instance, it shows LOG on a black background for the envelope mode, then when clicked shows LIN on a blue background.

I'll have to experiment a bit and report back.

**Comment by zynmuse** [comment]
Radio button would work good if it can be implemented. So two buttons side by side one LOG and one LIN and whichever you press will light up and the other will go out.
Something like that is already used on the left of the zyngfusion panel for part/kit/voice/ selection

**Comment by polluxsynth** [comment]
Good point about the radio buttons. I like the idea of reusing existing graphic concepts rather than inventing a new one, for such a relatively insignificant change.

**Comment by polluxsynth** [comment]
Something like this:

![Linlog button with lin depressed](https://butoba.net/pix/linlog-lin-detail.jpg)

![Linlog button with log depressed](https://butoba.net/pix/linlog-log-detail.jpg)

**Comment by fundamental** [comment]
Ooh fancy :) I'll have to get that PR merged in after some quick sanity testing.

**Comment by polluxsynth** [comment]
Closing ticket now that the PR has been merged.
