### ISSUE TITLE
segfault: Jack reports error: Cannot delete key ..../event-types (BDB0073 DB_NOTFOUND: No matching key/data pair found)

### ISSUE THREAD

**Issue by avlapp** [zynaddsubfx/zyn-fusion-issues#353]
$ jackd --version
jackdmp version 1.9.20 tmpdir /dev/shm protocol 9

Arch Linux

$ zynaddsubfx -v

ZynAddSubFX - Copyright (c) 2002-2013 Nasca Octavian Paul and others
                Copyright (c) 2009-2019 Mark McCurry [active maintainer]
This program is free software (GNU GPL v2 or later) and
it comes with ABSOLUTELY NO WARRANTY.

Version: 3.0.6

$ zynaddsubfx

ZynAddSubFX - Copyright (c) 2002-2013 Nasca Octavian Paul and others
                Copyright (c) 2009-2019 Mark McCurry [active maintainer]
This program is free software (GNU GPL v2 or later) and
it comes with ABSOLUTELY NO WARRANTY.

Try 'zynaddsubfx --help' for command-line options.

Sample Rate =           48000
Sound Buffer Size =     256 samples
Internal latency =      5.3 ms
ADsynth Oscil.Size =    1024 samples
lo server running on 16879
[INFO] Nio::start()
Starting Audio: JACK
Jack buffer resized
Audio Started
Starting MIDI: JACK
MIDI Started
[INFO] exec-after-init
[INFO] startup OSC
[INFO] UI calbacks
[INFO] OSC replay
[INFO] auto_save setup
[INFO] NSM Stuff
[INFO] LASH Stuff
[INFO] Launching Zyn-Fusion...
[INFO] Loading system libzest.so
[INFO:Zyn] setup_pugl()
[INFO] Main Loop...
Jack reports error: Cannot delete key http://jackaudio.org/metadata/event-types (BDB0073 DB_NOTFOUND: No matching key/data pair found)
Deactivating and closing JACK client
Starting Audio: JACK
[INFO:Zyn] zest_tick()
Jack buffer resized
Audio Started
Starting MIDI: JACK
MIDI Started
[INFO:Zyn] zest_open()
[INFO:Zyn] Found Assets at /usr/lib/zynaddsubfx/
[INFO:Zyn] Starting Zyn-Fusion
[INFO:Zyn] Thanks for supporting the development of this project
[INFO:Zyn] Creating MRuby Interpreter...
[debug] parsing json file
[debug] json parsed succesfully
Jack reports error: Cannot delete key http://jackaudio.org/metadata/event-types (BDB0073 DB_NOTFOUND: No matching key/data pair found)
Deactivating and closing JACK client

**Comment by fundamental** [comment]
The errors from jack indicate an issue with the database on jackd's side. I've been advised that restarting jackd should resolve that specific problem. Let me know if you can replicate an issue on zyn's side.

**Comment by avlapp** [comment]
Restarting jack doesn't solve it.

**Comment by fundamental** [comment]
In that case I'd check either the jack daemon's bug tracker for steps to resolve, or the #jack channel on Libera. If there's still a zyn issue after the database issue is fixed I'd be happy to help with that problem, but I wouldn't personally know the exact fix for jackd.

**Comment by falkTX** [comment]
could it be zyn is trying to delete a property without checking that it exists?

**Comment by fundamental** [comment]
I considered that as a possibility, but since I'm not able to replicate the issue and ardour devs indicate DB_NOTFOUND is generally a sign of a problem on the jackd side, I don't think it's particularly likely.

**Comment by falkTX** [comment]
will be impossible to fix if we cant replicate it.
deleting /dev/shm/*db* stuff likely makes this go away, worst case a reboot does it too. would be interesting to know if it still keeps happening anyway

**Comment by avlapp** [comment]
> will be impossible to fix if we cant replicate it. deleting /dev/shm/_db_ stuff likely makes this go away, worst case a reboot does it too. would be interesting to know if it still keeps happening anyway

Keeps happening anyway:
[debug] json parsed succesfully

Jack reports error: Cannot delete key http://jackaudio.org/metadata/event-types (BDB0073 DB_NOTFOUND: No matching key/data pair found)
Deactivating and closing JACK client

**Comment by avlapp** [comment]
Bug is confirmed 
https://bugs.archlinux.org/task/74283?project=5&string=zynaddsubfx

**Comment by edomango05** [comment]
i' m having the same issue too ( Arch Linux )

**Comment by enderprism** [comment]
It started to work again on Manjaro, and I have no idea why. I also recently switched to EndeavourOS which uses Pipewire by default and the issue does not exist here. The only trouble I have now is that when using Jack (so I can see it in my Pipewire connection graph) or other sound servers, Zynaddsubfx doesn't connect automatically to my speakers.
