### ISSUE TITLE
Windows Crosscompile with Ming will not work due to missing portaudio deps in WSL 

### ISSUE THREAD

**Issue by mnstine** [zynaddsubfx/zyn-fusion-issues#355]
Is this type of build something that is supportable?  Portaudio is not listed in the dependencies download.  And I think because WSL does not load the Linux Windowing system portaudio is not installed.

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"

**Comment by mnstine** [comment]
libtool: link:  x86_64-w64-mingw32-gcc -shared lib/.libs/libportaudio-2.dll.def  src/common/.libs/pa_allocation.o src/common/.libs/pa_converters.o src/common/.libs/pa_cpuload.o src/common/.libs/pa_dither.o src/common/.libs/pa_debugprint.o src/common/.libs/pa_front.o src/common/.libs/pa_process.o src/common/.libs/pa_stream.o src/common/.libs/pa_trace.o src/hostapi/skeleton/.libs/pa_hostapi_skeleton.o src/hostapi/wmme/.libs/pa_win_wmme.o src/os/win/.libs/pa_win_hostapis.o src/os/win/.libs/pa_win_util.o src/os/win/.libs/pa_win_waveformat.o   -lwinmm    -o lib/.libs/libportaudio-2.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker lib/.libs/libportaudio.dll.a
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_cpuload.o: in function `PaUtil_InitializeCpuLoadMeasurer':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_cpuload.c:62: undefined reference to `__assert_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_debugprint.o: in function `vsnprintf':
/usr/include/x86_64-linux-gnu/bits/stdio2.h:80: undefined reference to `__vsnprintf_chk'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_debugprint.o: in function `PaUtil_DebugPrint':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_debugprint.c:119: undefined reference to `stderr'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_debugprint.o: in function `vfprintf':
/usr/include/x86_64-linux-gnu/bits/stdio2.h:130: undefined reference to `__vfprintf_chk'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_debugprint.o: in function `PaUtil_DebugPrint':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_debugprint.c:123: undefined reference to `__stack_chk_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_front.o: in function `InitializeHostApis':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_front.c:196: undefined reference to `__assert_fail'
/usr/bin/x86_64-w64-mingw32-ld: /home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_front.c:197: undefined reference to `__assert_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_front.o: in function `Pa_GetDeviceInfo':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_front.c:744: undefined reference to `__stack_chk_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_front.o: in function `Pa_IsFormatSupported':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_front.c:1094: undefined reference to `__stack_chk_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_front.o: in function `Pa_OpenStream':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_front.c:1228: undefined reference to `__stack_chk_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_front.o: in function `Pa_OpenDefaultStream':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_front.c:1311: undefined reference to `__stack_chk_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_process.o: in function `CopyTempOutputBuffersToHostOutputBuffers':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_process.c:1255: undefined reference to `__assert_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_process.o: in function `CalculateFrameShift':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_process.c:79: undefined reference to `__assert_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_process.o: in function `PaUtil_SetNoInput':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_process.c:455: undefined reference to `__assert_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_process.o: in function `PaUtil_SetInputChannel':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_process.c:464: undefined reference to `__assert_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_process.o: in function `PaUtil_SetInterleavedInputChannels':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_process.c:481: undefined reference to `__assert_fail'
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_process.o:/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_process.c:483: more undefined references to `__assert_fail' follow
/usr/bin/x86_64-w64-mingw32-ld: src/common/.libs/pa_process.o: in function `PaUtil_EndBufferProcessing':
/home/mnstine/zyn-fusion-build/deps/portaudio/src/common/pa_process.c:1651: undefined reference to `__stack_chk_fail'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:170: lib/libportaudio.la] Error 1
make[1]: Leaving directory '/home/mnstine/zyn-fusion-build/deps/portaudio'
make: *** [Makefile.windows.mk:73: build_portaudio] Error 2

**Comment by fundamental** [comment]
WSL, should work, though since I don't have any personal windows machines I haven't tested to see how it handles audio. It certainly handles GUI apps pretty well based on my experience.  Also, is this just using WSL to build the app or is this for only the cross compile build?

Based on the errors it looks like the latter. No guarantees, but you might want to see if portaudio has had another release as it could resolve some of the mingw issues.

**Comment by mnstine** [comment]
This is a Ubuntu desktop bash shell from the Microsoft store used just to crosscompile.

**Comment by mnstine** [comment]
I installed libasound-dev to try to see if that would be enough for it to compile but it looks like it needs portaudio system packages installed which are not there, because it is not a full desktop environment (I assume).

**Comment by mnstine** [comment]
Looks like I do need to setup hyper-v and have a fully bootable and working OS image to make this compile.  I was just testing to see if I could streamline this process.

**Comment by fundamental** [comment]
I'm sure there's someway to get it to work, but if WSL causes any headaches a VM would be the fastest way to get the software built.

**Comment by mnstine** [comment]
mnstine@DAWSTATION:~$ sudo apt-get install portaudio
[sudo] password for mnstine:
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package portaudio

Ok thanks.  Giving up now.... You can close this ticket.
Thanks for the help!

**Comment by fundamental** [comment]
For the record if you're crossbuilding for windows you shouldn't need to install portaudio yourself, it should be built in one of the stages, weird setup, but that's multiplatform for you..
