### ISSUE TITLE
Resonance tab missing from PADsynth

### ISSUE THREAD

**Issue by dancesWithBugs** [zynaddsubfx/zyn-fusion-issues#358]
In the old interface a resonance window can be accessed from PADsynth. An equivalent tab in zyn-fusion is available for ADDsynth, but not PADsynth.

![Selection_047](https://user-images.githubusercontent.com/75453205/166626038-bf386bf1-c5aa-42d4-aff9-c11fe06380f6.png)
![Selection_049](https://user-images.githubusercontent.com/75453205/166626048-41568a21-9928-41f8-86c0-973bdc0cb532.png)

**Comment by fundamental** [comment]
Resolved. Thanks for the PR :+1:
