### ISSUE TITLE
No GUI (Ubuntu 22.04)

### ISSUE THREAD

**Issue by jrezai** [zynaddsubfx/zyn-fusion-issues#371]
I'm on Ubuntu MATE 22.04. When I install _sudo apt-get install zynaddsubfx-lv2,_ there is no GUI for ZynAddSubFX in a Daw/Sequencer.

So then I tried installing zynaddsubfx_3.0.5-1kxstudio7_amd64.deb from kxstudio instead but when I try to open ZynAddSubFX in a DAW/Sequencer, I get:
```
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```
I tried it with both MusE sequencer and Qtractor.

ZynAddSubFX is looking for swrast_dri.so in

`/usr/lib/dri`

That file on my computer is in:

`/lib/x86_64-linux-gnu/dri`

If I use my distros package for ZynAddSubFX, there is no GUI, and when I try the kx studio .deb, there is no GUI and it crashes.

Any ideas? (it used to work fine in Ubuntu 20.04).

Thanks.

**Comment by fundamental** [comment]
That sounds like an issue with the openGL libraries on your system (which would impact other application as well). I do not have a fix to resolve the issue at this time.

**Comment by pgervais** [comment]
@jrezai This looks like an issue with how the distro packaged ZynAddSubFX rather than a bug with the codebase itself. Have you filed a ticket with the package maintainers?

**Comment by jrezai** [comment]
@pgervais I haven't filed a ticket with the package maintainers. I ended up building from source and ZynAddSubFX worked properly, so I think you're right that it's likely related to how the distro packaged it.
