### ISSUE TITLE
Build Issue on Ubuntu 22.04 pa_process (portaudio)

### ISSUE THREAD

**Issue by mnstine** [zynaddsubfx/zyn-fusion-issues#372]
Trying to build (cross compile) for Windows and getting this error.  I'm thinking they are not using portaudio on this version of Ubuntu?

![Screenshot 2022-10-03 210914](https://user-images.githubusercontent.com/65842646/193719449-9f26ae60-66ee-40fd-b38b-a8124db9e6cd.png)

**Comment by mnstine** [comment]
Just ran it on a down level 20.04 and it compiled fine.

**Comment by fundamental** [comment]
I suspect that upgrading the port audio version might resolve the issue on the 22.04 version of mingw, but I haven't confirmed this. Searching around some it sounds like a plausible explanation might be symbol visibility flags within the port audio library ( https://stackoverflow.com/questions/18165527/linker-unable-to-find-assert-fail ), so worst case I suspect it wouldn't be terribly difficult to patch the dependency (or add in -DNDEBUG) if it isn't resolved with a newer copy of portaudio.
