### ISSUE TITLE
Sound stops on FL Studio

### ISSUE THREAD

**Issue by nobody102** [zynaddsubfx/zyn-fusion-issues#373]
After about 5 minutes of use, the audio stops playing.  This is on Windows FL Studio 20.9 VST.

**Comment by fundamental** [comment]
That sounds like you're using a demo build of zyn-fusion.

**Comment by pgervais** [comment]
@nobody102 I'm closing this issue because it seems fundamental answered the question. Please comment if it's not the case and we'll reopen it.
