### ISSUE TITLE
AddSynth Voice List tab: Labels on sliders are wrong / not updated

### ISSUE THREAD

**Issue by VincyZed** [zynaddsubfx/zyn-fusion-issues#377]
![image](https://user-images.githubusercontent.com/50145178/206872423-7200717b-25f1-44a2-a7bc-9aefc688b7b4.png)

This one is pretty-self explanatory 🙂

**Comment by fundamental** [comment]
Mostly resolved via https://github.com/mruby-zest/mruby-zest-build/commit/cf9c9fed9b1fc0d968c9a0f52815045ece759fe0 There's likely some additional decisions about if the detune slider should modify the coarse detune, the fine detune, or both.
