### ISSUE TITLE
Kit Enable/Disable buttons don't work

### ISSUE THREAD

**Issue by VincyZed** [zynaddsubfx/zyn-fusion-issues#378]
The kits always stay enabled, even if, in this example, I turn off Kit 1 and 2 with the corresponding buttons.

![image](https://user-images.githubusercontent.com/50145178/206889021-4a600629-429f-467d-b386-92933faf9c24.png)

**Comment by fundamental** [comment]
Fixed via https://github.com/zynaddsubfx/zynaddsubfx/commit/255d8442407842841712f4cae0966969129a76a9
