### ISSUE TITLE
Can't use fine adjustment in Linux with Bitwig Studio

### ISSUE THREAD

**Issue by micahscopes** [zynaddsubfx/zyn-fusion-issues#379]
I've tried both toggling the fine adjustment button as well as holding down shift.  I just can't seem to get the fine adjustment working.

**Comment by fundamental** [comment]
Several hosts capture the shift key so plugins cannot see it, however clicking the fine button in the header should change the UI into fine adjustment mode. Does the click not keep the shift button toggled or is the button toggled, but the toggled button doesn't result in fine manipulation?

**Comment by micahscopes** [comment]
Clicking the fine button doesn't keep it toggled.  If I click really fast sometimes I can see that it does get toggled very briefly as it lights up for a moment.

**Comment by fundamental** [comment]
Resolved via https://github.com/mruby-zest/mruby-zest-build/commit/a74af0b5604a93c4b615660c97f41ac895049da7
