### ISSUE TITLE
Strange behavior of ADDsynth resonance in Zynthian

### ISSUE THREAD

**Issue by polluxsynth** [zynaddsubfx/zyn-fusion-issues#389]
(Originally I'd labelled this issue 'Resonance no longer works in ADDsynth', but after some more testing that does not seem to be the case (mental note: don't add issues after a late night debug session :-) ), so repurposing the issue for the second problem mentioned in the original ticket).

So far I've only been able to replicate this when running Zynaddsubfx on Zynthian: When a patch with resonance enabled in ADDsynth is loaded by Zynthian (either when loading what in Zynthian terminology is called a Snapshot, i.e. the complete setup of the machine, including the patches for the various synth engines used, _or_ when loading the patch individually for the intended part), the corresponding part will be silent (have only tried patches with only ADDsynth enabled, so I don't know how and if it interacts with SUBsynth or PADsynth). Zynthian uses the _/load-part is_ OSC command to load .xiz files to individual parts; however, when doing this manually using oscprompt, it works fine. It also works fine after doing Load Instrument from the patch browser in Zyn-Fusion. I have not been able to reproduce this outside of Zynthian.

Furthermore, it's not entirely true that the patch is completely silent: If Resonance is disabled, and notes played, they will be heard of course, and if held, they will continue to be heard when Resonance is enabled. However, when other notes are played while Resonance is enabled, the previously held notes will be muted for the duration of the new notes played (complete envelope from start of attack to end of release, as seen in the real-time amplifier envelope display). Once the new notes have completed, the held notes are heard again.

Obviously there is not a lot to go on at this point, so I'm really mentioning this because perhaps it will jog someone's mind regarding what could be the cause, or have any ideas on how to proceed with debugging.

The behavior is consistent with something happening when Resonance is enabled, so that any audio passing through it causes the entire audio stream to be disrupted when mixing with voices that do not pass through Resonance. 

This happens with the current master of Zynaddsubfx. Using the version supplied by Zynthian (3.0.5), it works fine.

**Comment by polluxsynth** [comment]
Did some more research, and learned that when Zynthian loads the patch (_/load-part is_), it also follows it with setting a bunch of CC's to the value corresponding to whatever is set for that part in Zynthian (Zynthian does not maintain a complete UI for Zynaddsubfx, but only a subset of what can be reached from the part settings pane, including things like part volume, portamento settings, bend range, etc). Crucially in this case, it includes the 'resonance bandwidth', CC78, which is set to 64 by default. This seems to cause the resonance module to misbehave, and I suspect it's due to some unitialized value related to the Resonance Bandwidth Depth setting (OSC port /part<n>/ctl/bandwidth.depth), because if this setting is changed from its default 64 in the Zynthian UI, and then the Resonance Bandwidth is nudged to any value (possibly even back to 64), normality is restored to the Resonance, and it behaves as normal again.

Once this has been done once for a part, it stays that way, so to me it seems like the internal value for the Resonance Bandwidth Depth is initialized to some far-off value, and when the Resonance Bandwidth setting is received (CC78), it causes something to go seriously wrong in the Resonance module, but when Resonance Bandwidth Depth is set to a sane value, followed by a new update to Resonance Bandwidth, normality is restored until Zynaddsubfx is terminated and restarted.

**Comment by polluxsynth** [comment]
Fixed here: https://github.com/zynaddsubfx/zynaddsubfx/pull/231

**Comment by fundamental** [comment]
Closing as fixed since the PR is merged.
