### ISSUE TITLE
Crash when loading plugin in Ardour on Linux

### ISSUE THREAD

**Issue by heuchi** [zynaddsubfx/zyn-fusion-issues#39]
I've installed the demo from zyn-fusion-3.0.1rc1-nov-20.tar.bz2 on my Ubuntu 14.04.5 LTS.
When I load the plugin into Ardour (self-compiled 5.4.0), it crashes immediately showing this in the console:
<pre>WARNING: this host does not send sample-rate information for LV2 UIs, using 44100 as fallback (this could be wrong)
[INFO] Opened the zynaddsubfx UI...
[INFO] Ready to run
[INFO:Zyn] zest_open(osc.udp://127.0.0.1:11896)
[INFO:Zyn] Found Assets at /opt/zyn-fusion/
[INFO:Zyn] Creating MRuby Interpreter...
[INFO] setting up runner
[debug] parsing json file
[INFO] init gl
[INFO] loading fonts
[INFO] window width=1181
[INFO] window height=659
[INFO] init window
Time for a fast load is 7.798ms load(0.008) class(0.001) spawn(7.789)...
[INFO] doing setup
[INFO] doing layout
[INFO] Running Layout Solver...
[INFO] launching program...
[INFO] ret code = 0
[ERROR] GLPSOL EXITED WITH ERROR CODE 1
[INFO] GLPK Solver finished...
[INFO] Read solution to layout...
[ERROR] The output file '/tmp/zest-w.txt' from glpsol was not found
[ERROR] This file is needed for layout
[ERROR] Please verify that there is a usable glpsol in the current directory
AM_PreferencesAudio::destroy instance destroyed
AM_PreferencesAudio::~AM_PreferencesAudio(), instanceCount after destruction: 0
AM_MemoryRecord closing down with 185 allocations vs 172 freed
Speicherzugriffsfehler (Speicherabzug geschrieben)
</pre>

This happens with lv2 and vst versions of the plugin. I also tried with Ardour 4.7.0 from another Linux distribution, which shows the same behaviour.

However, there is a way to avoid the crash: First open a Carla-Rack in Ardour, and then open the ZynAddSubFX plugin in Carla. Once this instance is open, I can open more instances directly from Ardour without using Carla in the middle. The error line about glpsol (ERROR CODE 1) disappears.

**Comment by heuchi** [comment]
I did some more research on this.
The plugin fails to provide a valid input file for the call to glpsol when it's loaded directly in Ardour. There are problems in most of the 'constraint' lines. Here is an excerpt from the diff of the /tmp/zest-temporary.mod files, first one is with Ardour, second one with Carla-Rack:
<pre>
1242c1242
< constraint15:  1 * virtw +  -9,000000 * effvertw = 0;
---
> constraint15:  1 * virtw +  -0.900000 * effvertw = 0;
1244c1244
< constraint16:  1 * virth +  -1,000000 * effverth = 0;
---
> constraint16:  1 * virth +  -1.000000 * effverth = 0;
</pre>

The version created in Ardour has ',' instead of '.' in the decimal numbers and some of the values are multiplied by 10. Might be a problem with the locale settings.

**Comment by fundamental** [comment]
Thanks a ton for investigating this. I should be able to test, replicate, and fix this issue now that the root cause is identified. I'll update this issue once I have a new build ready.

**Comment by fundamental** [comment]
Could you verify that this issue is fixed in the below version?
http://fundamental-code.com/zyn-fusion/zyn-fusion-3.0.1rc2-linux-demo.tar.bz2

**Comment by heuchi** [comment]
I can confirm it's fixed. It now loads without any problems here.
