### ISSUE TITLE
Adaptive harmonics power >=100 wrecks the oscillator

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#40]
![selection_018](https://cloud.githubusercontent.com/assets/491704/20608788/445a6d2e-b285-11e6-9da0-df3489de1495.png)

Setting the Adaptive harmonics Power to 100 results in a flat (silent) waveform). everything above is a +1 DC offset waveform.

Power = 100
![selection_019](https://cloud.githubusercontent.com/assets/491704/20608822/7ed12bdc-b285-11e6-8850-e9f3e3197821.png)

Power > 100
![selection_020](https://cloud.githubusercontent.com/assets/491704/20608832/9093a818-b285-11e6-8a4b-029ec99a46f0.png)

Every adaptive harmonics mode has this problem. ADDsynth and PADsynth both are affected.

**Comment by fundamental** [comment]
Nice find. It looks like the metadata that Zyn exposes was incorrect for the Zyn OSC API. Looking at the UI I see 'Padaptiveharmonicspar' has a maximum of 100 and when it's defined in OscilGen.cpp it's defined 0 to 127. The XML serialization confirms that it should be defined as 0 to 100.
