### ISSUE TITLE
Zynaddsubfx GUI doesn't show up in Ardour

### ISSUE THREAD

**Issue by sjomae** [zynaddsubfx/zyn-fusion-issues#404]
```
ardour8 -v
Ardour8.6.454 (built using 8.6-465-gc37d523b2e and GCC version 14.2.1 20240805)
```

```
$ zynaddsubfx -v

ZynAddSubFX - Copyright (c) 2002-2013 Nasca Octavian Paul and others
                Copyright (c) 2009-2019 Mark McCurry [active maintainer]
This program is free software (GNU GPL v2 or later) and
it comes with ABSOLUTELY NO WARRANTY.

Version: 3.0.6

```
Adding the LV2 plugin seems to go fine, but the gui doesn't show up. Standalone gui works fine.

**Comment by fundamental** [comment]
Are you able to replicate this issue with a build of the development version of zynaddsubfx?

**Comment by sjomae** [comment]
Works, latest git zyn, latest version in ardour.
There is a ardour related fix apparently
https://discourse.ardour.org/t/zynaddsubfx-gui-not-showing-in-8-7/110705/3

**Comment by fundamental** [comment]
Thanks for the followup
