### ISSUE TITLE
No "Bypass global filter" switch in ADDsynth?

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#41]
I can't locate the checkbox to bypass the global filter for active ADDsynth voice?

It is missing?

**Comment by fundamental** [comment]
It's there, just not where you'd expect it.
Add Synth -> Voice -> Amplitude -> General -> Bypass

**Comment by unfa** [comment]
Could it be labeled "Bypass Global Filter" instead of just "Bypass"?
Right until I saw the tooltip I still wasn't sure it's the right switch.

![selection_033](https://cloud.githubusercontent.com/assets/491704/20764534/e28149f2-b72e-11e6-839c-7996cbe3d9c3.png)

I think there's room to make the two buttons "Bypass" and "Reson" bigger and have more precise labels:

"Bypass Global Filter" and "Resonance"

**Comment by fundamental** [comment]
On 11-30, unfa wrote:
> Could it be labeled "Bypass Global Filter" instead of just "Bypass"?
> Right until I saw the tooltip I still wasn't sure it's the right switch.
> 
> ![selection_033](https://cloud.githubusercontent.com/assets/491704/20764534/e28149f2-b72e-11e6-839c-7996cbe3d9c3.png)
> 
> I think there's room to make the two buttons "Bypass" and "Reso" bigger and have more precise labels.
That sounds pretty reasonable.
I've got to invest some time in the layout algorithms to make sure that
this shows up nicely at multiple sizes

**Comment by fundamental** [comment]
![zyn-fusion-bypass](https://user-images.githubusercontent.com/766621/30244701-926e3adc-9591-11e7-823d-4e9c79530c9c.png)
