### ISSUE TITLE
ADDsynth Harmonic tab controls need arrangement tweaks

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#42]
I hope the drawing describes it well:

![selection_021](https://cloud.githubusercontent.com/assets/491704/20609039/f91fdada-b287-11e6-9790-2ad2a81c2406.png)
Also - there's a lot of space there, could these elements be a bit bigger, wider to use that space in a more optimal way?

**Comment by fundamental** [comment]
This was altered along with other layout changes for 3.0.2 
![zyn-fusion-harmonics](https://user-images.githubusercontent.com/766621/30220524-b3722806-948d-11e7-9e90-5fb671d149e9.png)

Closing as fixed
