### ISSUE TITLE
Allow chaning ADDsynth voice modulation depth in realtime

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#50]
I wish I could automate/MIDI-control the amount of modulation applied to an ADDsynth voice in realtime, mid-note just like it works for the filters.

I think it'd make it much easier to make complex sounds with automating the individual modulation amounts. I haven't experimented with pitches, but that'd also rock.

**Comment by fundamental** [comment]
Experimentally added via https://github.com/zynaddsubfx/zynaddsubfx/commit/24e48c507dde62e95d4aadf7e5477f48faa70bc4 . Testing indicates that the volume parameter really needs more resolution than the existing 7 bits.
