### ISSUE TITLE
install-linux.sh requires the existence of /usr/share/zynaddsubfx

### ISSUE THREAD

**Issue by cocreature** [zynaddsubfx/zyn-fusion-issues#52]
The install script calls `ln -s /opt/zyn-fusion/banks /usr/share/zynaddsubfx/banks` which will fail if `/usr/share/zynaddsubfx` does not already exist (as it is the case on a clean system). I don’t think there is a good reason to expect this directory to be present, i.e., installation should also work on a clean system.

**Comment by fundamental** [comment]
Thanks for pointing this out, it will be fixed in the next release
