### ISSUE TITLE
Virtual Keyboard Loses Keyboard Focus Unexpectely

### ISSUE THREAD

**Issue by fundamental** [zynaddsubfx/zyn-fusion-issues#55]
Budislav Stepanov:
> Also in every synth when you playing some sound with pc keyboard you can
> navigate through ui and play with all elements independently on what you do
> with your keyboard and sound never stops. I notice when I playing in Zyn
> with pc kb and click in browser it stop playing on kb and start to type in
> comments. In part settings I am playing with kb than I change some
> parameters than it freeze sound and start type in key mapping. So this is
> bug also.

**Comment by badosu** [comment]
Think might be this one: https://github.com/zynaddsubfx/zyn-fusion-issues/issues/101

**Comment by fundamental** [comment]
Should be fixed for now.
