### ISSUE TITLE
Add Experimental Unit Based Control

### ISSUE THREAD

**Issue by fundamental** [zynaddsubfx/zyn-fusion-issues#58]
Test the 3.1 idea of floating point controls+units+etc with widgets with the filter cutoff frequency control. This should set the ground work for how these sorts of changes will be done in the future.

**Comment by unfa** [comment]
Wow! Could we get better precision for all the parameters? No more zipper noise? No more EQ peak filter being either half step below or half step above the resonance I want to cut? :D

**Comment by fundamental** [comment]
> Could we get better precision for all the parameters?

That's the eventual plan.
Basically each parameter needs:
- A unit based representation
- An adapter on xml load to losslessly open old files
- A new OSC address/a one line change to the UI's parameter mapping
- A few minor changes to remove the old param
- Some unit tests to ensure that there are no regressions within the process

For each parameter that this is done to the net result is:
- A parameter with meaningful values without a series of ugly hacks
  i.e. moving the filter cutoff should hopefully log something like "base cutoff 4.24 kHz" in the tooltip pane when moving it
- Much more meaningful manual input i.e. the possibility of implementing a "type 100 Hz to set the control to exactly that frequency"
- Easier to configure MIDI mapped ranges (this includes host automation ranges based upon current plans)
- A much more fine tunable parameter
- Parameters which will tend to be easier to integrate with updates to already running notes

> No more zipper noise?

Hopefully zipper noise will be minimized and as stuff is exposed to hosts as 0.0 to 1.0 style parameters will not be limited to the 7 bit representation that many of them currently have.

> No more EQ peak filter being either half step below or half step above the resonance I want to cut?

Yep

**Comment by fundamental** [comment]
Progress is being made on this issue: https://github.com/zynaddsubfx/zynaddsubfx/commit/b650636e306237397ef106b86fc2aaa35ec5182b

- The UI needs to acknowledge the difference between linear and log encodings [**DONE**]
- There needs to be some sort of stickyness to parameters (e.g. for -100% to 100% make it easier to have +-25%/+-50%/etc )
- For the filters in particular some updates need to be made to the realtime interpolation code [**SCRATCHED DUE TO INSTABILITY**]]

**Comment by fundamental** [comment]
Floating point filter parameters have been merged into the master branch.
