### ISSUE TITLE
File Selector Bugs

### ISSUE THREAD

**Issue by fundamental** [zynaddsubfx/zyn-fusion-issues#6]
- [x] going to a directory, typing a partial path, and then clicking on the full path results in /base/partial/clicked when it should result in /base/clicked. Adding a check for in-directory vs partial directory state should solve this
- [x] Changing drives from C:// to Z:// isn't possible due to empty path behavior

**Comment by romainbar** [comment]
Also have a weird one on Linux 64: about half the directories are randomly missing for the list (but the output list is consistent and always presented in the same "random" order). I could not find any strong pattern, though I noticed in the few folders I checked that from the original list there are never more than 3 successive ones present or missing.

**Comment by fundamental** [comment]
@romainbar
With current versions of zyn I haven't been able to replicate this issue. I'm not sure if this bug is still here or not as you appear to be using an earlier version of zyn due to the jack uuid linker issue with the supplied version with zyn-fusion (that issue should be fixed and packaged ideally by the end of the weekend).

As per the "random" order that reenforces the idea that you're on an older version of zynaddsubfx as the current git version sorts all files and folders:
https://github.com/zynaddsubfx/zynaddsubfx/blob/master/src/Misc/MiddleWare.cpp#L883

**Comment by romainbar** [comment]
Directory browser fixed with latest demo. Thanks.

**Comment by fundamental** [comment]
Thanks for confirming the fix :+1:

**Comment by fundamental** [comment]
Quoting AJYoung on kvr:

> 1. File>Load Instrument/Master/etc. This file browser system as a whole is very problematic and > unstable.
>    
>    A) Navigate to any folder and try to select a blank option in the list on the right. Each time you click it will for some reason erase part of the full path down at the bottom. When this happens, you can't navigate to anywhere. Click enough times and the host crashes. If you try to manually type the folder path, it will also crash the host
>    B) Sometimes when navigating through folder, the option ".." to navigate up one level disappears. The only way to get back is to manually delete the folder name from the full path down at the bottom.

**Comment by fundamental** [comment]
Bugs should be fixed in 3.0.2rc2+ releases
