### ISSUE TITLE
Add MIDI Learn To ToggleButton/TriggerButton

### ISSUE THREAD

**Issue by fundamental** [zynaddsubfx/zyn-fusion-issues#60]

**Comment by mikobuntu** [comment]
@fundamental Glad to see you are working hard on Zyn :) Just a quick question.... Will Zyn's controls eventually all be exposed to some form of midi/automation on Linux [ obviously 128 parameters will never cover this scope and I am aware of the minimal midi controls ala LMMS ]? I can envisage an actual control unit that exposes each category somehow in a separate window. 
I ask because i would like to be able to automate a vast amount of different parameters within Bitwig in the LXVST version. Thanks :)

**Comment by fundamental** [comment]
On 12-17, Mikobuntu wrote:
> Will Zyn's controls eventually all be exposed to some form of midi/automation on Linux
> [ obviously 128 parameters will never cover this scope and I am aware of the minimal midi controls ala LMMS ]?

Well, if you can send different MIDI channels, that gets you up to
~0.026% of the parameters :p

The plan is to integrate VST exposed parameters (for typical host
automation) with the MIDI learn subsystem.
For the most part this is being documented/researched at:
https://github.com/zynaddsubfx/zyn-fusion-issues/issues/20

This presents a number of technical issues as the specifications for
VST/LV2 (to the best of my knowledge) assumes that there are a fixed
number of parameters exposed to the host and the names/bounds/etc of the
parameters is fixed.
Some hosts seem to have extensions which permit changing the total
number of parameters, or changing some information about them
(labels/etc) while running the plugin.
I've only heard about closed source VST plugins using these extensions,
so some trial and error will be involved in figuring out how to
practically use this.

For zynaddsubfx this set of technical problems doesn't really
involve the UI, so all the major bits which need changing aren't
affected by the UI (temporary) licensing.
In particular there's src/Plugins/ZynAddSubFX/* and
DPF/distroho/src/DistrohoPluginVST.cpp

Worst case there can be a set of N "par. 1"/"par. 2"/"par. 3"/etc which
simply map onto MIDI learn parameters with perhaps a means of learning
parameters from the UI without needing to explicitly bind them to a
particular MIDI CC.

Getting back to the original question:
- effectively everything can be exposed to a MIDI mapping already
- a VST/LV2 parameter would (likely) simply map 0..1 and feed it to the
  MIDI mapping layer (which already addresses the 0..1->meaningful value
  problem)
- some parameters now produce changes in already running notes
- more parameters will be reflected in running notes in future versions
- more parameters will have better parameter smoothing in future
  releases

> I can envisage an actual control unit that exposes each category
> somehow in a separate window.
> I ask because i would like to be able to automate a vast amount of
> different parameters within Bitwig in the LXVST version.

I think the most practical option is to let people click on individual
controls to expose them to a much smaller midi-learn/automation list.
Internally everything is a hierarchical string based path representation
though: http://fundamental-code.com/zyn-ports/

Comments/Feedback/Prior art on how this should be approached is
appreciated.

**Comment by mikobuntu** [comment]
Thanks for your very detailed reply :) It shows that you have already given this a lot of prior thought. 
I will think/research more on this subject and get back to you thanks @fundamental

**Comment by fundamental** [comment]
Toggle Buttons can now be automated. Trigger buttons are a different paradigm, so I'm going to close this issue for now and likely open a new one when dealing with trigger buttons
