### ISSUE TITLE
Wrong architeture for demo?

### ISSUE THREAD

**Issue by nklepeis** [zynaddsubfx/zyn-fusion-issues#61]
Get following error on 32-bit Fedora 24:
bash: /usr/bin/zyn-fusion: cannot execute binary file: Exec format error

Is there a version for my architecture?

Thx, Neil

**Comment by fundamental** [comment]
At the moment only a 64 bit linux and 64 bit windows build are distributed. During the closed beta additionally a 32 bit linux build and an experimental 64 bit OSX build were available, but neither received much attention.
 
I plan on revisiting this issue in the future as linux 32 bit simply needs packaging.

**Comment by fundamental** [comment]
UI Source is available 3.0.2  and onwards (along with full version binaries)
