### ISSUE TITLE
Live frequency chart preview for Filters

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#69]
I guess it's not a simple thing, but I think it'd be great to see the animated frequency response of the filters affected by the ENV, LFO or live operation by GUI or MIDI CC, resonance and other stuff. I guess a special switch "Live" or something could be nice, to make the static chart still available or programing the filter bank.

I initially thougth about this for the formant filters, because they all move so much, but I've noticed no filter charts respond to the ENV and LFO input.

![selection_084](https://cloud.githubusercontent.com/assets/491704/22306740/a37c0ca4-e340-11e6-91b7-b51435a6d7e7.png)

Also I've noticed that the chard doesnt't respond to changing the filter stages and Q value for Formant FIlters (other classes do react), while the sound is different, maybe that's a related thing.

**Comment by fundamental** [comment]
The problem with providing a 'live' view to the filter responses, is that there's multiple 'live' versions of the filter. In particular for every note there's a different instance of the filter and each instance is going to be at a different state due to envelopes/lfos/velocity senses/etc.

**Comment by unfa** [comment]
Hmm, you're right this would make sense only for monophonic patches.

**Comment by fundamental** [comment]
For now I'm going to close this. There may be some situation in the future which would motivate reopening this for monophonic setups.
