### ISSUE TITLE
LV2 plugin Missing `manifest.ttl`

### ISSUE THREAD

**Issue by simonvanderveldt** [zynaddsubfx/zyn-fusion-issues#7]
Upon adding the LV2 plugin to carla-rack I get the following errors in my terminal:

```
Error opening file /home/simon/.lv2/zyn-fusion/manifest.ttl (No such file or directory)
lilv_world_load_file(): error: Error loading file `file:///home/simon/.lv2/zyn-fusion/manifest.ttl'
lilv_world_load_bundle(): error: Error reading file:///home/simon/.lv2/zyn-fusion/manifest.ttl
```

Also, carla-rack doesn't allow me to open the GUI to edit settings. Judging by the contents of `manifest.ttl` from other plugins it's probably caused by the missing file, but I might be missing some GUI toolkit to render it. What kind of toolkit is used for the GUI?

**Comment by fundamental** [comment]
Whoops, it looks like my packaging script missed quite a few files in the lv2 folder. I'll have to update the demo soon to resolve that. In the mean time I've tared up just that folder if you want the missing files before I have time to repack the whole demo:

http://fundamental-code.com/tmp/ZynAddSubFX.lv2-missing-files.tar.bz2

The toolkit used for the GUI is a custom one named mruby-zest (as in https://github.com/mruby/mruby ). Most of the UI is built into the libzest.so file which is included in the linux dist. As long as that file can be located generally the rest of the assets (fonts, etc) can be found relative to that library.

**Comment by simonvanderveldt** [comment]
> Whoops, it looks like my packaging script missed quite a few files in the lv2 folder. I'll have to update the demo soon to resolve that. In the mean time I've tared up just that folder if you want the missing files before I have time to repack the whole demo:
> 
> http://fundamental-code.com/tmp/ZynAddSubFX.lv2-missing-files.tar.bz2

Thanks for the quick response and fix! This seems to have fixed the `manifest.ttl` errors :+1: 

> The toolkit used for the GUI is a custom one named mruby-zest (as in https://github.com/mruby/mruby ). Most of the UI is built into the libzest.so file which is included in the linux dist. As long as that file can be located generally the rest of the assets (fonts, etc) can be found relative to that library.

Thus far I've been unable to get the UI to show when running as an LV2 plugin.
`jalv.gtk3` only shows a single field, which is the "OSC Port". Command line output is the following:

```
~/.l/ZynAddSubFX.lv2 ❯ jalv.gtk3 http://zynaddsubfx.sourceforge.net
lilv_world_add_plugin(): error: Duplicate plugin <http://zynaddsubfx.sourceforge.net>
lilv_world_add_plugin(): error: ... found in file:///home/simon/.lv2/ZynAddSubFX.lv2/
lilv_world_add_plugin(): error: ... and      file:///usr/lib64/lv2/ZynAddSubFX.lv2/
Plugin:       http://zynaddsubfx.sourceforge.net
No appropriate UI found
JACK Name:    ZynAddSubFX
Block length: 1024 frames
etc.
```

`jalv.qt`only shows a "Close" button. Command line output is the following:

```
                       jalv.qt http://zynaddsubfx.sourceforge.net  
lilv_world_add_plugin(): error: Duplicate plugin <http://zynaddsubfx.sourceforge.net>
lilv_world_add_plugin(): error: ... found in file:///home/simon/.lv2/ZynAddSubFX.lv2/
lilv_world_add_plugin(): error: ... and      file:///usr/lib64/lv2/ZynAddSubFX.lv2/
Plugin:       http://zynaddsubfx.sourceforge.net
No appropriate UI found
etc...
```

Carla-rack keeps the "Show custom UI" button disabled.

**Comment by fundamental** [comment]
If you have an already installed instance of the zynaddsubfx lv2 plugin the one from the demo will conflict with it. You can get around this by setting the LV2_PATH.

Assuming you installed the demo to .lv2/ZynAddSubFX.lv2 you should be able to launch it via
'LV2_PATH=/home/simon/.lv2/ jalv.gtk http://zynaddsubfx.sourceforge.net'

**Comment by simonvanderveldt** [comment]
> If you have an already installed instance of the zynaddsubfx lv2 plugin the one from the demo will conflict with it. You can get around this by setting the LV2_PATH.
> 
> Assuming you installed the demo to .lv2/ZynAddSubFX.lv2 you should be able to launch it via
> 'LV2_PATH=/home/simon/.lv2/ jalv.gtk http://zynaddsubfx.sourceforge.net'

Thanks for the hint! This has gotten rid of the "Duplicate plugin" errors.

Unfortunately still the same result regarding the UI.
The only relevant thing I found was the following from `jalv.qt`:

```
suil error: Unable to open UI library /home/simon/.lv2//ZynAddSubFX.lv2/ZynAddSubFX_ui.so (/home/simon/.lv2//ZynAddSubFX.lv2/ZynAddSubFX_ui.so: undefined symbol: glEnd)
```

**Comment by fundamental** [comment]
I've been testing under jalv.gtk which didn't seem to have a problem with the missing GL linker flag, but it should work fine in jalv.qt now that the linker flag has been added. If you'll check the demo page the demo-linux package has been updated.  If there are any issues there please reopen the issue.
