### ISSUE TITLE
Rename "distorsion" to "distortion"

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#71]
I believe this is a typo.

![selection_088](https://cloud.githubusercontent.com/assets/491704/22405959/55a513f6-e64a-11e6-86a6-aaf0b238807b.png)

**Comment by fundamental** [comment]
Fixed via https://github.com/zynaddsubfx/zynaddsubfx/commit/bc068710ee642c0cf419d5e9e46573b2ed146e27
The updated metadata needs to be used to regenerate the json schema for the next release.

**Comment by mikobuntu** [comment]
Possibly related : I remember seeing a few source files in the ZASF core which contained the word 'Spliter' , this could/should be 'Split' .. or perhaps "splinter" ( maybe even "Separator" ), but I believe "Spliter" is not a real word ( In the English Dictionary at least ).

**Comment by fundamental** [comment]
@mikobuntu There's the external program 'spliter' (should be spelled splitter) distributed with the fltk portion of zynaddsubfx which does not have a new UI. After grepping the zyn/zyn-fusion source, there should not be any label in the zyn-fusion UI which matches the regular expression /.*[sS]plit.*/

**Comment by ssj71** [comment]
totally unrelated but "distorsion" is still prevalent in rakarrack source and documentation. I never realized it came from upstream :)

**Comment by afentoe** [comment]
The pulldown menu is fixed now, but in 3.0.3 the effect title is still displayed as Distorsion:

![distorsion wrong title](https://user-images.githubusercontent.com/44930277/51426096-e7af5900-1be5-11e9-8af0-55d53ae8428d.png)

**Comment by pdesaulniers** [comment]
@afentoe Thanks! Fixed in https://github.com/mruby-zest/mruby-zest/commit/276d7ee4de8fb010a563bd36b37164c8d6e5d127 .
