### ISSUE TITLE
Enabling parts from the mian window level

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#73]
I found out that one **can select** a different part with this 4x4 dial in the main window (which is cool!), but one **cannot enable/disable** parts through that. I have to open the Mixer and enable new parts from there.

![selection_097](https://cloud.githubusercontent.com/assets/491704/22630442/6ab4d1b8-ebfa-11e6-9df1-c462f6cdd423.png)

It'd be very convenient.

**Comment by fundamental** [comment]
Do you have a preference on *how* a part can be enabled/disabled?

left/right/middle click based different actions?
keyboard modifier based different actions?
additional controls?
something else?

**Comment by unfa** [comment]
I would personally prefer middle mouse button to toggle the parts on/off. Probably a hint about that could be dropped in the GUI "help" region.

**Comment by fundamental** [comment]
This enhancement is in the soon to be released -rc.
