### ISSUE TITLE
Cannot midi learn?

### ISSUE THREAD

**Issue by RealmportalMC** [zynaddsubfx/zyn-fusion-issues#87]
On windows 10  home 64 bit, Reaper 5.40 and zyn-fusion 3.0.2rc1 for windows

how do i use automation???

**Comment by fundamental** [comment]
To use midi learn:

1. Hold the control key to start midi learning (or click the midi learn indicator at the top of the window)
2. Click on the knob or slider that you're interested in learning
2b. Release the control key  (or click the midi learn indicator)
3. Supply the plugin with new MIDI CC events (from a physical controller or in-host source)
4. The first MIDI CC event received by zyn is bound to the knob or slider which midi learning has been initiated on

This MIDI CC based workflow has received criticism in the past and there are plans to move to more traditional VST parameters in the near-term. This is documented in https://github.com/zynaddsubfx/zyn-fusion-issues/issues/20 and https://github.com/zynaddsubfx/zyn-fusion-issues/issues/77 . The latter issue's direction has been summarized in a proposal at http://zynaddsubfx.sourceforge.net/proposals/automation/parameter-automation-future-plan.html . As the proposal is a work-in-progress any feedback is appreciated.
