### ISSUE TITLE
Implement DnD for automation of knobs

### ISSUE THREAD

**Issue by JohannesLorenz** [zynaddsubfx/zyn-fusion-issues#88]
# Background

DAWs such as LMMS have the possibility to automate its knobs with controllers or editors, e.g. a volume knob could be automated with a sine wave. Automating *zyn* knobs (with the automation source being LMMS) require DnD (Drag and Drop) functionality.

# First Milestone
The implementation should follow the [DnD](https://freedesktop.org/wiki/Specifications/XDND/) protocol. For understanding the meanings of mimetypes and other data (currently *not needed*), the [Qt Docs](http://doc.qt.io/qt-4.8/dnd.html) might be helpful (this is what the LMMS side will use for implementation). Extremely helpful: [qdnd_x11.cpp](http://code.qt.io/cgit/qt/qt.git/tree/src/gui/kernel/qdnd_x11.cpp) - Search this file e.g. for "XdndSelection".

The exact steps are, according to the Steps in the XDND specification:

0. See spec.
1. Applies to LMMS only (nothing to do for zyn).
2. See spec.
3. LMMS only.
4. Receive XdndPosition. Most stuff can be ignored, since all we want to do is store our knob's OSC path (and don't care about what the source actually does with it). The action ("data.l[4]") however shall be "XdndActionLink". For everything else, see spec.
5. See spec (almost trivial)
6. LMMS only.
7. LMMS only
8. See spec. The data must not be fetched from the XdndDropEvent, since we only need to store the OSC path and do nothing else (if this would need to be done in the future, see the lines beginning at qdnd.cpp:1925, the mimetype would be "application/x-lmms-stringpair" and the string would be "automatable_model:<some discardable integer>"). So, when the XdndDropEvent is received, inform the MiddleWare about the knob's path and let it store it (e.g. "/last_dnd /path/to/knob").

# Second Milestone
After DnD is implemented, it's simple: LMMS sends a message ("/last_dnd") and receives exactly that path, which shall cause zyn to flush the last dnd path. LMMS can then connect the string to zyn.

In order to know which Zyn LMMS needs to send the "/last_dnd" message, nothing needs to be done. LMMS can broadcast "/last_dnd" to all zyn instances which have a GUI (usually a small amount), and only one will return a non-empty string.

**Comment by fundamental** [comment]
After some quick hacking I have XdndAware, XdndPossition, and XdndDrop working in the pugl fork within the zest toolkit. Next up making XdndPossition update the in window cursor and then letting XdndDrop trigger the desired osc message

**Comment by fundamental** [comment]
The UI can now emit the "/last_dnd" message when a drag and drop event happens over a knob/slider.

**Comment by JohannesLorenz** [comment]
This has already been fixed a year ago in test_libversion.c :tada:
