### ISSUE TITLE
No text cursor visible for typing

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#89]
It's a bit hard to know that you're about to type in text, because there is no typing cursor in the text fields.
This applies to Part Names and for Filenames as well.

![spectacle l12978](https://cloud.githubusercontent.com/assets/491704/25313124/93d1688a-2828-11e7-9ad1-91179543c2b2.png)

**Comment by fundamental** [comment]
I had thought that filenames got a (mostly cosmetic) cursor in the last update, but perhaps I was mistaken. The functionality is certainly missing for part names. See also #16

**Comment by fundamental** [comment]
The cursor now has been added to the LabelButton shown in the original screenshot.
