### ISSUE TITLE
GUI crashing when displaying Distortion effect controls

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#90]
In the 3.0.2 Linux 64-version, LV2 plugin hosted in Carla (also in newest version), Zyn-Fusion GUI crashes whenever I add a Distortion effect. The effect is added and I then cannot disable it. When I restart the GUI to disable the effect it will crash every time when I get to the screen that'll show me the distortion effect controls.

**Comment by fundamental** [comment]
This bug was fixed on April 19th and will be in the next update
