### ISSUE TITLE
GUI crashing when trying to save Master settings file

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#91]
3.0.2, LV2 via Carla host.

I tried saving my work with *File > Save Master* , the GUI crashes, and the XMZ file isn't saved.

**Comment by fundamental** [comment]
I believe this bug was fixed on April 24th and it should be in the next
update.

Saving should still be possible if you use your mouse to hit the enter button.
Hitting the keyboard enter button ended up running some out-of-date code
leading to the crash.

**Comment by fundamental** [comment]
It seems to be fixed in current revisions, let me know if it's still an issue.
