### ISSUE TITLE
linux_install.sh defines a wrong interpreter and won't run

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#92]
The `linux_install.sh` file starts with `#!/usr/bash` instead of `#!/bin/bash` which makes it fail to run in my system (Linux Mint).

I had to run `bash ./linux_install.sh` to execute it.

**Comment by fundamental** [comment]
Thanks for spotting the mistake.
It is now fixed.

**Comment by unfa** [comment]
I guess it can be closed now.
