### ISSUE TITLE
ADDsynth > VCE > Frequency > Coarse works in 0..1 range, not -1..+1

### ISSUE THREAD

**Issue by unfa** [zynaddsubfx/zyn-fusion-issues#94]
ADDsynth > VCE > Frequency > Coarse.

The knob's default value is not centered, but all-left. And it only can make the pitch higher, you can't use it to lower the pitch.

**Comment by fundamental** [comment]
It appears the wrong OSC binding was used for the voice coarse detune. This has been corrected locally, but the fix needs to be tested. The fix should also resolve #95

**Comment by pdesaulniers** [comment]
Seems fine. However:
- Double-clicking on coarse doesn't reset the value
- I suppose the coarse knobs in global and modulation panels should also start in a centered position?

**Comment by fundamental** [comment]
> Double-clicking on coarse doesn't reset the value

Sounds like a missing default metadata within the zyn core and thus the OSC schema that osc-bridge uses for resetting

> I suppose the coarse knobs in global and modulation panels should also start in a centered position?

Usually, I'd say yes to that sort of question, though some of zyn's parameter ranges are a bit strange.

**Comment by pdesaulniers** [comment]
Should be fixed by https://github.com/zynaddsubfx/zynaddsubfx/commit/56ffc34b3ae3362e7ee1dc947f3e53f918dfec89 .

(assuming the weird parameter ranges are not an issue :p)
