### ISSUE TITLE
DRM?

### ISSUE THREAD

**Issue by shiftypenguin** [zynaddsubfx/zyn-fusion-issues#96]
Can't find any info about the status of copy protection. Does it exist in the purchased copy?

**Comment by fundamental** [comment]
The demo version is restricted to 10 minutes of use (per application startup). The full version is restricted to a single user license.

Is there some limitation in particular that you're concerned about?

**Comment by shiftypenguin** [comment]
Well I was going to use it on a box without Internet and didn't know if that would be an issue.

**Comment by fundamental** [comment]
Ah, yeah. There's no phone-home mechanism which would stop you from using it, so it should be fine.
