### ISSUE TITLE
What about a Raspberry Pi (ARM CPU) version?

### ISSUE THREAD

**Issue by ghost** [zynaddsubfx/zyn-fusion-issues#97]
Hi,
I'm using a Raspberry Pi as virtual synth with ZynAdd actually. All sequenced with a Kilpatrick Carbon hardware MIDI sequencer.
Zyn-fysion is really awesome (GUI and external control) and can be a real killer synth on Raspberry Pi.
If i buy zyn-fusion now, how to be certain that it work on ARM a day? Open source or not. 
I do not use x86 computer at all.
Thanks
Bruno

**Comment by fundamental** [comment]
The current releases do not include ARM builds. The next release (in a week or two) will include source along with the (x86_64) binaries if you're interested in building a personal binary on an architecture other than x86_64.

That said, I've tested Linux x86/x86_64, Windows x86_64, and OSX x86_64, but I have not tested the software on ARM at this point. It should work without modification, but this has not been verified; nor has the CPU/GPU load of the UI been verified on a Raspberry Pi.

The more typical workflow that users have talked about is hosting a zynaddsubfx instance on a Raspberry Pi and controlling it with the user interface hosted on a secondary (and not always connected) machine which would typically be a x86_64 machine. It will be interesting to hear some more about more strictly Raspberry Pi workflows/machines.

**Comment by ghost** [comment]
Nice to hear that. Now i´m giving you some money on gumroad.
Raspberry Pi 3 work perfectly with ZynAddSubFX with old gui. I think that the new gui work too.
I´ll try when you release the code.
Thanks

**Comment by unfa** [comment]
So the sources will be released soon? Awesome!

I wonder if one could use Zyn-Fusion in a Mod Duo with the ARM version. Will it also come as an LV2 plugin fro ARM platform?
